// ==========================================
// COMPREHENSIVE DATASET FOR 50 PREHISTORIC CREATURES (DINO 50)
// ==========================================

export interface JapaneseSegment {
  text: string;
  ruby?: string;
}

export interface QuizQuestion {
  japaneseSegments: JapaneseSegment[];
  keyword: string;
  keywordHintJa: string;
  options: {
    text: string;
    translation: string;
  }[];
  correctIndex: number;
  explanationJa: string;
  explanationEn: string;
}

export interface DinosaurChallenge {
  id: string;
  nameJa: string;
  nameEn: string;
  scientificName: string;
  phonetic: string;
  phoneticKatakana: string;
  era: 'Triassic' | 'Jurassic' | 'Cretaceous';
  diet: 'Herbivore' | 'Carnivore' | 'Piscivore';
  length: string;
  meaning: string;
  audioPitch: number;
  triviaJa: string;
  triviaEn: string;
  speciesName: string;
  speciesMeaning: string;
  speciesNote: string;
  vocabQuestion: QuizQuestion;
  basicQuestion: QuizQuestion;
}

// ==========================================
// PRONUNCIATION MAP
// ==========================================
export const PRONUNCIATION_MAP: Record<string, string> = {
  'Carnivore': 'カーニボア',
  'Herbivore': 'ハービボア',
  'Piscivore': 'ピシボア',
  'Predator': 'プレデター',
  'Prey': 'プレイ',
  'Apex': 'エイペックス',
  'Theropod': 'テロポッド',
  'Sauropod': 'サウロポッド',
  'Ceratopsian': 'ケラトシアン',
  'Pterosaur': 'テロサール',
  'Plesiosaur': 'プレシオサール',
  'Mosasaur': 'モササール',
  'Ichthyosaur': 'イクチオサール',
  'Horn': 'ホーン',
  'Claw': 'クロー',
  'Armor': 'アーマー',
  'Sail': 'セイル',
  'Feather': 'フェザー',
  'Scale': 'スケイル',
  'Tooth': 'トゥース',
  'Wing': 'ウィング',
  'Neck': 'ネック',
  'Flipper': 'フリッパー',
  'Crest': 'クレスト',
  'Dome': 'ドーム',
  'Frill': 'フリル',
  'Thumb': 'サム',
  'Giant': 'ジャイアント',
  'Sickle': 'シックル',
  'Beak': 'ビーク',
  'Snout': 'スナウト',
  'Hunter': 'ハンター',
  'Spine': 'スパイン',
  'Shark': 'シャーク',
  'Tusk': 'タスク',
  'Saber': 'サーベル',
  'Cat': 'キャット',
  'Beast': 'ビースト',
  'Tall': 'トール',
  'Trunk': 'トランク',
  'Bottom': 'ボトム',
  'Swimmer': 'スイマー',
  'Skull': 'スカル',
  'Teeth': 'ティース',
  'Cold': 'コールド',
  'Shrimp': 'シュリンプ',
  'Five': 'ファイブ',
  'Plated': 'プレイテッド',
  'Warm': 'ウォーム',
  'Bite': 'バイト',
  'Fish': 'フィッシュ',
  'Flight': 'フライト',
  'Fossil': 'フォシル',
  'Bone': 'ボーン',
  'Tail': 'テイル',
  'Spike': 'スパイク',
  'Club': 'クラブ',
  'Glider': 'グライダー',
  'Filter': 'フィルター',
  'Plankton': 'プランクトン'
};

interface RawDino {
  id: string;
  nameJa: string;
  nameEn: string;
  sci: string;
  phonetic: string;
  phoneticKatakana: string;
  era: 'Triassic' | 'Jurassic' | 'Cretaceous';
  diet: 'Herbivore' | 'Carnivore' | 'Piscivore';
  length: string;
  meaning: string;
  pitch: number;
  triviaJa: string;
  triviaEn: string;
  speciesName: string;
  speciesMeaning: string;
  speciesNote: string;
  expertKW: string;
  expertHint: string;
  expertSegs: string[][];
  expertOpts: string[][];
  expertCorrect: number;
  expertExplJa: string;
  expertExplEn: string;
  basicKW: string;
  basicHint: string;
  basicSegs: string[][];
  basicOpts: string[][];
  basicCorrect: number;
  basicExplJa: string;
  basicExplEn: string;
}

// ==========================================
// RAW DINOSAURS DATASET (50 CREATURES)
// ==========================================
const RAW_DINOS: RawDino[] = [
  // 1
  {
    id: 'tyrannosaurus',
    nameJa: 'T.レックス',
    nameEn: 'Tyrannosaurus rex',
    sci: 'Tyrannosaurus rex',
    phonetic: '/tɪˌrænəˈsɔːrəs rɛks/',
    phoneticKatakana: 'ティラノサウルス・レックス',
    era: 'Cretaceous',
    diet: 'Carnivore',
    length: '約12〜13m',
    meaning: '暴君トカゲの王',
    pitch: 0.3,
    triviaJa: '白亜紀末期の北アメリカに君臨した最強の肉食恐竜で、非常に強力な顎と鋭い歯を持っていました。',
    triviaEn: 'Tyrannosaurus rex was one of the most powerful apex predators of the Cretaceous.',
    speciesName: 'rex',
    speciesMeaning: 'ラテン語で「王（King）」を意味する。最高峰の強さを表す。',
    speciesNote: '💡白亜紀末期の北アメリカに君臨した最強の肉食恐竜の王',
    expertKW: 'Apex',
    expertHint: '頂点',
    expertSegs: [['T.レックスは白亜紀の生態系の「'], ['頂点', 'ちょうてん'], ['」に君臨した肉食恐竜です。英語で？']],
    expertOpts: [['Apex', '頂点（えいぺっくす）'], ['Bottom', '底部'], ['Middle', '中間'], ['Edge', '端']],
    expertCorrect: 0,
    expertExplJa: 'Apexは生態系やピラミッドの頂点を意味します。',
    expertExplEn: 'Apex refers to the top or highest part of a hierarchy.',
    basicKW: 'Bite',
    basicHint: '噛む',
    basicSegs: [['骨をも砕く強力な「'], ['噛む', 'かむ'], ['」力を持っていました。この基礎英語は？']],
    basicOpts: [['Sing', '歌う'], ['Bite', '噛む（ばいと）'], ['Jump', '跳ぶ'], ['Swim', '泳ぐ']],
    basicCorrect: 1,
    basicExplJa: 'Biteは歯で噛み付く、噛む力を意味します。',
    basicExplEn: 'Bite means to use teeth to seize or crush.'
  },
  // 2
  {
    id: 'spinosaurus',
    nameJa: 'スピノサウルス',
    nameEn: 'Spinosaurus',
    sci: 'Spinosaurus aegyptiacus',
    phonetic: '/ˌspiːnoʊˈsɔːrəs/',
    phoneticKatakana: 'スピノサウルス',
    era: 'Cretaceous',
    diet: 'Piscivore',
    length: '約14〜18m',
    meaning: 'トゲトカゲ',
    pitch: 0.35,
    triviaJa: '背中に巨大な帆（棘）を持ち、水生適応して魚を主食にしていた史上最大級の肉食恐竜です。',
    triviaEn: 'Spinosaurus was a giant semi-aquatic dinosaur with a sail on its back.',
    speciesName: 'aegyptiacus',
    speciesMeaning: 'ラテン語で「エジプトの」という意味で、最初の化石がエジプトで発見されたことに由来する。',
    speciesNote: '💡背中の巨大な帆と水生適応が特徴の史上最大級の肉食恐竜',
    expertKW: 'Sail',
    expertHint: '帆',
    expertSegs: [['背中にある、骨と皮膚でできた巨大な「'], ['帆', 'ほ'], ['」が非常に有名です。この英語は？']],
    expertOpts: [['Sail', '帆（せいる）'], ['Wing', '翼'], ['Horn', '角'], ['Plate', '板']],
    expertCorrect: 0,
    expertExplJa: 'Sailは船の帆や背中の帆状の突起を指します。',
    expertExplEn: 'Sail is a structural extension resembling a ship sail.',
    basicKW: 'Fish',
    basicHint: '魚',
    basicSegs: [['スピノサウルスは川や湖で「'], ['魚', 'さかな'], ['」を捕まえて食べていました。この基礎英語は？']],
    basicOpts: [['Bird', '鳥'], ['Fish', '魚（ふぃっしゅ）'], ['Cat', '猫'], ['Dog', '犬']],
    basicCorrect: 1,
    basicExplJa: 'Fishは水中を泳ぐ魚を意味します。',
    basicExplEn: 'Fish is a vertebrate living in water.'
  },
  // 3
  {
    id: 'triceratops',
    nameJa: 'トリケラトプス',
    nameEn: 'Triceratops',
    sci: 'Triceratops horridus',
    phonetic: '/traɪˈsɛrətɒps/',
    phoneticKatakana: 'トリケラトプス',
    era: 'Cretaceous',
    diet: 'Herbivore',
    length: '約8〜9m',
    meaning: '3本の角の顔',
    pitch: 0.5,
    triviaJa: '顔に3本の立派な角と大きなフリルを持ち、ティラノサウルスとも戦った代表的な草食恐竜です。',
    triviaEn: 'Triceratops was a large herbivorous dinosaur with three prominent facial horns.',
    speciesName: 'horridus',
    speciesMeaning: 'ラテン語で「ざらざらした、恐ろしい、トゲトゲした」という意味で、頑丈な外見に由来する。',
    speciesNote: '💡3本の角と大きなフリルを持つ白亜紀を代表する草食恐竜',
    expertKW: 'Horn',
    expertHint: '角',
    expertSegs: [['頭部には頑丈な「'], ['角', 'つの'], ['」が3本生えていました。この英語はどれ？']],
    expertOpts: [['Horn', '角（ほーん）'], ['Claw', '爪'], ['Tail', '尾'], ['Tooth', '歯']],
    expertCorrect: 0,
    expertExplJa: 'Hornは動物の頭部にある角を指します。',
    expertExplEn: 'Horn is a hard pointed protrusion on the head.',
    basicKW: 'Herbivore',
    basicHint: '草食動物',
    basicSegs: [['トリケラトプスは植物を食べる「'], ['草食動物', 'そうしょくどうぶつ'], ['」でした。この英語は？']],
    basicOpts: [['Carnivore', '肉食動物'], ['Herbivore', '草食動物（はーびぼあ）'], ['Omnivore', '雑食'], ['Insectivore', '食虫']],
    basicCorrect: 1,
    basicExplJa: 'Herbivoreは草や植物を食べる草食動物を表します。',
    basicExplEn: 'Herbivore is an animal feeding on plants.'
  },
  // 4
  {
    id: 'pteranodon',
    nameJa: 'プテラノドン',
    nameEn: 'Pteranodon',
    sci: 'Pteranodon longiceps',
    phonetic: '/təˈrænədɒn/',
    phoneticKatakana: 'プテラノドン',
    era: 'Cretaceous',
    diet: 'Piscivore',
    length: '翼開長約7〜9m',
    meaning: '歯のない翼',
    pitch: 0.6,
    triviaJa: '恐竜ではなく、歯のないクチバシと後頭部の大きなトサカが特徴の有名な翼竜です。',
    triviaEn: 'Pteranodon was a large pterosaur with a prominent crest and toothless beak.',
    speciesName: 'longiceps',
    speciesMeaning: 'ラテン語の longus（長い）と caput（頭）の合成語で、「長い頭」を意味する。',
    speciesNote: '💡大きなトサカと歯のないクチバシを持つ有名な翼竜',
    expertKW: 'Crest',
    expertHint: 'トサカ・冠',
    expertSegs: [['頭の後ろには特徴的な大きな「'], ['トサカ', 'とさか'], ['」がありました。この英語は？']],
    expertOpts: [['Crest', '冠・トサカ（くれすと）'], ['Wing', '翼'], ['Tail', '尾'], ['Horn', '角']],
    expertCorrect: 0,
    expertExplJa: 'Crestは鳥や爬虫類の頭部にあるトサカを指します。',
    expertExplEn: 'Crest is a comb or tuft on the head of an animal.',
    basicKW: 'Flight',
    basicHint: '飛行',
    basicSegs: [['大きな翼を広げて空を「'], ['飛行', 'ひこう'], ['」していました。この基礎英語は？']],
    basicOpts: [['Swim', '泳ぐ'], ['Flight', '飛行（ふらいと）'], ['Walk', '歩く'], ['Run', '走る']],
    basicCorrect: 1,
    basicExplJa: 'Flightは空を飛ぶこと、飛行を意味します。',
    basicExplEn: 'Flight is the act of flying through the air.'
  },
  // 5
  {
    id: 'velociraptor',
    nameJa: 'ヴェロキラプトル',
    nameEn: 'Velociraptor',
    sci: 'Velociraptor mongoliensis',
    phonetic: '/vəˈlɒsɪræptər/',
    phoneticKatakana: 'ヴェロキラプトル',
    era: 'Cretaceous',
    diet: 'Carnivore',
    length: '約1.8〜2m',
    meaning: '素早い泥棒',
    pitch: 0.7,
    triviaJa: '全身が羽毛に覆われ、後ろ足の鎌のような鋭い鉤爪が武器の機敏な小型肉食恐竜です。',
    triviaEn: 'Velociraptor was a feathered dromaeosaurid known for its intelligence and sickle claws.',
    speciesName: 'mongoliensis',
    speciesMeaning: '発見地である「モンゴル（Mongolia）」に由来する地理的名称。',
    speciesNote: '💡羽毛に覆われた機敏な知能派の小型肉食恐竜',
    expertKW: 'Feather',
    expertHint: '羽毛',
    expertSegs: [['最新の研究で、体はフワフワした「'], ['羽毛', 'うもう'], ['」に覆われていたことが分かっています。この英語は？']],
    expertOpts: [['Feather', '羽毛（ふぇざー）'], ['Scale', 'ウロコ'], ['Armor', '鎧'], ['Skin', '皮膚']],
    expertCorrect: 0,
    expertExplJa: 'Featherは鳥類や羽毛恐竜の羽を意味します。',
    expertExplEn: 'Feather is one of the light growths forming bird coatings.',
    basicKW: 'Claw',
    basicHint: '鉤爪',
    basicSegs: [['足の指には鋭い「'], ['鉤爪', 'かぎづめ'], ['」がありました。この英語はどれ？']],
    basicOpts: [['Tooth', '歯'], ['Claw', '爪（くろー）'], ['Horn', '角'], ['Bone', '骨']],
    basicCorrect: 1,
    basicExplJa: 'Clawは動物や鳥の鋭い爪を指します。',
    basicExplEn: 'Claw means a curved sharp nail on a foot.'
  },
  // 6
  {
    id: 'aucasaurus',
    nameJa: 'アウカサウルス',
    nameEn: 'Aucasaurus',
    sci: 'Aucasaurus garridoi',
    phonetic: '/ˌɔːkəˈsɔːrəs/',
    phoneticKatakana: 'アウカサウルス',
    era: 'Cretaceous',
    diet: 'Carnivore',
    length: '約5〜6m',
    meaning: 'アウカのトカゲ',
    pitch: 0.5,
    triviaJa: '南米アルゼンチンのアウカ・マフエボで発見された、非常に短い前肢を持つアベリサウルス科の肉食恐竜です。',
    triviaEn: 'Aucasaurus was an abelisaurid theropod from South America with remarkably short arms.',
    speciesName: 'garridoi',
    speciesMeaning: 'アルゼンチンの化石発見者アルベルト・ガリード（Alberto Garrido）氏への献名。',
    speciesNote: '💡南米で発見された非常に短い前肢を持つアベリサウルス科の肉食恐竜',
    expertKW: 'Theropod',
    expertHint: '獣脚類',
    expertSegs: [['二足歩行の肉食恐竜である「'], ['獣脚類', 'じゅうきゃくるい'], ['」に分類されます。英語で？']],
    expertOpts: [['Theropod', '獣脚類（てろぽっど）'], ['Sauropod', '竜脚類'], ['Ceratopsian', '角竜'], ['Ornithischian', '鳥盤類']],
    expertCorrect: 0,
    expertExplJa: 'Theropodは獣脚類（二足歩行の肉食恐竜グループ）を意味します。',
    expertExplEn: 'Theropod is a carnivorous dinosaur group characterized by bipedalism.',
    basicKW: 'Short',
    basicHint: '短い',
    basicSegs: [['アウカサウルスは前足が非常に「'], ['短い', 'みじかい'], ['」という特徴がありました。この英語は？']],
    basicOpts: [['Long', '長い'], ['Short', '短い（しょーと）'], ['Big', '大きい'], ['Tall', '高い']],
    basicCorrect: 1,
    basicExplJa: 'Shortは長さや距離が短いことを表します。',
    basicExplEn: 'Short means measuring a small distance from end to end.'
  },
  // 7
  {
    id: 'argentinosaurus',
    nameJa: 'アルゼンチノサウルス',
    nameEn: 'Argentinosaurus',
    sci: 'Argentinosaurus huinculensis',
    phonetic: '/ˌɑːrdʒəntiːnoʊˈsɔːrəs/',
    phoneticKatakana: 'アルゼンチノサウルス',
    era: 'Cretaceous',
    diet: 'Herbivore',
    length: '約30〜40m',
    meaning: 'アルゼンチンのトカゲ',
    pitch: 0.25,
    triviaJa: '地球上で最も重く巨大な陸上動物の一つとされる、圧倒的な巨体を誇る超大型竜脚類です。',
    triviaEn: 'Argentinosaurus was one of the largest and heaviest land animals in Earth history.',
    speciesName: 'huinculensis',
    speciesMeaning: '発見地であるアルゼンチンのプラサ・ウインクル（Plaza Huincul）層に由来する。',
    speciesNote: '💡地球上で最も重く巨大な陸上動物の一つとされる超大型竜脚類',
    expertKW: 'Sauropod',
    expertHint: '竜脚類',
    expertSegs: [['長い首と四足歩行を持つ巨大草食恐竜「'], ['竜脚類', 'りゅうきゃくるい'], ['」の代表格です。英語で？']],
    expertOpts: [['Sauropod', '竜脚類（さうろぽっど）'], ['Theropod', '獣脚類'], ['Pterosaur', '翼竜'], ['Ankylosaur', '鎧竜']],
    expertCorrect: 0,
    expertExplJa: 'Sauropodは首と尾が長い巨大な四足歩行の草食恐竜グループを指します。',
    expertExplEn: 'Sauropod is a group of huge long-necked herbivorous dinosaurs.',
    basicKW: 'Giant',
    basicHint: '巨大な',
    basicSegs: [['アルゼンチノサウルスは圧倒的に「'], ['巨大な', 'きょだいな'], ['」体躯を持っていました。この英語は？']],
    basicOpts: [['Tiny', 'ちいさな'], ['Giant', '巨大な（じゃいあんと）'], ['Fast', '速い'], ['Weak', '弱い']],
    basicCorrect: 1,
    basicExplJa: 'Giantは並外れて大きいこと、巨大なものを意味します。',
    basicExplEn: 'Giant means of very great size or force.'
  },
  // 8
  {
    id: 'giganotosaurus',
    nameJa: 'ギガノトサウルス',
    nameEn: 'Giganotosaurus',
    sci: 'Giganotosaurus carolinii',
    phonetic: '/ˌdʒɪɡəˌnoʊtəˈsɔːrəs/',
    phoneticKatakana: 'ギガノトサウルス',
    era: 'Cretaceous',
    diet: 'Carnivore',
    length: '約12〜13m',
    meaning: '巨大な南方のトカゲ',
    pitch: 0.32,
    triviaJa: '白亜紀の南アメリカに生息していた、T.レックスに匹敵する最大級の肉食恐竜です。',
    triviaEn: 'Giganotosaurus was a massive apex carnivorous dinosaur from Cretaceous South America.',
    speciesName: 'carolinii',
    speciesMeaning: '発見者であるアマチュア化石ハンターのロドルフォ・カロリニ（Rubén Carolini）氏への献名。',
    speciesNote: '💡白亜紀の南米に生息していたT.レックスに匹敵する最大級の肉食恐竜',
    expertKW: 'Predator',
    expertHint: '捕食者',
    expertSegs: [['南米大陸の生態系で頂点に君臨した強力な「'], ['捕食者', 'ほしょくしゃ'], ['」でした。英語で？']],
    expertOpts: [['Predator', '捕食者（ぷれでたー）'], ['Prey', '獲物'], ['Herbivore', '草食動物'], ['Scavenger', 'スカベンジャー']],
    expertCorrect: 0,
    expertExplJa: 'Predatorは他の動物を捕食する肉食獣や捕食者を意味します。',
    expertExplEn: 'Predator is an animal that preys on others.',
    basicKW: 'Heavy',
    basicHint: '重い',
    basicSegs: [['体重が数トンもある非常に「'], ['重い', 'おもい'], ['」肉食恐竜でした。この基礎英語は？']],
    basicOpts: [['Light', '軽い'], ['Heavy', '重い（へびー）'], ['Soft', '柔らかい'], ['Fast', '速い']],
    basicCorrect: 1,
    basicExplJa: 'Heavyは質量や体重が大きい、重いことを表します。',
    basicExplEn: 'Heavy means of great weight.'
  },
  // 9
  {
    id: 'liopleurodon',
    nameJa: 'リオプレウロドン',
    nameEn: 'Liopleurodon',
    sci: 'Liopleurodon ferox',
    phonetic: '/ˌlaɪoʊˈplʊərədɒn/',
    phoneticKatakana: 'リオプレウロドン',
    era: 'Jurassic',
    diet: 'Carnivore',
    length: '約6〜7m',
    meaning: '滑らかな側面の歯',
    pitch: 0.4,
    triviaJa: 'ジュラ紀の海の王者として知られる大型首長竜（プリオサウルス類）で、強靭な4枚のひれで泳ぎました。',
    triviaEn: 'Liopleurodon was a massive apex pliosaur that ruled the Jurassic seas.',
    speciesName: 'ferox',
    speciesMeaning: 'ラテン語で「獰猛な、野性的な、残忍な」を意味する。',
    speciesNote: '💡ジュラ紀の海の王者として知られる強靭な海生爬虫類',
    expertKW: 'Plesiosaur',
    expertHint: '首長竜',
    expertSegs: [['4枚のひれと長い体を持つ海生爬虫類「'], ['首長竜', 'くびながりゅう'], ['」の仲間です。英語で？']],
    expertOpts: [['Plesiosaur', '首長竜（ぷれじおさーる）'], ['Pterosaur', '翼竜'], ['Dinosaurs', '恐竜'], ['Fish', '魚']],
    expertCorrect: 0,
    expertExplJa: 'Plesiosaurは中生代の海に生息した首長竜類を指します。',
    expertExplEn: 'Plesiosaur is a large marine reptile with four flippers.',
    basicKW: 'Swimmer',
    basicHint: '泳ぎ手',
    basicSegs: [['4枚の強力なひれを使って海を素早く進む「'], ['泳ぎ手', 'およぎて'], ['」でした。この英語は？']],
    basicOpts: [['Runner', '走者'], ['Swimmer', '泳ぎ手（すいまー）'], ['Flyer', '飛行者'], ['Jumper', '跳躍者']],
    basicCorrect: 1,
    basicExplJa: 'Swimmerは水泳をする人や生物（泳ぎ手）を意味します。',
    basicExplEn: 'Swimmer is a person or animal that swims.'
  },
  // 10
  {
    id: 'brachiosaurus',
    nameJa: 'ブラキオサウルス',
    nameEn: 'Brachiosaurus',
    sci: 'Brachiosaurus altithorax',
    phonetic: '/ˌbrækiəˈsɔːrəs/',
    phoneticKatakana: 'ブラキオサウルス',
    era: 'Jurassic',
    diet: 'Herbivore',
    length: '約25〜26m',
    meaning: '腕のトカゲ',
    pitch: 0.45,
    triviaJa: '前足が後ろ足よりも長く、キリンのように高い木の葉を食べていた巨大な首長草食恐竜です。',
    triviaEn: 'Brachiosaurus was a giant sauropod with front limbs longer than its hind legs.',
    speciesName: 'altithorax',
    speciesMeaning: 'ラテン語の altus（高い）とギリシャ語の thorax（胸）に由来し、「高い胸」を意味する。',
    speciesNote: '💡前足が後ろ足より長く、高い木の葉を食べていた巨大な首長草食恐竜',
    expertKW: 'Neck',
    expertHint: '首',
    expertSegs: [['木の高いところの葉を食べるため、非常に長い「'], ['首', 'くび'], ['」を持っていました。この英語は？']],
    expertOpts: [['Neck', '首（ねっく）'], ['Tail', '尾'], ['Leg', '足'], ['Arm', '腕']],
    expertCorrect: 0,
    expertExplJa: 'Neckは頭と胴体をつなぐ「首」を意味します。',
    expertExplEn: 'Neck is the part of the body connecting the head to the rest of the body.',
    basicKW: 'Tall',
    basicHint: '高い',
    basicSegs: [['キリンのように背が高く「'], ['高い', 'たかい'], ['」体高をしていました。この基礎英語は？']],
    basicOpts: [['Short', '低い'], ['Tall', '高い（とーる）'], ['Small', '小さい'], ['Wide', '広い']],
    basicCorrect: 1,
    basicExplJa: 'Tallは高さがある、背が高いことを表します。',
    basicExplEn: 'Tall means of great height.'
  },
  // 11
  {
    id: 'iguanodon',
    nameJa: 'イグアノドン',
    nameEn: 'Iguanodon',
    sci: 'Iguanodon bernissartensis',
    phonetic: '/ɪˈɡwɑːnədɒn/',
    phoneticKatakana: 'イグアノドン',
    era: 'Cretaceous',
    diet: 'Herbivore',
    length: '約9〜10m',
    meaning: 'イグアナの歯',
    pitch: 0.52,
    triviaJa: '親指の尖ったスパイクと、四足歩行と二足歩行を切り替えて移動できた有名な草食恐竜です。',
    triviaEn: 'Iguanodon was an early-discovered herbivore with thumb spikes and flexible stance.',
    speciesName: 'bernissartensis',
    speciesMeaning: 'ベルギーのベルニッサール（Bernissart）炭鉱で多数の化石が発見されたことに由来する。',
    speciesNote: '💡親指のスパイクと柔軟な四足・二足歩行を持つ代表的な草食恐竜',
    expertKW: 'Thumb',
    expertHint: '親指',
    expertSegs: [['前足の「'], ['親指', 'おやゆび'], ['」には武器になる鋭いスパイクがありました。この英語は？']],
    expertOpts: [['Thumb', '親指（さむ）'], ['Toe', '足指'], ['Claw', '爪'], ['Finger', '指']],
    expertCorrect: 0,
    expertExplJa: 'Thumbは手の親指を意味します。',
    expertExplEn: 'Thumb is the short thick first digit of the human hand or corresponding animal digit.',
    basicKW: 'Walk',
    basicHint: '歩く',
    basicSegs: [['二足でも四足でも地面を「'], ['歩く', 'あるく'], ['」ことができました。この基礎英語は？']],
    basicOpts: [['Fly', '飛ぶ'], ['Walk', '歩く（うぉーく）'], ['Swim', '泳ぐ'], ['Sleep', '眠る']],
    basicCorrect: 1,
    basicExplJa: 'Walkは足を使って歩く動作を意味します。',
    basicExplEn: 'Walk means to move at a regular pace by lifting and setting down each foot.'
  },
  // 12
  {
    id: 'allosaurus',
    nameJa: 'アロサウルス',
    nameEn: 'Allosaurus',
    sci: 'Allosaurus fragilis',
    phonetic: '/ˌæləˈsɔːrəs/',
    phoneticKatakana: 'アロサウルス',
    era: 'Jurassic',
    diet: 'Carnivore',
    length: '約8〜12m',
    meaning: '異様なトカゲ',
    pitch: 0.38,
    triviaJa: 'ジュラ紀後期を代表する肉食恐竜で、目の上の小さな突起と頑丈な顎で獲物を狩りました。',
    triviaEn: 'Allosaurus was the dominant apex carnivore of the Late Jurassic.',
    speciesName: 'fragilis',
    speciesMeaning: 'ラテン語で「壊れやすい、もろい」を意味し、脊椎骨が繊細な構造であったことに由来する。',
    speciesNote: '💡ジュラ紀後期を代表する生態系の頂点に立った肉食恐竜',
    expertKW: 'Hunter',
    expertHint: 'ハンター',
    expertSegs: [['ジュラ紀の森で強力な「'], ['ハンター', 'はんたー'], ['」として恐れられていました。この英語は？']],
    expertOpts: [['Hunter', 'ハンター（はんたー）'], ['Prey', '獲物'], ['Guard', '警備員'], ['Pet', 'ペット']],
    expertCorrect: 0,
    expertExplJa: 'Hunterは獲物を探し求めて狩る者を意味します。',
    expertExplEn: 'Hunter is a person or animal that hunts game or other wild animals.',
    basicKW: 'Tooth',
    basicHint: '歯',
    basicSegs: [['鋸歯状の鋭い「'], ['歯', 'は'], ['」で獲物の肉を切り裂きました。この基礎英語は？']],
    basicOpts: [['Eye', '目'], ['Tooth', '歯（とぅーす）'], ['Ear', '耳'], ['Nose', '鼻']],
    basicCorrect: 1,
    basicExplJa: 'Toothは口内にある歯を意味します。',
    basicExplEn: 'Tooth is each of the hard, calcareous structures in the jaws.'
  },
  // 13
  {
    id: 'stegosaurus',
    nameJa: 'ステゴサウルス',
    nameEn: 'Stegosaurus',
    sci: 'Stegosaurus stenops',
    phonetic: '/ˌstɛɡəˈsɔːrəs/',
    phoneticKatakana: 'ステゴサウルス',
    era: 'Jurassic',
    diet: 'Herbivore',
    length: '約9m',
    meaning: '屋根に覆われたトカゲ',
    pitch: 0.48,
    triviaJa: '背中に並んだ大きな板状の骨と、尻尾の4本の鋭いトゲが特徴的な草食恐竜です。',
    triviaEn: 'Stegosaurus was a herbivore featuring distinctive back plates and spiked tail.',
    speciesName: 'stenops',
    speciesMeaning: 'ギリシャ語の stenos（狭い）と ops（顔）に由来し、「狭い顔」を意味する。',
    speciesNote: '💡背中の板と尻尾のスパイクが特徴的なジュラ紀の草食恐竜',
    expertKW: 'Plate',
    expertHint: '板',
    expertSegs: [['背中には体温調節などの役割があったとされる骨の「'], ['板', 'いた'], ['」が並んでいました。英語で？']],
    expertOpts: [['Plate', '板（ぷれーと）'], ['Sail', '帆'], ['Wing', '翼'], ['Horn', '角']],
    expertCorrect: 0,
    expertExplJa: 'Plateは平らな板状の構造を指します。',
    expertExplEn: 'Plate is a smooth, flat, thin piece of material.',
    basicKW: 'Tail',
    basicHint: '尻尾',
    basicSegs: [['尻尾の先端には危険なトゲのある「'], ['尻尾', 'しっぽ'], ['」がありました。この英語は？']],
    basicOpts: [['Head', '頭'], ['Tail', '尾（ているとれんど）'], ['Neck', '首'], ['Back', '背中']],
    basicCorrect: 1,
    basicExplJa: 'Tailは動物の後端にある尾を意味します。',
    basicExplEn: 'Tail is the rear part of an animal body extending beyond the torso.'
  },
  // 14
  {
    id: 'quetzalcoatlus',
    nameJa: 'ケツァルコアトルス',
    nameEn: 'Quetzalcoatlus',
    sci: 'Quetzalcoatlus northropi',
    phonetic: '/ˌkɛtsɑːlkoʊˈwɑːtləs/',
    phoneticKatakana: 'ケツァルコアトルス',
    era: 'Cretaceous',
    diet: 'Carnivore',
    length: '翼開長約10〜11m',
    meaning: '羽毛ある蛇神ケツァルコアトル',
    pitch: 0.65,
    triviaJa: 'キリンほどの背丈とセスナ機並みの翼幅を持つ、史上最大の飛行生物（翼竜）です。',
    triviaEn: 'Quetzalcoatlus was the largest flying animal in Earth history, as tall as a giraffe.',
    speciesName: 'northropi',
    speciesMeaning: 'ノースロップ・グラマン社の創立者ジョン・ノースロップ（John Northrop）氏にちなむ。',
    speciesNote: '💡キリンほどの背丈とセスナ機並みの翼幅を持つ史上最大の飛行生物',
    expertKW: 'Pterosaur',
    expertHint: '翼竜',
    expertSegs: [['恐竜とは異なる空飛ぶ爬虫類「'], ['翼竜', 'よくりゅう'], ['」の最大種です。英語で？']],
    expertOpts: [['Pterosaur', '翼竜（てろさーる）'], ['Bird', '鳥'], ['Dragon', 'ドラゴン'], ['Bat', 'コウモリ']],
    expertCorrect: 0,
    expertExplJa: 'Pterosaurは中生代の空を支配した翼竜類を意味します。',
    expertExplEn: 'Pterosaur is an extinct flying reptile of the Mesozoic.',
    basicKW: 'Sky',
    basicHint: '空',
    basicSegs: [['巨大な翼で悠々と「'], ['空', 'そら'], ['」を飛んでいました。この基礎英語は？']],
    basicOpts: [['Sea', '海'], ['Sky', '空（すかい）'], ['Land', '陸'], ['Cave', '洞窟']],
    basicCorrect: 1,
    basicExplJa: 'Skyは頭上に広がる大空、空を意味します。',
    basicExplEn: 'Sky is the region of the atmosphere seen from the earth.'
  },
  // 15
  {
    id: 'plesiosaurus',
    nameJa: 'プレシオサウルス',
    nameEn: 'Plesiosaurus',
    sci: 'Plesiosaurus dolichodeirus',
    phonetic: '/ˌpliːziəˈsɔːrəs/',
    phoneticKatakana: 'プレシオサウルス',
    era: 'Jurassic',
    diet: 'Piscivore',
    length: '約3〜5m',
    meaning: 'トカゲに近いもの',
    pitch: 0.55,
    triviaJa: '長い首と4枚のパドルのようなひれを持ち、海中を優雅に泳いで魚を捕食していた代表的な首長竜です。',
    triviaEn: 'Plesiosaurus was a classic long-necked marine reptile of Jurassic seas.',
    speciesName: 'dolichodeirus',
    speciesMeaning: 'ギリシャ語の dolichos（長い）と deire（首）に由来し、「長い首」を意味する。',
    speciesNote: '💡長い首と4枚のひれを持つジュラ紀の代表的な首長竜',
    expertKW: 'Flipper',
    expertHint: 'ひれ',
    expertSegs: [['海中を泳ぐために4枚の強力な「'], ['ひれ', 'ひれ'], ['」を持っていました。英語で？']],
    expertOpts: [['Flipper', 'ひれ（ふりっぱー）'], ['Wing', '翼'], ['Leg', '足'], ['Arm', '腕']],
    expertCorrect: 0,
    expertExplJa: 'Flipperは海生動物の遊泳用のひれを指します。',
    expertExplEn: 'Flipper is a broad flat limb used for swimming by marine animals.',
    basicKW: 'Sea',
    basicHint: '海',
    basicSegs: [['太古の「'], ['海', 'うみ'], ['」を泳ぎ回っていました。この基礎英語は？']],
    basicOpts: [['Mountain', '山'], ['Sea', '海（しー）'], ['Desert', '砂漠'], ['Forest', '森']],
    basicCorrect: 1,
    basicExplJa: 'Seaは地球上の海水をたたえた海域を意味します。',
    basicExplEn: 'Sea is the expanse of salt water covering most of the earth surface.'
  },
  // 16
  {
    id: 'tarbosaurus',
    nameJa: 'タルボサウルス',
    nameEn: 'Tarbosaurus',
    sci: 'Tarbosaurus bataar',
    phonetic: '/ˌtɑːrbəˈsɔːrəs/',
    phoneticKatakana: 'タルボサウルス',
    era: 'Cretaceous',
    diet: 'Carnivore',
    length: '約10〜12m',
    meaning: '恐るべきトカゲ',
    pitch: 0.33,
    triviaJa: 'アジアの白亜紀末期に君臨した大型肉食恐竜で、T.レックスの近縁種にあたります。',
    triviaEn: 'Tarbosaurus was the apex predator of Cretaceous Asia, closely related to T. rex.',
    speciesName: 'bataar',
    speciesMeaning: 'モンゴル語の baatar（勇者、英雄）に由来する。',
    speciesNote: '💡アジアの白亜紀末期に君臨したT.レックス近縁の大型肉食恐竜',
    expertKW: 'Predator',
    expertHint: '捕食者',
    expertSegs: [['アジアの生態系で頂点に立った肉食の「'], ['捕食者', 'ほしょくしゃ'], ['」です。英語で？']],
    expertOpts: [['Predator', '捕食者（ぷれでたー）'], ['Prey', '獲物'], ['Herbivore', '草食動物'], ['Omnivore', '雑食']],
    expertCorrect: 0,
    expertExplJa: 'Predatorは捕食者を意味します。',
    expertExplEn: 'Predator is an animal that preys on others.',
    basicKW: 'Strong',
    basicHint: '強い',
    basicSegs: [['頑丈な頭骨と非常に「'], ['強い', 'つよい'], ['」顎を持っていました。この基礎英語は？']],
    basicOpts: [['Weak', '弱い'], ['Strong', '強い（すとろんぐ）'], ['Slow', '遅い'], ['Soft', '柔らかい']],
    basicCorrect: 1,
    basicExplJa: 'Strongは力や耐久力があることを表します。',
    basicExplEn: 'Strong means having great power or physical strength.'
  },
  // 17
  {
    id: 'nothosaurus',
    nameJa: 'ノトサウルス',
    nameEn: 'Nothosaurus',
    sci: 'Nothosaurus mirabilis',
    phonetic: '/ˌnoʊθəˈsɔːrəs/',
    phoneticKatakana: 'ノトサウルス',
    era: 'Triassic',
    diet: 'Piscivore',
    length: '約4〜7m',
    meaning: '偽りのトカゲ',
    pitch: 0.42,
    triviaJa: 'トリアス紀の海や海岸で暮らしていた原始的な海生爬虫類で、水かきのある足で泳ぎました。',
    triviaEn: 'Nothosaurus was an amphibious marine reptile of the Triassic with webbed feet.',
    speciesName: 'mirabilis',
    speciesMeaning: 'ラテン語で「驚異的な、素晴らしい」を意味する。',
    speciesNote: '💡トリアス紀の海や海岸で暮らしていた原始的な海生爬虫類',
    expertKW: 'Reptile',
    expertHint: '爬虫類',
    expertSegs: [['恐竜とは異なるグループの古代の「'], ['爬虫類', 'はちゅうるい'], ['」です。英語で？']],
    expertOpts: [['Reptile', '爬虫類（れぷたいーる）'], ['Mammal', '哺乳類'], ['Amphibian', '両生類'], ['Fish', '魚類']],
    expertCorrect: 0,
    expertExplJa: 'Reptileはトカゲやヘビなどの爬虫類を指します。',
    expertExplEn: 'Reptile is a vertebrate animal of a class that includes snakes and lizards.',
    basicKW: 'Swim',
    basicHint: '泳ぐ',
    basicSegs: [['浅い海を自在に「'], ['泳ぐ', 'およぐ'], ['」ことができました。この基礎英語は？']],
    basicOpts: [['Run', '走る'], ['Swim', '泳ぐ（すいむ）'], ['Climb', '登る'], ['Fly', '飛ぶ']],
    basicCorrect: 1,
    basicExplJa: 'Swimは水中を泳ぐ動作を意味します。',
    basicExplEn: 'Swim means to propel the body through water by limb movements.'
  },
  // 18
  {
    id: 'dakosaurus',
    nameJa: 'ダコサウルス',
    nameEn: 'Dakosaurus',
    sci: 'Dakosaurus andiniensis',
    phonetic: '/ˌdækəˈsɔːrəs/',
    phoneticKatakana: 'ダコサウルス',
    era: 'Jurassic',
    diet: 'Carnivore',
    length: '約4〜6m',
    meaning: '噛み裂くトカゲ',
    pitch: 0.39,
    triviaJa: '海に適応したワクロスの仲間で、丸い頭骨と強力な歯を持つジュラ紀の海のハンターです。',
    triviaEn: 'Dakosaurus was a fully marine crocodyliform with a skull like a theropod.',
    speciesName: 'andiniensis',
    speciesMeaning: '南米のアンデス山脈（Andes）に由来する地理的名称。',
    speciesNote: '💡完全に海に適応し、ゴジラの愛称でも知られるワクロスの仲間',
    expertKW: 'Marine',
    expertHint: '海の',
    expertSegs: [['陸を離れて完全に「'], ['海の', 'うみの'], ['」環境に適応したワニの近縁です。英語で？']],
    expertOpts: [['Marine', '海の（まりーん）'], ['Forest', '森の'], ['Desert', '砂漠の'], ['Sky', '空の']],
    expertCorrect: 0,
    expertExplJa: 'Marineは海や海洋に関連することを意味します。',
    expertExplEn: 'Marine relates to or found in the sea.',
    basicKW: 'Sharp',
    basicHint: '鋭い',
    basicSegs: [['ギザギザした「'], ['鋭い', 'するどい'], ['」歯で獲物を引き裂きました。この基礎英語は？']],
    basicOpts: [['Dull', '鈍い'], ['Sharp', '鋭い（しゃーぷ）'], ['Soft', '柔らかい'], ['Flat', '平らな']],
    basicCorrect: 1,
    basicExplJa: 'Sharpは先端や刃が鋭利であることを表します。',
    basicExplEn: 'Sharp having a thin cutting edge or a tapering point.'
  },
  // 19
  {
    id: 'ankylosaurus',
    nameJa: 'アンキロサウルス',
    nameEn: 'Ankylosaurus',
    sci: 'Ankylosaurus magniventris',
    phonetic: '/æŋˌkaɪləˈsɔːrəs/',
    phoneticKatakana: 'アンキロサウルス',
    era: 'Cretaceous',
    diet: 'Herbivore',
    length: '約6〜8m',
    meaning: '連結したトカゲ',
    pitch: 0.46,
    triviaJa: '全身が頑丈な骨の装甲に覆われ、尻尾の先端には強烈なこん棒を持つ「生きた戦車」です。',
    triviaEn: 'Ankylosaurus was a heavily armored herbivore with a devastating tail club.',
    speciesName: 'magniventris',
    speciesMeaning: 'ラテン語の magnus（大きい）と venter（腹部）に由来し、「大きな腹」を意味する。',
    speciesNote: '💡全身が骨の装甲と尻尾のこん棒に覆われた「生きた戦車」',
    expertKW: 'Armor',
    expertHint: '装甲・鎧',
    expertSegs: [['肉食恐竜の攻撃を防ぐ頑丈な「'], ['装甲', 'そうこう'], ['」を持っていました。英語で？']],
    expertOpts: [['Armor', '装甲・鎧（あーまー）'], ['Feather', '羽毛'], ['Skin', '皮膚'], ['Cloth', '服']],
    expertCorrect: 0,
    expertExplJa: 'Armorは身体を保護する鎧や装甲を指します。',
    expertExplEn: 'Armor is the metal coverings formerly used to protect the body.',
    basicKW: 'Club',
    basicHint: 'こん棒',
    basicSegs: [['尻尾の先には敵を叩きのめす「'], ['こん棒', 'こんぼう'], ['」がありました。この英語は？']],
    basicOpts: [['Sword', '剣'], ['Club', 'こん棒（くらぶ）'], ['Bow', '弓'], ['Shield', '盾']],
    basicCorrect: 1,
    basicExplJa: 'Clubは棍棒や重い打撃武器を意味します。',
    basicExplEn: 'Club is a heavy stick with a thicker end used as a weapon.'
  },
  // 20
  {
    id: 'pachycephalosaurus',
    nameJa: 'パキケファロサウルス',
    nameEn: 'Pachycephalosaurus',
    sci: 'Pachycephalosaurus wyomingensis',
    phonetic: '/ˌpækɪˌsɛfəloʊˈsɔːrəs/',
    phoneticKatakana: 'パキケファロサウルス',
    era: 'Cretaceous',
    diet: 'Herbivore',
    length: '約4〜5m',
    meaning: '厚い頭のトカゲ',
    pitch: 0.49,
    triviaJa: '頭骨の頂上がドーム状に分厚く隆起しており、頭突きで仲間と競い合ったとされる植物食恐竜です。',
    triviaEn: 'Pachycephalosaurus was a bipedal herbivore famous for its immensely thick domed skull.',
    speciesName: 'wyomingensis',
    speciesMeaning: 'アメリカのワイオミング州（Wyoming）で化石が発見されたことに由来する。',
    speciesNote: '💡ドーム状の厚い頭骨を持ち、頭突きで知られる草食恐竜',
    expertKW: 'Dome',
    expertHint: 'ドーム',
    expertSegs: [['頭部には丸く盛り上がった「'], ['ドーム', 'どーむ'], ['」状の分厚い骨がありました。英語で？']],
    expertOpts: [['Dome', 'ドーム（どーむ）'], ['Flat', '平ら'], ['Cone', '円錐'], ['Box', '箱']],
    expertCorrect: 0,
    expertExplJa: 'Domeは半球状の屋根や突起を意味します。',
    expertExplEn: 'Dome is a rounded vault forming the roof of a structure or head.',
    basicKW: 'Head',
    basicHint: '頭',
    basicSegs: [['分厚い骨で守られた頑丈な「'], ['頭', 'あたま'], ['」を持っていました。この基礎英語は？']],
    basicOpts: [['Foot', '足'], ['Head', '頭（へっど）'], ['Hand', '手'], ['Arm', '腕']],
    basicCorrect: 1,
    basicExplJa: 'Headは動物の頭部を意味します。',
    basicExplEn: 'Head is the upper part of the human body or front/upper part of an animal.'
  },
  // 21
  {
    id: 'mosasaurus',
    nameJa: 'モササウルス',
    nameEn: 'Mosasaurus',
    sci: 'Mosasaurus hoffmannii',
    phonetic: '/ˌmoʊzəˈsɔːrəs/',
    phoneticKatakana: 'モササウルス',
    era: 'Cretaceous',
    diet: 'Carnivore',
    length: '約14〜17m',
    meaning: 'マース川のトカゲ',
    pitch: 0.31,
    triviaJa: '白亜紀末期の海に君臨した最強の海生トカゲで、あらゆる獲物を呑み込む巨大な顎を持っていました。',
    triviaEn: 'Mosasaurus was the ultimate apex predator of the Late Cretaceous oceans.',
    speciesName: 'hoffmannii',
    speciesMeaning: '最初の化石標本を発見したオランダの医師・古生物学者チャールズ・ホフマン（Jean Hofmann）氏への献名。',
    speciesNote: '💡白亜紀後期の海に君臨した最強最大の海生トカゲ類',
    expertKW: 'Ocean',
    expertHint: '海洋・海',
    expertSegs: [['白亜紀の広大な「'], ['海洋', 'かいよう'], ['」の頂点に君臨した王者です。英語で？']],
    expertOpts: [['Ocean', '海・海洋（おーしゃん）'], ['River', '川'], ['Lake', '湖'], ['Pond', '池']],
    expertCorrect: 0,
    expertExplJa: 'Oceanは地球上の広大な海を意味します。',
    expertExplEn: 'Ocean is a very large expanse of sea.',
    basicKW: 'Jaws',
    basicHint: '顎',
    basicSegs: [['獲物を逃さない強力な「'], ['顎', 'あご'], ['」を持っていました。この基礎英語は？']],
    basicOpts: [['Tail', '尾'], ['Jaws', '顎（じょーず）'], ['Wing', '翼'], ['Fin', '鰭']],
    basicCorrect: 1,
    basicExplJa: 'Jawsは動物の口を構成する上下の顎を意味します。',
    basicExplEn: 'Jaws are the upper and lower structures holding the teeth in the mouth.'
  },
  // 22
  {
    id: 'ichthyosaurus',
    nameJa: 'イクチオサウルス',
    nameEn: 'Ichthyosaurus',
    sci: 'Ichthyosaurus communis',
    phonetic: '/ˌɪkθiːəˈsɔːrəs/',
    phoneticKatakana: 'イクチオサウルス',
    era: 'Jurassic',
    diet: 'Piscivore',
    length: '約2m',
    meaning: '魚のトカゲ',
    pitch: 0.58,
    triviaJa: '現代のイルカに驚くほど似た流線型の体を持ち、魚やイカを素早く追いかけて食べた魚竜です。',
    triviaEn: 'Ichthyosaurus was a dolphin-like marine reptile that thrived in Jurassic seas.',
    speciesName: 'communis',
    speciesMeaning: 'ラテン語で「普通の、一般的な」を意味し、多くの化石が発見されることに由来する。',
    speciesNote: '💡現代のイルカに驚くほど似た流線型の体を持つ魚竜',
    expertKW: 'Ichthyosaur',
    expertHint: '魚竜',
    expertSegs: [['魚のような体型に進化をした海生爬虫類「'], ['魚竜', 'ぎょりゅう'], ['」の代表です。英語で？']],
    expertOpts: [['Ichthyosaur', '魚竜（いくちおさーる）'], ['Plesiosaur', '首長竜'], ['Pterosaur', '翼竜'], ['Dinosaur', '恐竜']],
    expertCorrect: 0,
    expertExplJa: 'Ichthyosaurは魚に似た姿の海生爬虫類である魚竜を指します。',
    expertExplEn: 'Ichthyosaur is an extinct marine reptile resembling a dolphin or fish.',
    basicKW: 'Fast',
    basicHint: '速い',
    basicSegs: [['海中を非常に「'], ['速い', 'はやい'], ['」スピードで泳ぐことができました。この基礎英語は？']],
    basicOpts: [['Slow', '遅い'], ['Fast', '速い（ふぁすと）'], ['Heavy', '重い'], ['Quiet', '静かな']],
    basicCorrect: 1,
    basicExplJa: 'Fastは移動速度が速いことを表します。',
    basicExplEn: 'Fast moving or capable of moving at high speed.'
  },
  // 23
  {
    id: 'tylosaurus',
    nameJa: 'ティロサウルス',
    nameEn: 'Tylosaurus',
    sci: 'Tylosaurus proriger',
    phonetic: '/ˌtaɪləˈsɔːrəs/',
    phoneticKatakana: 'ティロサウルス',
    era: 'Cretaceous',
    diet: 'Carnivore',
    length: '約12〜14m',
    meaning: '突起のあるトカゲ',
    pitch: 0.34,
    triviaJa: '吻部（鼻先）が硬く突出し、内陸海で他の海生動物をも襲った白亜紀の大型モササウルス類です。',
    triviaEn: 'Tylosaurus was a giant predatory mosasaur with a reinforced ramming snout.',
    speciesName: 'proriger',
    speciesMeaning: 'ラテン語の prora（船首）と gero（運ぶ）に由来し、「船首を持つ者」を意味する。',
    speciesNote: '💡鼻先の硬い突起で獲物に体当たりして狩りをした大型モササウルス類',
    expertKW: 'Snout',
    expertHint: '吻・鼻先',
    expertSegs: [['頭部の先端には硬い「'], ['鼻先', 'はなさき'], ['」があり、体当たりに使われました。英語で？']],
    expertOpts: [['Snout', '鼻先・吻（すなうと）'], ['Ear', '耳'], ['Tail', '尾'], ['Fin', '鰭']],
    expertCorrect: 0,
    expertExplJa: 'Snoutは動物の突き出た鼻先や吻を意味します。',
    expertExplEn: 'Snout is the projecting nose and mouth of an animal.',
    basicKW: 'Hunt',
    basicHint: '狩る',
    basicSegs: [['内陸の海で様々な獲物を「'], ['狩る', 'かる'], ['」海のハンターでした。この基礎英語は？']],
    basicOpts: [['Sleep', '眠る'], ['Hunt', '狩る（はんと）'], ['Grow', '成長する'], ['Hide', '隠れる']],
    basicCorrect: 1,
    basicExplJa: 'Huntは獲物を追って狩猟することを意味します。',
    basicExplEn: 'Hunt means to pursue and kill wild animals for food or sport.'
  },
  // 24
  {
    id: 'utahraptor',
    nameJa: 'ユタラプトル',
    nameEn: 'Utahraptor',
    sci: 'Utahraptor ostrommaysi',
    phonetic: '/ˈjuːtəˌræptər/',
    phoneticKatakana: 'ユタラプトル',
    era: 'Cretaceous',
    diet: 'Carnivore',
    length: '約5〜7m',
    meaning: 'ユタの泥棒',
    pitch: 0.43,
    triviaJa: 'ヴェロキラプトルよりもはるかに巨大で、足の鎌爪で獲物を仕留めたドロマエオサウルス類の大型種です。',
    triviaEn: 'Utahraptor was the largest dromaeosaurid dinosaur, armed with massive sickle claws.',
    speciesName: 'ostrommaysi',
    speciesMeaning: '恐竜研究の巨匠ジョン・オストロム（John Ostrom）氏とクリス・メイズ（Chris Mays）氏にちなむ。',
    speciesNote: '💡巨大なサイズと強力なシックルクローを持つドロマエオサウルス類の大型種',
    expertKW: 'Sickle',
    expertHint: '鎌',
    expertSegs: [['足の指には鎌のような「'], ['鎌', 'かま'], ['」状の恐ろしい鉤爪がありました。英語で？']],
    expertOpts: [['Sickle', '鎌（しっくる）'], ['Hammer', 'ハンマー'], ['Knife', 'ナイフ'], ['Spear', '槍']],
    expertCorrect: 0,
    expertExplJa: 'Sickleは草を刈る農具の「鎌」を意味します。',
    expertExplEn: 'Sickle is a short handled farming tool with a semicircular blade.',
    basicKW: 'Kill',
    basicHint: '仕留める・殺す',
    basicSegs: [['強力な武器で獲物を確実に「'], ['仕留める', 'しとめる'], ['」肉食恐竜でした。この基礎英語は？']],
    basicOpts: [['Save', '救う'], ['Kill', '仕留める（きる）'], ['Feed', '育てる'], ['Help', '助ける']],
    basicCorrect: 1,
    basicExplJa: 'Killは生命を終わらせる、仕留めることを意味します。',
    basicExplEn: 'Kill means to put to an end to the life of a person or animal.'
  },
  // 25
  {
    id: 'deinonychus',
    nameJa: 'デイノニクス',
    nameEn: 'Deinonychus',
    sci: 'Deinonychus antirrhopus',
    phonetic: '/daɪˈnɒnɪkəs/',
    phoneticKatakana: 'デイノニクス',
    era: 'Cretaceous',
    diet: 'Carnivore',
    length: '約3〜4m',
    meaning: '恐ろしい爪',
    pitch: 0.51,
    triviaJa: '後ろ足の第2趾にある大きな鉤爪が名前の由来で、集団でより大きな獲物を狩ったとされる小型肉食恐竜です。',
    triviaEn: 'Deinonychus was an agile, pack-hunting dromaeosaurid with deadly foot claws.',
    speciesName: 'antirrhopus',
    speciesMeaning: 'ギリシャ語で「釣り合いを取る、均衡させる」という意味で、硬い尻尾がバランスをとっていたことに由来する。',
    speciesNote: '💡恐ろしい鉤爪を持ち、恐竜学の革命のきっかけとなった小型肉食恐竜',
    expertKW: 'Dromaeosaur',
    expertHint: 'ドロマエオサウルス類',
    expertSegs: [['羽毛に覆われ機敏に動く「'], ['ドロマエオサウルス類', 'どろまえおさうるするい'], ['」に属します。英語で？']],
    expertOpts: [['Dromaeosaur', 'ドロマエオサウルス（どろまえおさうる）'], ['Sauropod', '竜脚類'], ['Ceratopsian', '角竜'], ['Stegosaur', '剣竜']],
    expertCorrect: 0,
    expertExplJa: 'Dromaeosaurはラプトル類を含む二足歩行の肉食恐竜群を指します。',
    expertExplEn: 'Dromaeosaur is a member of agile carnivorous theropod dinosaurs.',
    basicKW: 'Pack',
    basicHint: '群れ',
    basicSegs: [['仲間と「'], ['群れ', 'むれ'], ['」を作って協力して狩りをしていました。この基礎英語は？']],
    basicOpts: [['Pack', '群れ（ぱっく）'], ['Alone', '単独'], ['House', '家'], ['Team', 'チーム']],
    basicCorrect: 1,
    basicExplJa: 'Packは動物の群れやパックを意味します。',
    basicExplEn: 'Pack is a group of wild animals such as wolves or raptors hunting together.'
  },
  // 26
  {
    id: 'diplodocus',
    nameJa: 'ディプロドクス',
    nameEn: 'Diplodocus',
    sci: 'Diplodocus carnegii',
    phonetic: '/dɪˈplɒdəvəs/',
    phoneticKatakana: 'ディプロドクス',
    era: 'Jurassic',
    diet: 'Herbivore',
    length: '約25〜27m',
    meaning: '二重の梁（はり）',
    pitch: 0.41,
    triviaJa: '極端に長い首と鞭のような尾を持つ、ジュラ紀を代表する超大型の竜脚類です。',
    triviaEn: 'Diplodocus was a very long sauropod with a slender whip-like tail.',
    speciesName: 'carnegii',
    speciesMeaning: '化石を発見・寄贈した大実業家アンドリュー・カーネギー（Andrew Carnegie）氏への献名。',
    speciesNote: '💡鞭のような長い尾と極めて長い首を持つジュラ紀の超大型草食恐竜',
    expertKW: 'Whip',
    expertHint: '鞭（ムチ）',
    expertSegs: [['尻尾の先端はまるで「'], ['鞭', 'むち'], ['」のように細くしなやかでした。英語で？']],
    expertOpts: [['Whip', '鞭（ほいっぷ）'], ['Rope', '綱'], ['Wire', '針金'], ['Stick', '棒']],
    expertCorrect: 0,
    expertExplJa: 'Whipはしなやかな鞭を意味します。',
    expertExplEn: 'Whip is a strip of leather or cord fastened to a handle for striking.',
    basicKW: 'Long',
    basicHint: '長い',
    basicSegs: [['首も尻尾も非常に「'], ['長い', 'ながい'], ['」体をしていました。この基礎英語は？']],
    basicOpts: [['Short', '短い'], ['Long', '長い（ろんぐ）'], ['High', '高い'], ['Wide', '広い']],
    basicCorrect: 1,
    basicExplJa: 'Longは長さや距離が長いことを表します。',
    basicExplEn: 'Long measuring a great distance from end to end.'
  },
  // 27
  {
    id: 'elasmosaurus',
    nameJa: 'エラスモサウルス',
    nameEn: 'Elasmosaurus',
    sci: 'Elasmosaurus platyurus',
    phonetic: '/ɪˌlæzməˈsɔːrəs/',
    phoneticKatakana: 'エラスモサウルス',
    era: 'Cretaceous',
    diet: 'Piscivore',
    length: '約14m',
    meaning: '薄い板のトカゲ',
    pitch: 0.47,
    triviaJa: '全長の半分以上が首という極端に長い首を持ち、ネッシーのモデルとしても有名な首長竜です。',
    triviaEn: 'Elasmosaurus was a plesiosaur with an extraordinarily long neck comprising over 70 vertebrae.',
    speciesName: 'platyurus',
    speciesMeaning: 'ギリシャ語の platys（平らな）と oura（尾）に由来し、「平らな尾」を意味する。',
    speciesNote: '💡全長の半分以上が首という極端に長い首を持つ白亜紀の首長竜',
    expertKW: 'Vertebra',
    expertHint: '脊椎・骨',
    expertSegs: [['首には70個以上もの「'], ['脊椎', 'せきつい'], ['」（骨）が連なっていました。英語で？']],
    expertOpts: [['Vertebra', '脊椎（ヴぁーてぶら）'], ['Rib', '肋骨'], ['Skull', '頭骨'], ['Tooth', '歯']],
    expertCorrect: 0,
    expertExplJa: 'Vertebraは背骨を構成する個々の骨（椎骨）を指します。',
    expertExplEn: 'Vertebra is each of the series of small bones forming the backbone.',
    basicKW: 'Water',
    basicHint: '水',
    basicSegs: [['生涯のほとんどを「'], ['水', 'みず'], ['」の中で過ごしました。この基礎英語は？']],
    basicOpts: [['Fire', '火'], ['Water', '水（うぉーたー）'], ['Air', '空気'], ['Earth', '土']],
    basicCorrect: 1,
    basicExplJa: 'Waterは川や海を構成する水分や水を意味します。',
    basicExplEn: 'Water is a transparent, odorless, tasteless liquid forming seas and rivers.'
  },
  // 28
  {
    id: 'acrocanthosaurus',
    nameJa: 'アクロカントサウルス',
    nameEn: 'Acrocanthosaurus',
    sci: 'Acrocanthosaurus atokensis',
    phonetic: '/ˌækroʊˌkænθəˈsɔːrəs/',
    phoneticKatakana: 'アクロカントサウルス',
    era: 'Cretaceous',
    diet: 'Carnivore',
    length: '約11〜12m',
    meaning: '高いトゲを持つトカゲ',
    pitch: 0.36,
    triviaJa: '背中の脊椎骨から高く突き出た棘突起が特徴で、筋肉の隆起によって帆やこんぶのような形を作っていた肉食恐竜です。',
    triviaEn: 'Acrocanthosaurus was a large theropod distinguished by high neural spines along its back.',
    speciesName: 'atokensis',
    speciesMeaning: 'アメリカ・オクラホマ州のアトカ郡（Atoka County）に由来する地理的名称。',
    speciesNote: '💡背骨から高く伸びる棘突起が特徴的な大型肉食恐竜',
    expertKW: 'Spine',
    expertHint: '背骨・棘',
    expertSegs: [['背中には高く伸びた骨の「'], ['棘', 'とげ'], ['」が並んでいました。英語で？']],
    expertOpts: [['Spine', '背骨・棘（すぱいん）'], ['Tail', '尾'], ['Arm', '腕'], ['Leg', '脚']],
    expertCorrect: 0,
    expertExplJa: 'Spineは脊椎や動物のトゲ状突起を意味します。',
    expertExplEn: 'Spine is a series of vertebrae extending from the skull to the pelvis.',
    basicKW: 'Muscle',
    basicHint: '筋肉',
    basicSegs: [['背中の突起の間には発達した「'], ['筋肉', 'きんにく'], ['」がついていました。この基礎英語は？']],
    basicOpts: [['Skin', '皮膚'], ['Muscle', '筋肉（まっすると）'], ['Fat', '脂肪'], ['Blood', '血液']],
    basicCorrect: 1,
    basicExplJa: 'Muscleは体を動かす筋肉組織を意味します。',
    basicExplEn: 'Muscle is a band or bundle of fibrous tissue in a human or animal body that has the ability to contract.'
  },
  // 29
  {
    id: 'carnotaurus',
    nameJa: 'カルノタウルス',
    nameEn: 'Carnotaurus',
    sci: 'Carnotaurus sastrei',
    phonetic: '/ˌkɑːrnoʊˈtɔːrəs/',
    phoneticKatakana: 'カルノタウルス',
    era: 'Cretaceous',
    diet: 'Carnivore',
    length: '約7〜9m',
    meaning: '肉食の牛',
    pitch: 0.37,
    triviaJa: '頭部に牛のような2本の角が生えており、非常に短い前足と優れた走行能力を持っていた南米の肉食恐竜です。',
    triviaEn: 'Carnotaurus was a distinctive predatory dinosaur with two bull-like horns and vestigial arms.',
    speciesName: 'sastrei',
    speciesMeaning: '化石を発見した牧場主アンヘル・サストレ（Ángel Sastre）氏への献名。',
    speciesNote: '💡頭部の2本の角と極端に短い前足が特徴的な肉食恐竜',
    expertKW: 'Bull',
    expertHint: '雄牛',
    expertSegs: [['頭に生えた角が「'], ['雄牛', 'おうし'], ['」に似ていることから名付けられました。英語で？']],
    expertOpts: [['Bull', '雄牛（ぶるー）'], ['Horse', '馬'], ['Deer', '鹿'], ['Lion', '獅子']],
    expertCorrect: 0,
    expertExplJa: 'Bullはオスの牛を意味します。',
    expertExplEn: 'Bull is an uncastrated adult male bovine animal.',
    basicKW: 'Run',
    basicHint: '走る',
    basicSegs: [['頑丈な後足で俊敏に「'], ['走る', 'はしる'], ['」ことができました。この基礎英語は？']],
    basicOpts: [['Sleep', '眠る'], ['Run', '走る（らん）'], ['Swim', '泳ぐ'], ['Fly', '飛ぶ']],
    basicCorrect: 1,
    basicExplJa: 'Runは素早く走る動作を意味します。',
    basicExplEn: 'Run means to move at a speed faster than a walk.'
  },
  // 30
  {
    id: 'kronosaurus',
    nameJa: 'クロノサウルス',
    nameEn: 'Kronosaurus',
    sci: 'Kronosaurus queenslandicus',
    phonetic: '/ˌkroʊnəˈsɔːrəs/',
    phoneticKatakana: 'クロノサウルス',
    era: 'Cretaceous',
    diet: 'Carnivore',
    length: '約9〜11m',
    meaning: 'クロノスのトカゲ',
    pitch: 0.44,
    triviaJa: 'ギリシャ神話の神クロノスにちなみ命名された、巨大な頭部と強靭な顎を持つ海の怪物のような首長竜です。',
    triviaEn: 'Kronosaurus was a massive, short-necked pliosaur named after the Greek Titan Cronus.',
    speciesName: 'queenslandicus',
    speciesMeaning: '発見地であるオーストラリアのクイーンズランド州（Queensland）に由来する。',
    speciesNote: '💡ギリシャ神話の神にちなむ、巨大な頭部と強靭な顎を持つ大型首長竜',
    expertKW: 'Titan',
    expertHint: '巨神・巨人',
    expertSegs: [['神話の「'], ['巨神', 'きょじん'], ['」の名を冠した圧倒的な巨体の海の捕食者です。英語で？']],
    expertOpts: [['Titan', '巨神（たいてん）'], ['Hero', '英雄'], ['Ghost', '幽霊'], ['Giant', '巨人']],
    expertCorrect: 0,
    expertExplJa: 'Titanは神話に登場する巨大な神々や巨神を意味します。',
    expertExplEn: 'Titan is a person or thing of very great strength, intellect, or importance.',
    basicKW: 'Power',
    basicHint: '力・パワー',
    basicSegs: [['非常に高い咬合力と「'], ['力', 'ちから'], ['」を持っていました。この基礎英語は？']],
    basicOpts: [['Weak', '弱さ'], ['Power', '力（ぱわー）'], ['Fear', '恐怖'], ['Dark', '闇']],
    basicCorrect: 1,
    basicExplJa: 'Powerは物理的な力やエネルギーを意味します。',
    basicExplEn: 'Power is the ability or capacity to do something or act in a particular way.'
  },
  // 31
  {
    id: 'cymbospondylus',
    nameJa: 'キンボスポンディルス',
    nameEn: 'Cymbospondylus',
    sci: 'Cymbospondylus youngorum',
    phonetic: '/ˌsɪmboʊˈspɒndɪləs/',
    phoneticKatakana: 'キンボスポンディルス',
    era: 'Triassic',
    diet: 'Carnivore',
    length: '約8〜10m',
    meaning: '舟形の背骨',
    pitch: 0.53,
    triviaJa: 'トリアス紀の深海に生息していた巨大な魚竜で、背骨の形状が舟に似ていることから名付けられました。',
    triviaEn: 'Cymbospondylus was a gigantic Triassic ichthyosaur with a streamlined, finless tail.',
    speciesName: 'youngorum',
    speciesMeaning: '古生物研究に貢献したヤング（Young）家への献名。',
    speciesNote: '💡背骨の形状が舟に似た、トリアス紀の大型魚竜',
    expertKW: 'Vertebrae',
    expertHint: '背骨',
    expertSegs: [['背骨（椎骨）の形状が舟のようだったことから名付けられた「'], ['背骨', 'せぼね'], ['」の構造を持つ魚竜です。英語で？']],
    expertOpts: [['Vertebrae', '背骨（ヴぁーてぶら）'], ['Skull', '頭骨'], ['Rib', '肋骨'], ['Tooth', '歯']],
    expertCorrect: 0,
    expertExplJa: 'Vertebraeは背骨（脊椎）の複数形を意味します。',
    expertExplEn: 'Vertebrae are the bones forming the spinal column.',
    basicKW: 'Deep',
    basicHint: '深い',
    basicSegs: [['太古の「'], ['深い', 'ふかい'], ['」海を回遊していました。この基礎英語は？']],
    basicOpts: [['Shallow', '浅い'], ['Deep', '深い（でぃーぷ）'], ['High', '高い'], ['Low', '低い']],
    basicCorrect: 1,
    basicExplJa: 'Deepは水深が深いことを表します。',
    basicExplEn: 'Deep extending far down from the surface.'
  },
  // 32
  {
    id: 'agustinia',
    nameJa: 'アグスティニア',
    nameEn: 'Agustinia',
    sci: 'Agustinia ligabuei',
    phonetic: '/ˌɑːɡʊˈstiːniə/',
    phoneticKatakana: 'アグスティニア',
    era: 'Cretaceous',
    diet: 'Herbivore',
    length: '約15m',
    meaning: 'アグスティンのトカゲ',
    pitch: 0.46,
    triviaJa: '背中に突いた奇妙で長いプレートや棘が特徴的な、南米産の珍しい竜脚類です。',
    triviaEn: 'Agustinia was a South American sauropod with bizarre armor plates and spikes along its back.',
    speciesName: 'ligabuei',
    speciesMeaning: 'イタリアの科学者・実業家のジャンカルロ・リガブエ（Giancarlo Ligabue）氏への献名。',
    speciesNote: '💡背中に奇妙な棘や板状突起を持つ南米の珍しい竜脚類',
    expertKW: 'Spike',
    expertHint: 'スパイク・トゲ',
    expertSegs: [['背中から何本もの不思議な「'], ['棘', 'とげ'], ['」が伸びていました。英語で？']],
    expertOpts: [['Spike', 'スパイク（すぱいく）'], ['Leaf', '葉'], ['Feather', '羽毛'], ['Hair', '毛']],
    expertCorrect: 0,
    expertExplJa: 'Spikeは尖ったトゲ状の突起を指します。',
    expertExplEn: 'Spike is a thin, thin pointed piece of metal or bone.',
    basicKW: 'Strange',
    basicHint: '奇妙な',
    basicSegs: [['非常に「'], ['奇妙な', 'きみょうな'], ['」外見をした恐竜でした。この基礎英語は？']],
    basicOpts: [['Normal', '普通の'], ['Strange', '奇妙な（すとれんじ）'], ['Simple', '簡単な'], ['Clear', '明確な']],
    basicCorrect: 1,
    basicExplJa: 'Strangeは普通ではない、奇妙なことを表します。',
    basicExplEn: 'Strange unusual or surprising in a way that is unsettling or hard to understand.'
  },
  // 33
  {
    id: 'pterodactylus',
    nameJa: 'プテロダクティルス',
    nameEn: 'Pterodactylus',
    sci: 'Pterodactylus antiquus',
    phonetic: '/ˌtɛrəˈdæktɪləs/',
    phoneticKatakana: 'プテロダクティルス',
    era: 'Jurassic',
    diet: 'Piscivore',
    length: '翼開長約1m',
    meaning: '翼の指',
    pitch: 0.62,
    triviaJa: '最初に学名が記載された有名な小型の翼竜で、細長いクチバシで昆虫や小魚を捕らえました。',
    triviaEn: 'Pterodactylus was the first named pterosaur, small in size with a slender beak.',
    speciesName: 'antiquus',
    speciesMeaning: 'ラテン語で「古い、古代の」を意味する。',
    speciesNote: '💡最初に科学的記載がなされた有名な小型の翼竜',
    expertKW: 'Pterosaur',
    expertHint: '翼竜',
    expertSegs: [['歴史上最初に記載された「'], ['翼竜', 'よくりゅう'], ['」として有名です。英語で？']],
    expertOpts: [['Pterosaur', '翼竜（てろさーる）'], ['Bird', '鳥'], ['Lizard', 'トカゲ'], ['Bat', 'コウモリ']],
    expertCorrect: 0,
    expertExplJa: 'Pterosaurは翼竜類を意味します。',
    expertExplEn: 'Pterosaur is a flying reptile.',
    basicKW: 'Small',
    basicHint: '小さい',
    basicSegs: [['体長が約1メートルほどの「'], ['小さい', 'ちいさい'], ['」翼竜でした。この基礎英語は？']],
    basicOpts: [['Big', '大きい'], ['Small', '小さい（すもーる）'], ['Tall', '高い'], ['Long', '長い']],
    basicCorrect: 1,
    basicExplJa: 'Smallはサイズや程度が小さいことを表します。',
    basicExplEn: 'Small of a size that is less than normal or standard.'
  },
  // 34
  {
    id: 'apatosaurus',
    nameJa: 'アパトサウルス',
    nameEn: 'Apatosaurus',
    sci: 'Apatosaurus ajax',
    phonetic: '/əˌpætəˈsɔːrəs/',
    phoneticKatakana: 'アパトサウルス',
    era: 'Jurassic',
    diet: 'Herbivore',
    length: '約21〜23m',
    meaning: '欺くトカゲ',
    pitch: 0.43,
    triviaJa: '頑丈な骨格と鞭のような尾を持つジュラ紀の大型竜脚類で、かつてはブロントサウルスと混同されていました。',
    triviaEn: 'Apatosaurus was a massive, heavily built sauropod dinosaur of the Late Jurassic.',
    speciesName: 'ajax',
    speciesMeaning: 'ギリシャ神話の豪勇の英雄アイアス（Ajax）にちなむ。',
    speciesNote: '💡頑丈な体格と鞭のような尾を持つジュラ紀の大型竜脚類',
    expertKW: 'Sauropod',
    expertHint: '竜脚類',
    expertSegs: [['象徴的な長い首を持つ草食恐竜「'], ['竜脚類', 'りゅうきゃくるい'], ['」の一種です。英語で？']],
    expertOpts: [['Sauropod', '竜脚類（さうろぽっど）'], ['Theropod', '獣脚類'], ['Ceratopsian', '角竜'], ['Ornithischian', '鳥盤類']],
    expertCorrect: 0,
    expertExplJa: 'Sauropodは首の長い草食恐竜を指します。',
    expertExplEn: 'Sauropod is a long-necked dinosaur.',
    basicKW: 'Heavy',
    basicHint: '重い',
    basicSegs: [['非常に頑丈で「'], ['重い', 'おもい'], ['」体重を支える足を持っていました。この基礎英語は？']],
    basicOpts: [['Light', '軽い'], ['Heavy', '重い（へびー）'], ['Thin', '薄い'], ['Fast', '速い']],
    basicCorrect: 1,
    basicExplJa: 'Heavyは体重や質量が重いことを表します。',
    basicExplEn: 'Heavy of great weight.'
  },
  // 35
  {
    id: 'dimorphodon',
    nameJa: 'ディモルフォドン',
    nameEn: 'Dimorphodon',
    sci: 'Dimorphodon macronix',
    phonetic: '/daɪˈmɔːrfədɒn/',
    phoneticKatakana: 'ディモルフォドン',
    era: 'Jurassic',
    diet: 'Piscivore',
    length: '翼開長約1.4m',
    meaning: '2種類の形の歯',
    pitch: 0.59,
    triviaJa: '頭部が非常に大きく、大きさの異なる2種類の歯を持っていたジュラ紀前期の初期翼竜です。',
    triviaEn: 'Dimorphodon was an early pterosaur with a large puffin-like skull and two tooth types.',
    speciesName: 'macronix',
    speciesMeaning: 'ギリシャ語の makros（大きい）と onyx（爪）に由来し、「大きな爪」を意味する。',
    speciesNote: '💡大きな頭部と2種類の異なる歯を持っていた初期の翼竜',
    expertKW: 'Teeth',
    expertHint: '歯（複数）',
    expertSegs: [['口の中に大きさや形の違う「'], ['歯', 'は'], ['」が生えていました。英語で？']],
    expertOpts: [['Teeth', '歯（てぃーす）'], ['Eyes', '目'], ['Bones', '骨'], ['Claws', '爪']],
    expertCorrect: 0,
    expertExplJa: 'Teethは「歯」の複数形です。',
    expertExplEn: 'Teeth are the plural of tooth, hard structures in the mouth.',
    basicKW: 'Large',
    basicHint: '大きい',
    basicSegs: [['体に対して頭部が非常に「'], ['大きい', 'おおきい'], ['」特徴がありました。この基礎英語は？']],
    basicOpts: [['Small', '小さい'], ['Large', '大きい（らーじ）'], ['Short', '短い'], ['Weak', '弱い']],
    basicCorrect: 1,
    basicExplJa: 'Largeはサイズが大きいことを表します。',
    basicExplEn: 'Large of considerable size or capacity.'
  },
  // 36
  {
    id: 'shonisaurus',
    nameJa: 'ショニサウルス',
    nameEn: 'Shonisaurus',
    sci: 'Shonisaurus popularis',
    phonetic: '/ˌʃoʊniˈsɔːrəs/',
    phoneticKatakana: 'ショニサウルス',
    era: 'Triassic',
    diet: 'Piscivore',
    length: '約15m',
    meaning: 'ショーショーニのトカゲ',
    pitch: 0.45,
    triviaJa: 'トリアス紀の海に生息していた史上最大級の魚竜で、丸く幅広い体型と長い吻が特徴です。',
    triviaEn: 'Shonisaurus was one of the largest Triassic ichthyosaurs, with a wide body and long snout.',
    speciesName: 'popularis',
    speciesMeaning: 'ラテン語で「一般の、国民の」を意味し、ネバダ州の州の化石に指定されたことにちなむ。',
    speciesNote: '💡丸くて幅広い体型を持つトリアス紀の巨大な魚竜',
    expertKW: 'Ichthyosaur',
    expertHint: '魚竜',
    expertSegs: [['トリアス紀の海で巨大に繁栄した「'], ['魚竜', 'ぎょりゅう'], ['」の一種です。英語で？']],
    expertOpts: [['Ichthyosaur', '魚竜（いくちおさーる）'], ['Plesiosaur', '首長竜'], ['Mosasaur', 'モササウルス'], ['Dinosaur', '恐竜']],
    expertCorrect: 0,
    expertExplJa: 'Ichthyosaurは魚竜を意味します。',
    expertExplEn: 'Ichthyosaur is a marine reptile.',
    basicKW: 'Wide',
    basicHint: '広い・幅の広い',
    basicSegs: [['お腹周りが非常に「'], ['広い', 'ひろい'], ['」ふっくらした体型をしていました。この基礎英語は？']],
    basicOpts: [['Narrow', '狭い'], ['Wide', '広い（わいど）'], ['Thin', '薄い'], ['Short', '短い']],
    basicCorrect: 1,
    basicExplJa: 'Wideは幅が広いことを表します。',
    basicExplEn: 'Wide of great extent from side to side.'
  },
  // 37
  {
    id: 'parasaurolophus',
    nameJa: 'パラサウロロフス',
    nameEn: 'Parasaurolophus',
    sci: 'Parasaurolophus walkeri',
    phonetic: '/ˌpærəˌsɔːrəˈloʊfəs/',
    phoneticKatakana: 'パラサウロロフス',
    era: 'Cretaceous',
    diet: 'Herbivore',
    length: '約9〜10m',
    meaning: 'サウロロフスに近いもの',
    pitch: 0.52,
    triviaJa: '頭の後ろに伸びる管状の長いトサカを持ち、空気を鳴らして音（鳴き声）を響かせた草食恐竜です。',
    triviaEn: 'Parasaurolophus was a hadrosaurid known for its long, resonant tubular cranial crest.',
    speciesName: 'walkeri',
    speciesMeaning: 'カナダの化石発掘者・実業家のウォーカー（Byron Edmund Walker）氏への献名。',
    speciesNote: '💡頭部の管状の長いトサカから音を響かせたとされるハドロサウルス類',
    expertKW: 'Crest',
    expertHint: 'トサカ・冠',
    expertSegs: [['頭から後方に伸びる管状の「'], ['トサカ', 'とさか'], ['」が楽器のように音を鳴らしました。英語で？']],
    expertOpts: [['Crest', 'トサカ（くれすと）'], ['Horn', '角'], ['Tail', '尾'], ['Fin', '鰭']],
    expertCorrect: 0,
    expertExplJa: 'Crestは頭部のトサカや冠を意味します。',
    expertExplEn: 'Crest is a ridge or tuft on the head.',
    basicKW: 'Sound',
    basicHint: '音',
    basicSegs: [['トサカ内部の複雑な管で大きな「'], ['音', 'おと'], ['」を響かせました。この基礎英語は？']],
    basicOpts: [['Light', '光'], ['Sound', '音（さうんど）'], ['Color', '色'], ['Smell', '匂い']],
    basicCorrect: 1,
    basicExplJa: 'Soundは耳で聞こえる音を意味します。',
    basicExplEn: 'Sound vibrations that travel through the air and can be heard.'
  },
  // 38
  {
    id: 'rhamphorhynchus',
    nameJa: 'ランフォリンクス',
    nameEn: 'Rhamphorhynchus',
    sci: 'Rhamphorhynchus muensteri',
    phonetic: '/ˌræmfəˈrɪŋkəs/',
    phoneticKatakana: 'ランフォリンクス',
    era: 'Jurassic',
    diet: 'Piscivore',
    length: '翼開長約1.8m',
    meaning: 'くちばしの先端',
    pitch: 0.63,
    triviaJa: '前方に突き出た鋭い歯と、先端にひし形の舵がついた長い尾を持つジュラ紀の翼竜です。',
    triviaEn: 'Rhamphorhynchus was a long-tailed Jurassic pterosaur with forward-pointing teeth and a vane.',
    speciesName: 'muensteri',
    speciesMeaning: 'ドイツの古生物学者ゲオルク・ミュンスター（Georg zu Münster）伯爵への献名。',
    speciesNote: '💡ひし形の舵がついた長い尾と前方に向いた歯を持つジュラ紀の翼竜',
    expertKW: 'Diamond',
    expertHint: 'ひし形',
    expertSegs: [['尻尾の先端には「'], ['ひし形', 'ひしがた'], ['」の膜（舵）がついていました。英語で？']],
    expertOpts: [['Diamond', 'ひし形（だいやもんど）'], ['Circle', '円'], ['Square', '正方形'], ['Triangle', '三角形']],
    expertCorrect: 0,
    expertExplJa: 'Diamondはダイヤ形（ひし形）を意味します。',
    expertExplEn: 'Diamond is a rhombus shape with oblique angles.',
    basicKW: 'Fish',
    basicHint: '魚',
    basicSegs: [['鋭い歯で水面から「'], ['魚', 'さかな'], ['」を突き刺して捕食しました。この基礎英語は？']],
    basicOpts: [['Bird', '鳥'], ['Fish', '魚（ふぃっしゅ）'], ['Fruit', '果物'], ['Grass', '草']],
    basicCorrect: 1,
    basicExplJa: 'Fishは水生動物の魚を意味します。',
    basicExplEn: 'Fish is a cold-blooded animal living in water.'
  },
  // 39
  {
    id: 'anhanguera',
    nameJa: 'アンハングエラ',
    nameEn: 'Anhanguera',
    sci: 'Anhanguera santanae',
    phonetic: '/ˌæhæŋˈɡwɛrə/',
    phoneticKatakana: 'アンハングエラ',
    era: 'Cretaceous',
    diet: 'Piscivore',
    length: '翼開長約4〜5m',
    meaning: '古い悪魔（トゥピ語）',
    pitch: 0.54,
    triviaJa: '上下のクチバシの先端に半円形のトサカを持ち、海の上を飛びながら魚をすくい取った翼竜です。',
    triviaEn: 'Anhanguera was a fish-eating pterosaur with semicircular crests on its jaws from Brazil.',
    speciesName: 'santanae',
    speciesMeaning: 'ブラジルの有名な化石産地サンタナ層（Santana Formation）に由来する。',
    speciesNote: '💡クチバシの先端にトサカを持ち、魚を主食とした白亜紀の翼竜',
    expertKW: 'Beak',
    expertHint: 'クチバシ',
    expertSegs: [['上下の「'], ['クチバシ', 'くちばし'], ['」の先端に特徴的なトサカがありました。英語で？']],
    expertOpts: [['Beak', 'クチバシ（びーく）'], ['Tooth', '歯'], ['Tongue', '舌'], ['Lip', '唇']],
    expertCorrect: 0,
    expertExplJa: 'Beakは鳥類や翼竜の硬いクチバシを指します。',
    expertExplEn: 'Beak is a bird or pterosaur horny projecting jaws.',
    basicKW: 'Fly',
    basicHint: '飛ぶ',
    basicSegs: [['海風に乗って優雅に大空を「'], ['飛ぶ', 'とぶ'], ['」ことができました。この基礎英語は？']],
    basicOpts: [['Run', '走る'], ['Fly', '飛ぶ（ふらい）'], ['Swim', '泳ぐ'], ['Crawl', '這う']],
    basicCorrect: 1,
    basicExplJa: 'Flyは空中を飛行する動作を意味します。',
    basicExplEn: 'Fly means to move through the air using wings.'
  },
  // 40
  {
    id: 'eudimorphodon',
    nameJa: 'エウディモルフォドン',
    nameEn: 'Eudimorphodon',
    sci: 'Eudimorphodon ranzii',
    phonetic: '/ˌjuːdaɪˈmɔːrfədɒn/',
    phoneticKatakana: 'エウディモルフォドン',
    era: 'Triassic',
    diet: 'Piscivore',
    length: '翼開長約1m',
    meaning: '真の2種類の形の歯',
    pitch: 0.61,
    triviaJa: 'トリアス紀の地層から見つかった最古級の翼竜の一つで、非常に多くの細かい歯が並んでいました。',
    triviaEn: 'Eudimorphodon was one of the earliest and most primitive pterosaurs of the Triassic.',
    speciesName: 'ranzii',
    speciesMeaning: 'イタリアの化石収集家マリオ・ランツィ（Mario Ranzi）氏への献名。',
    speciesNote: '💡トリアス紀に栄えた、多数の細かい歯を持つ最古級の翼竜',
    expertKW: 'Triassic',
    expertHint: '三畳紀',
    expertSegs: [['恐竜や翼竜が誕生した「'], ['三畳紀', 'さんじょうき'], ['」に生息していました。英語で？']],
    expertOpts: [['Triassic', '三畳紀（とらいあしっく）'], ['Jurassic', 'ジュラ紀'], ['Cretaceous', '白亜紀'], ['Modern', '現代']],
    expertCorrect: 0,
    expertExplJa: 'Triassicは中生代の最初の時代である三畳紀を指します。',
    expertExplEn: 'Triassic is the first period of the Mesozoic era.',
    basicKW: 'Old',
    basicHint: '古い',
    basicSegs: [['中生代の非常に「'], ['古い', 'ふるい'], ['」時代を生きた翼竜です。この基礎英語は？']],
    basicOpts: [['New', '新しい'], ['Old', '古い（おーるど）'], ['Young', '若い'], ['Fast', '速い']],
    basicCorrect: 1,
    basicExplJa: 'Oldは年代が古い、古くから存在することを表します。',
    basicExplEn: 'Old having lived for a long time or dating from a remote past.'
  },
  // 41
  {
    id: 'leedsichthys',
    nameJa: 'リードシクティス',
    nameEn: 'Leedsichthys',
    sci: 'Leedsichthys problematicus',
    phonetic: '/ˌliːdʒɪkˈθɪs/',
    phoneticKatakana: 'リードシクティス',
    era: 'Jurassic',
    diet: 'Piscivore',
    length: '約9〜16m',
    meaning: 'リードの魚',
    pitch: 0.48,
    triviaJa: 'ジュラ紀の海に生息していた史上最大級の硬骨魚類で、クジラのようにプランクトンを濾過して食べました。',
    triviaEn: 'Leedsichthys was a gigantic suspension-feeding pachycormid fish of the Jurassic seas.',
    speciesName: 'problematicus',
    speciesMeaning: 'ラテン語で「問題のある、不可解な」を意味し、化石の構造が複雑で分類に苦労したことに由来する。',
    speciesNote: '💡クジラのようにおとなしくプランクトンを食べていた史上最大級の古代魚',
    expertKW: 'Filter',
    expertHint: '濾過・フィルター',
    expertSegs: [['巨大な口で海水を飲み込みプランクトンを「'], ['濾過', 'ろか'], ['」して食べていました。英語で？']],
    expertOpts: [['Filter', '濾過（ふるたー）'], ['Bite', '噛む'], ['Chew', '咀嚼'], ['Swallow', '丸呑み']],
    expertCorrect: 0,
    expertExplJa: 'Filterは液体から不純物や小生物を漉し取る機能を意味します。',
    expertExplEn: 'Filter is a porous device used to filter liquids or gases.',
    basicKW: 'Tiny',
    basicHint: 'ごく小さな',
    basicSegs: [['体が巨大であるにもかかわらず、食べるものは「'], ['小さな', 'ちいさな'], ['」プランクトンでした。英語で？']],
    basicOpts: [['Huge', '巨大な'], ['Tiny', 'ごく小さな（たいにー）'], ['Heavy', '重い'], ['Tall', '高い']],
    basicCorrect: 1,
    basicExplJa: 'Tinyは極めて小さいサイズを表します。',
    basicExplEn: 'Tiny very small in size or amount.'
  },
  // 42
  {
    id: 'puertasaurus',
    nameJa: 'プエルタサウルス',
    nameEn: 'Puertasaurus',
    sci: 'Puertasaurus reuili',
    phonetic: '/ˌpwɛrtəˈsɔːrəs/',
    phoneticKatakana: 'プエルタサウルス',
    era: 'Cretaceous',
    diet: 'Herbivore',
    length: '約30〜40m',
    meaning: 'プエルタのトカゲ',
    pitch: 0.27,
    triviaJa: '胴体が極めて幅広く、地球史上最大級の巨体を誇る南米産のティタノサウルス類です。',
    triviaEn: 'Puertasaurus was one of the largest titanosaurs ever, with an immensely broad chest.',
    speciesName: 'reuili',
    speciesMeaning: '化石を発見したパブロ・プエルタ（Pablo Puerta）氏とサンティアゴ・レウイル（Santiago Reuil）氏にちなむ。',
    speciesNote: '💡極めて幅の広い胴体を持ち、史上最大級とされる南米の竜脚類',
    expertKW: 'Titanosaur',
    expertHint: 'ティタノサウルス類',
    expertSegs: [['白亜紀末期に繁栄した最も巨大な草食恐竜グループ「'], ['ティタノサウルス類', 'てぃたのさうるするい'], ['」の一種です。英語で？']],
    expertOpts: [['Titanosaur', 'ティタノサウルス（たいてさうる）'], ['Stegosaur', '剣竜'], ['Ankylosaur', '鎧竜'], ['Ceratopsian', '角竜']],
    expertCorrect: 0,
    expertExplJa: 'Titanosaurは白亜紀に繁栄した頑丈な巨体を持つ竜脚類の一群です。',
    expertExplEn: 'Titanosaur is a diverse group of sauropod dinosaurs characterized by massive sizes.',
    basicKW: 'Wide',
    basicHint: '幅の広い',
    basicSegs: [['胸や胴体の部分が驚くほど「'], ['幅広い', 'はばひろい'], ['」骨格をしていました。この基礎英語は？']],
    basicOpts: [['Narrow', '狭い'], ['Wide', '幅の広い（わいど）'], ['Thin', '薄い'], ['Short', '短い']],
    basicCorrect: 1,
    basicExplJa: 'Wideは横幅が広いことを表します。',
    basicExplEn: 'Wide of great extent from side to side.'
  },
  // 43
  {
    id: 'megalosaurus',
    nameJa: 'メガロサウルス',
    nameEn: 'Megalosaurus',
    sci: 'Megalosaurus bucklandii',
    phonetic: '/ˌmɛɡələˈsɔːrəs/',
    phoneticKatakana: 'メガロサウルス',
    era: 'Jurassic',
    diet: 'Carnivore',
    length: '約6〜9m',
    meaning: '偉大なトカゲ',
    pitch: 0.4,
    triviaJa: '科学的に人類が世界で最初に命名・記載した歴史上記念すべき最初の恐竜です。',
    triviaEn: 'Megalosaurus was the first dinosaur ever to be scientifically described and named.',
    speciesName: 'bucklandii',
    speciesMeaning: '最初の化石を研究・記載したイギリスの地質学者ウィリアム・バックランド（William Buckland）氏への献名。',
    speciesNote: '💡世界で最初に学名がつけられた歴史上記念すべき最初の恐竜',
    expertKW: 'History',
    expertHint: '歴史',
    expertSegs: [['恐竜科学の「'], ['歴史', 'れきし'], ['」において最初に学名がつけられた記念碑的な種です。英語で？']],
    expertOpts: [['History', '歴史（ひすとりー）'], ['Future', '未来'], ['Myth', '神話'], ['Legend', '伝説']],
    expertCorrect: 0,
    expertExplJa: 'Historyは過去の出来事や歴史を意味します。',
    expertExplEn: 'History is the study of past events.',
    basicKW: 'First',
    basicHint: '最初の',
    basicSegs: [['人類に発見され命名された「'], ['最初の', 'さいしょの'], ['」恐竜となりました。この基礎英語は？']],
    basicOpts: [['Last', '最後の'], ['First', '最初の（ふぁーすと）'], ['Next', '次の'], ['Only', '唯一の']],
    basicCorrect: 1,
    basicExplJa: 'Firstは順序や歴史の中で最初であることを表します。',
    basicExplEn: 'First coming before all others in time or order.'
  },
  // 44
  {
    id: 'plateosaurus',
    nameJa: 'プラテオサウルス',
    nameEn: 'Plateosaurus',
    sci: 'Plateosaurus engelhardti',
    phonetic: '/ˌplætiəˈsɔːrəs/',
    phoneticKatakana: 'プラテオサウルス',
    era: 'Triassic',
    diet: 'Herbivore',
    length: '約6〜10m',
    meaning: '平らなトカゲ',
    pitch: 0.49,
    triviaJa: '三畳紀末期にヨーロッパで大繁栄した初期の大型竜脚形類で、二足歩行と四足歩行を使い分けました。',
    triviaEn: 'Plateosaurus was a prolific long-necked herbivore of the Late Triassic in Europe.',
    speciesName: 'engelhardti',
    speciesMeaning: '化石を発見したドイツの実業家・学者ミヒャエル・エンゲルハルト（Michael Engelhardt）氏への献名。',
    speciesNote: '💡三畳紀末期にヨーロッパで大繁栄した初期の大型草食恐竜',
    expertKW: 'Ancestor',
    expertHint: '祖先',
    expertSegs: [['後の巨大竜脚類の「'], ['祖先', 'そせん'], ['」にあたる三畳紀の草食動物です。英語で？']],
    expertOpts: [['Ancestor', '祖先（あんせすとあ）'], ['Child', '子供'], ['King', '王'], ['Rival', 'ライバル']],
    expertCorrect: 0,
    expertExplJa: 'Ancestorは血統上の祖先を意味します。',
    expertExplEn: 'Ancestor is a person or organism from whom one is descended.',
    basicKW: 'Early',
    basicHint: '初期の・早い',
    basicSegs: [['恐竜の歴史の中でも非常に「'], ['初期の', 'しょきの'], ['」時代に繁栄しました。この基礎英語は？']],
    basicOpts: [['Late', '遅い'], ['Early', '初期の（あーりー）'], ['Modern', '現代の'], ['New', '新しい']],
    basicCorrect: 1,
    basicExplJa: 'Earlyは時間的により早い時期や初期であることを表します。',
    basicExplEn: 'Early happening or done near the beginning of a particular time.'
  },
  // 45
  {
    id: 'microraptor',
    nameJa: 'ミクロラプトル',
    nameEn: 'Microraptor',
    sci: 'Microraptor gui',
    phonetic: '/ˌmaɪkroʊˈræptər/',
    phoneticKatakana: 'ミクロラプトル',
    era: 'Cretaceous',
    diet: 'Carnivore',
    length: '約0.8〜1m',
    meaning: '小さい泥棒',
    pitch: 0.72,
    triviaJa: '前足だけでなく後ろ足にも長い風切羽を持ち、樹間を滑空して暮らしていた四翼を持つ小型恐竜です。',
    triviaEn: 'Microraptor was a tiny four-winged dromaeosaurid capable of gliding between trees.',
    speciesName: 'gui',
    speciesMeaning: '中国の著名な古生物学者・羽毛恐竜研究者の徐星（Xu Xing / ジュ・シン）氏への献名。',
    speciesNote: '💡前足と後ろ足の四肢すべてに羽毛を持ち、滑空した小型の羽毛恐竜',
    expertKW: 'Glide',
    expertHint: '滑空する',
    expertSegs: [['樹から樹へと羽を広げて「'], ['滑空する', 'かっくうする'], ['」能力を持っていました。英語で？']],
    expertOpts: [['Glide', '滑空する（ぐらいど）'], ['Fall', '落下する'], ['Swim', '泳ぐ'], ['Dig', '掘る']],
    expertCorrect: 0,
    expertExplJa: 'Glideは空中を滑らかに滑空することを意味します。',
    expertExplEn: 'Glide means to move smoothly and continuously along in the air.',
    basicKW: 'Four',
    basicHint: '4つの',
    basicSegs: [['前足と後ろ足の合計「'], ['4つの', 'よっつの'], ['」羽に翼がありました。この基礎英語は？']],
    basicOpts: [['Two', '2つの'], ['Four', '4つの（ふぉー）'], ['Six', '6つの'], ['Eight', '8つの']],
    basicCorrect: 1,
    basicExplJa: 'Fourは数字の4を表します。',
    basicExplEn: 'Four equivalent to the sum of three and one.'
  },
  // 46
  {
    id: 'dolichorhynchops',
    nameJa: 'ドリコリンコプス',
    nameEn: 'Dolichorhynchops',
    sci: 'Dolichorhynchops osborni',
    phonetic: '/ˌdɒlɪkoʊˈrɪŋkɒps/',
    phoneticKatakana: 'ドリコリンコプス',
    era: 'Cretaceous',
    diet: 'Piscivore',
    length: '約3〜5m',
    meaning: '長い鼻の顔',
    pitch: 0.53,
    triviaJa: '首が短く頭部と口が長いポリコティルス類の首長竜で、内覧の海を素早く泳ぎ回りました。',
    triviaEn: 'Dolichorhynchops was a short-necked, fast-swimming plesiosaur from North American shallow seas.',
    speciesName: 'osborni',
    speciesMeaning: 'アメリカの著名な古生物学者ヘンリー・フェイフィールド・オズボーン（Henry Fairfield Osborn）氏への献名。',
    speciesNote: '💡首が短く頭部が発達した、内陸海を泳ぐ機敏な首長竜',
    expertKW: 'Plesiosaur',
    expertHint: '首長竜',
    expertSegs: [['海生爬虫類である「'], ['首長竜', 'くびながりゅう'], ['」の一種ですが、首は比較的短めです。英語で？']],
    expertOpts: [['Plesiosaur', '首長竜（ぷれじおさーる）'], ['Pterosaur', '翼竜'], ['Ichthyosaur', '魚竜'], ['Mosasaur', 'モササウルス']],
    expertCorrect: 0,
    expertExplJa: 'Plesiosaurは首長竜を指します。',
    expertExplEn: 'Plesiosaur is a marine reptile.',
    basicKW: 'Fast',
    basicHint: '速い',
    basicSegs: [['流線型の体で海中を「'], ['速く', 'はやく'], ['」泳いで魚を捕らえました。この基礎英語は？']],
    basicOpts: [['Slow', '遅い'], ['Fast', '速い（ふぁすと）'], ['Heavy', '重い'], ['Cold', '冷たい']],
    basicCorrect: 1,
    basicExplJa: 'Fastはスピードが速いことを表します。',
    basicExplEn: 'Fast moving at high speed.'
  },
  // 47
  {
    id: 'albertosaurus',
    nameJa: 'アルバートサウルス',
    nameEn: 'Albertosaurus',
    sci: 'Albertosaurus sarcophagus',
    phonetic: '/ælˌbɜːrtəˈsɔːrəs/',
    phoneticKatakana: 'アルバートサウルス',
    era: 'Cretaceous',
    diet: 'Carnivore',
    length: '約8〜9m',
    meaning: 'アルバータのトカゲ',
    pitch: 0.38,
    triviaJa: 'カナダのアルバータ州で多数発見されている、T.レックスの近縁にあたる素早い中型肉食恐竜です。',
    triviaEn: 'Albertosaurus was a swift, tyrannosaurid carnivore that lived in North America.',
    speciesName: 'sarcophagus',
    speciesMeaning: 'ギリシャ語で「肉を食らうもの（石棺）」を意味する。',
    speciesNote: '💡T.レックスの近縁でありながらスリムで素早い北米の肉食恐竜',
    expertKW: 'Tyrannosaur',
    expertHint: 'ティラノサウルス類',
    expertSegs: [['大型の頭部と短い前足を持つ「'], ['ティラノサウルス類', 'てぃらのさうるするい'], ['」の仲間です。英語で？']],
    expertOpts: [['Tyrannosaur', 'ティラノサウルス類（たいらのさうる）'], ['Sauropod', '竜脚類'], ['Ceratopsian', '角竜'], ['Stegosaur', '剣竜']],
    expertCorrect: 0,
    expertExplJa: 'Tyrannosaurは大型肉食恐竜ティラノサウルス科の総称です。',
    expertExplEn: 'Tyrannosaur is a member of large carnivorous tyrannosaurid dinosaurs.',
    basicKW: 'Group',
    basicHint: 'グループ・群れ',
    basicSegs: [['化石がまとまって見つかることから「'], ['グループ', 'ぐるーぷ'], ['」で行動していた可能性もあります。この基礎英語は？']],
    basicOpts: [['Alone', '単独'], ['Group', '群れ（ぐるーぷ）'], ['Single', '一匹'], ['Solo', 'ソロ']],
    basicCorrect: 1,
    basicExplJa: 'Groupは複数の個体の集まりやグループを意味します。',
    basicExplEn: 'Group a number of people or things that are located close together or considered together.'
  },
  // 48
  {
    id: 'stenopterygius',
    nameJa: 'ステノプテリギウス',
    nameEn: 'Stenopterygius',
    sci: 'Stenopterygius quadriscissus',
    phonetic: '/stɛnoʊˌptɛrɪˈdʒiːəs/',
    phoneticKatakana: 'ステノプテリギウス',
    era: 'Jurassic',
    diet: 'Piscivore',
    length: '約2〜4m',
    meaning: '狭い翼のひれ',
    pitch: 0.56,
    triviaJa: '流線型の美しい体と大きな目を持ち、母体内で子どもを育てて出産する化石も見つかっている魚竜です。',
    triviaEn: 'Stenopterygius was a sleek, dolphin-shaped Jurassic ichthyosaur known for live birth.',
    speciesName: 'quadriscissus',
    speciesMeaning: 'ラテン語の quadri（4つの）と scissus（裂けた）に由来する。',
    speciesNote: '💡流線型の美しい体を持ち、水中出産したことが分かっている魚竜',
    expertKW: 'Birth',
    expertHint: '誕生・出産',
    expertSegs: [['卵ではなく体内で子どもを育てる「'], ['出産', 'しゅっさん'], ['」（胎生）の化石証拠が見つかっています。英語で？']],
    expertOpts: [['Birth', '出産（ばーす）'], ['Egg', '卵'], ['Nest', '巣'], ['Seed', '種']],
    expertCorrect: 0,
    expertExplJa: 'Birthは生命が産まれること、出産を意味します。',
    expertExplEn: 'Birth is the emergence of a baby or other young from the body of its mother.',
    basicKW: 'Smooth',
    basicHint: '滑らかな',
    basicSegs: [['水の抵抗を減らす「'], ['滑らかな', 'なめらかな'], ['」流線型の皮膚をしていました。この基礎英語は？']],
    basicOpts: [['Rough', 'ざらざらした'], ['Smooth', '滑らかな（すむーす）'], ['Hard', '硬い'], ['Sharp', '鋭い']],
    basicCorrect: 1,
    basicExplJa: 'Smoothは表面が平らで滑らかな様子を表します。',
    basicExplEn: 'Smooth having an even and regular surface free from lumps or roughness.'
  },
  // 49
  {
    id: 'achelousaurus',
    nameJa: 'アケロウサウルス',
    nameEn: 'Achelousaurus',
    sci: 'Achelousaurus horneri',
    phonetic: '/əˌkiːləˈsɔːrəs/',
    phoneticKatakana: 'アケロウサウルス',
    era: 'Cretaceous',
    diet: 'Herbivore',
    length: '約6m',
    meaning: 'アケロオスのトカゲ',
    pitch: 0.49,
    triviaJa: '角の代わりに鼻の上や目の上に骨質の大きなコブ（隆起）を持っていた珍しい角竜です。',
    triviaEn: 'Achelousaurus was a ceratopsian dinosaur featuring bony boss bumps instead of horns.',
    speciesName: 'horneri',
    speciesMeaning: 'アメリカの著名な恐竜学者ジャック・ホーナー（Jack Horner）氏への献名。',
    speciesNote: '💡角ではなく骨質の大きなコブ（隆起）を鼻と目の上に持っていた角竜',
    expertKW: 'Ceratopsian',
    expertHint: '角竜類',
    expertSegs: [['頭部にフリルや角・コブを持つ草食恐竜「'], ['角竜類', 'かくりゅうるい'], ['」の仲間です。英語で？']],
    expertOpts: [['Ceratopsian', '角竜（けらとしあん）'], ['Sauropod', '竜脚類'], ['Theropod', '獣脚類'], ['Ornithischian', '鳥盤類']],
    expertCorrect: 0,
    expertExplJa: 'Ceratopsianは頭部に角やフリルを持つ角竜類を指します。',
    expertExplEn: 'Ceratopsian is a horned dinosaur of the Cretaceous.',
    basicKW: 'Bump',
    basicHint: 'コブ・隆起',
    basicSegs: [['鋭い角の代わりにゴツゴツした「'], ['コブ', 'こぶ'], ['」がありました。この基礎英語は？']],
    basicOpts: [['Hole', '穴'], ['Bump', 'コブ（ばんぷ）'], ['Line', '線'], ['Spot', '斑点']],
    basicCorrect: 1,
    basicExplJa: 'Bumpは表面の隆起やコブを意味します。',
    basicExplEn: 'Bump a light or hollow swell or protuberance on a surface.'
  },
  // 50
  {
    id: 'compsognathus',
    nameJa: 'コンプソグナトゥス',
    nameEn: 'Compsognathus',
    sci: 'Compsognathus longipes',
    phonetic: '/kɒmpˈsɒɡnəθəs/',
    phoneticKatakana: 'コンプソグナトゥス',
    era: 'Jurassic',
    diet: 'Carnivore',
    length: '約0.6〜1.4m',
    meaning: '上品な顎',
    pitch: 0.75,
    triviaJa: 'かつて世界最小の恐竜として有名だった、ニワトリほどの大きさの非常に素早い小型肉食恐竜です。',
    triviaEn: 'Compsognathus was a tiny, chicken-sized carnivorous dinosaur of the Late Jurassic.',
    speciesName: 'longipes',
    speciesMeaning: 'ラテン語の longus（長い）と pes（足）に由来し、「長い足」を意味する。',
    speciesNote: '💡ニワトリほどの大きさで、かつて世界最小の恐竜として知られた小型肉食竜',
    expertKW: 'Tiny',
    expertHint: '極めて小さい',
    expertSegs: [['恐竜としては「'], ['極めて小さい', 'きわめてちいさい'], ['」ニワトリサイズでした。英語で？']],
    expertOpts: [['Tiny', '極めて小さい（たいにー）'], ['Giant', '巨大な'], ['Heavy', '重い'], ['Long', '長い']],
    expertCorrect: 0,
    expertExplJa: 'Tinyは極めて小さなサイズを表します。',
    expertExplEn: 'Tiny very small.',
    basicKW: 'Fast',
    basicHint: '素早い',
    basicSegs: [['長い足で昆虫などを追いかける「'], ['素早い', 'すば早い'], ['」ハンターでした。この基礎英語は？']],
    basicOpts: [['Slow', '遅い'], ['Fast', '素早い（ふぁすと）'], ['Heavy', '重い'], ['Weak', '弱い']],
    basicCorrect: 1,
    basicExplJa: 'Fastは動きが素早いことを表します。',
    basicExplEn: 'Fast moving quickly or capable of high speed.'
  }
];

export const DINO_CHALLENGES: DinosaurChallenge[] = RAW_DINOS.map(raw => {
  const vocabQuestion: QuizQuestion = {
    japaneseSegments: raw.expertSegs.map(seg => ({ text: seg[0], ...(seg[1] ? { ruby: seg[1] } : {}) })),
    keyword: raw.expertKW,
    keywordHintJa: raw.expertHint,
    options: raw.expertOpts.map(opt => ({ text: opt[0], translation: opt[1] })),
    correctIndex: raw.expertCorrect,
    explanationJa: raw.expertExplJa,
    explanationEn: raw.expertExplEn
  };

  const basicQuestion: QuizQuestion = {
    japaneseSegments: raw.basicSegs.map(seg => ({ text: seg[0], ...(seg[1] ? { ruby: seg[1] } : {}) })),
    keyword: raw.basicKW,
    keywordHintJa: raw.basicHint,
    options: raw.basicOpts.map(opt => ({ text: opt[0], translation: opt[1] })),
    correctIndex: raw.basicCorrect,
    explanationJa: raw.basicExplJa,
    explanationEn: raw.basicExplEn
  };

  return {
    id: raw.id,
    nameJa: raw.nameJa,
    nameEn: raw.nameEn,
    scientificName: raw.sci,
    phonetic: raw.phonetic,
    phoneticKatakana: raw.phoneticKatakana,
    era: raw.era,
    diet: raw.diet,
    length: raw.length,
    meaning: raw.meaning,
    audioPitch: raw.pitch,
    triviaJa: raw.triviaJa,
    triviaEn: raw.triviaEn,
    speciesName: raw.speciesName,
    speciesMeaning: raw.speciesMeaning,
    speciesNote: raw.speciesNote,
    vocabQuestion,
    basicQuestion
  };
});

export const VOCABULARY_MAP: Record<string, string> = {};
DINO_CHALLENGES.forEach(challenge => {
  challenge.vocabQuestion.options.forEach(opt => {
    VOCABULARY_MAP[opt.text] = opt.translation;
  });
  challenge.basicQuestion.options.forEach(opt => {
    VOCABULARY_MAP[opt.text] = opt.translation;
  });
});

export const PRONUNCIATION_DICT: Record<string, string> = {
  apex: "エイペックス",
  bite: "バイト",
  sail: "セイル",
  fish: "フィッシュ",
  horn: "ホーン",
  herbivore: "ハービヴォア",
  crest: "クレスト",
  flight: "フライト",
  feather: "フェザー",
  claw: "クロー",
  theropod: "セラポッド",
  short: "ショート",
  sauropod: "ソロポッド",
  giant: "ジャイアント",
  predator: "プレデター",
  heavy: "ヘヴィ",
  plesiosaur: "プレジオソア",
  swimmer: "スイマー",
  neck: "ネック",
  tall: "トール",
  thumb: "サム",
  walk: "ウォーク",
  hunter: "ハンター",
  tooth: "トゥース",
  plate: "プレート",
  tail: "テイル",
  pterosaur: "テロソア",
  sky: "スカイ",
  flipper: "フリッパー",
  sea: "シー",
  strong: "ストロング",
  reptile: "レプタイル",
  swim: "スイム",
  marine: "マリーン",
  sharp: "シャープ",
  armor: "アーマー",
  club: "クラブ",
  dome: "ドーム",
  head: "ヘッド",
  ocean: "オーシャン",
  jaws: "ジョーズ",
  ichthyosaur: "イクティオソア",
  fast: "ファスト",
  snout: "スナウト",
  hunt: "ハント",
  sickle: "シクル",
  kill: "キル",
  dromaeosaur: "ドロマエオサウルス",
  pack: "パック",
  whip: "ホイップ",
  long: "ロング",
  vertebra: "ヴァーティブラ",
  water: "ウォーター",
  spine: "スパイン",
  muscle: "マッスル",
  bull: "ブル",
  run: "ラン",
  titan: "タイタン",
  power: "パワー",
  vertebrae: "ヴァーティブレイ",
  deep: "ディープ",
  spike: "スパイク",
  strange: "ストレンジ",
  small: "スモール",
  teeth: "ティース",
  large: "ラージ",
  wide: "ワイド",
  sound: "サウンド",
  diamond: "ダイアモンド",
  beak: "ビーク",
  fly: "フライ",
  triassic: "トライアシック",
  old: "オールド",
  filter: "フィルター",
  tiny: "タイニー",
  titanosaur: "タイタノソア",
  history: "ヒストリー",
  first: "ファースト",
  ancestor: "アンセスター",
  early: "アーリー",
  glide: "グライド",
  four: "フォー",
  tyrannosaur: "ティラノソア",
  group: "グループ",
  birth: "バース",
  smooth: "スムーズ",
  ceratopsian: "セラトプシアン",
  bump: "バンプ",
  bottom: "ボトム",
  middle: "ミドル",
  edge: "エッジ",
  sing: "シング",
  jump: "ジャンプ",
  wing: "ウィング",
  bird: "バード",
  cat: "キャット",
  dog: "ドッグ",
  carnivore: "カーニヴォア",
  omnivore: "オムニヴォア",
  insectivore: "インセクティヴォア",
  scale: "スケール",
  skin: "スキン",
  bone: "ボーン",
  ornithischian: "オルニティスキアン",
  big: "ビッグ",
  ankylosaur: "アンキロサウルス",
  weak: "ウィーク",
  prey: "プレイ",
  scavenger: "スカベンジャー",
  light: "ライト",
  soft: "ソフト",
  dinosaurs: "ダイナソーズ",
  runner: "ランナー",
  flyer: "フライヤー",
  jumper: "ジャンパー",
  leg: "レッグ",
  arm: "アーム",
  toe: "トウ",
  finger: "フィンガー",
  sleep: "スリープ",
  guard: "ガード",
  pet: "ペット",
  eye: "アイ",
  ear: "イヤー",
  nose: "ノーズ",
  back: "バック",
  dragon: "ドラゴン",
  bat: "バット",
  land: "ランド",
  cave: "ケイブ",
  mountain: "マウンテン",
  desert: "デザート",
  forest: "フォレスト",
  slow: "スロー",
  mammal: "ママル",
  amphibian: "アンフィビアン",
  climb: "クライム",
  dull: "ダル",
  flat: "フラット",
  cloth: "クロス",
  sword: "Sword",
  bow: "ボウ",
  shield: "シールド",
  cone: "コーン",
  box: "ボックス",
  foot: "フット",
  hand: "ハンド",
  river: "リバー",
  lake: "レイク",
  pond: "ポンド",
  fin: "フィン",
  dinosaur: "ダイナソー",
  quiet: "クワイエット",
  grow: "グロー",
  hide: "ハイド",
  hammer: "ハンマー",
  knife: "ナイフ",
  spear: "スピア",
  save: "セーブ",
  feed: "フィード",
  help: "ヘルプ",
  stegosaur: "ステゴサウルス",
  alone: "アローン",
  house: "ハウス",
  team: "チーム",
  rope: "ロープ",
  wire: "ワイヤー",
  stick: "スティック",
  high: "ハイ",
  rib: "リブ",
  skull: "スカル",
  fire: "ファイア",
  air: "エア",
  earth: "アース",
  fat: "ファット",
  blood: "ブラッド",
  horse: "ホース",
  deer: "ディア",
  lion: "ライオン",
  hero: "ヒーロー",
  ghost: "ゴースト",
  fear: "フィア",
  dark: "ダーク",
  shallow: "シャロウ",
  low: "ロー",
  leaf: "リーフ",
  hair: "ヘアー",
  normal: "ノーマル",
  simple: "シンプル",
  clear: "クリア",
  lizard: "リザード",
  thin: "シン",
  eyes: "アイズ",
  bones: "ボーンズ",
  claws: "クローズ",
  mosasaur: "モサソア",
  narrow: "ナロウ",
  color: "カラー",
  smell: "スメル",
  circle: "サークル",
  square: "スクエア",
  triangle: "トライアングル",
  fruit: "フルーツ",
  grass: "グラス",
  tongue: "タング",
  lip: "リップ",
  crawl: "クロール",
  jurassic: "ジュラシック",
  cretaceous: "クレテイシャス",
  modern: "モダン",
  new: "ニュー",
  young: "ヤング",
  chew: "チュー",
  swallow: "スワロウ",
  huge: "ヒュージ",
  future: "フューチャー",
  myth: "ミス",
  legend: "Legend",
  last: "Last",
  next: "Next",
  only: "オンリー",
  child: "チャイルド",
  king: "King",
  rival: "Rival",
  late: "レイト",
  fall: "フォール",
  dig: "ディグ",
  two: "Two",
  six: "Six",
  eight: "エイト",
  cold: "コールド",
  single: "シングル",
  solo: "ソロ",
  egg: "エッグ",
  nest: "ネスト",
  seed: "シード",
  rough: "ラフ",
  hard: "ハード",
  hole: "ホール",
  line: "ライン",
  spot: "スポット"
};

export const getPronunciation = (word: string): string | null => {
  if (!word) return null;
  const cleanWord = word.trim().toLowerCase();
  if (PRONUNCIATION_DICT[cleanWord]) {
    return PRONUNCIATION_DICT[cleanWord];
  }
  console.warn(`[Missing Pronunciation]: ${word}`);
  return null;
};

