// ==========================================
// DYNAMIC COMPACT DATASET FOR 50 PREHISTORIC CREATURES
// ==========================================

export interface JapaneseSegment {
  text: string;
  ruby?: string;
}

export interface QuizQuestion {
  japaneseSegments: JapaneseSegment[];
  keyword: string;
  keywordHintJa: string;
  options: {
    text: string;
    translation: string;
  }[];
  correctIndex: number;
  explanationJa: string;
  explanationEn: string;
}

export interface DinosaurChallenge {
  id: string;
  nameJa: string;
  nameEn: string;
  scientificName: string;
  phonetic: string;
  phoneticKatakana: string;
  era: 'Triassic' | 'Jurassic' | 'Cretaceous';
  diet: 'Herbivore' | 'Carnivore' | 'Piscivore';
  length: string;
  meaning: string;
  audioPitch: number;
  triviaJa: string;
  triviaEn: string;
  vocabQuestion: QuizQuestion;
  basicQuestion: QuizQuestion;
}

// ==========================================
// 1. ALL-INCLUSIVE PRONUNCIATION MAP
// ==========================================
export const PRONUNCIATION_MAP: Record<string, string> = {
  // Dino Expert Vocab
  'Carnivore': 'カーニボア',
  'Herbivore': 'ハービボア',
  'Piscivore': 'ピシボア',
  'Fossil': 'フォッシル',
  'Roar': 'ロアー',
  'Predator': 'プレデター',
  'Prey': 'プレイ',
  'Horn': 'ホーン',
  'Claw': 'クロー',
  'Armor': 'アーマー',
  'Sail': 'セイル',
  'Swim': 'スイム',
  'Feather': 'フェザー',
  'Scale': 'スケイル',
  'Tooth': 'トゥース',
  'Attack': 'アタック',
  'Defense': 'ディフェンス',
  'Flight': 'フライト',
  'Sleep': 'スリープ',
  'Plate': 'プレート',
  'Spike': 'スパイク',
  'Tail': 'テイル',
  'Wing': 'ウィング',
  'Neck': 'ネック',
  'Flipper': 'フリッパー',
  'Crest': 'クレスト',
  'Dome': 'ドーム',
  'Bull': 'ブル',
  'Frill': 'フリル',
  'Thumb': 'サム',
  'Nest': 'ネスト',
  'Egg': 'エッグ',
  'Giant': 'ジャイアント',
  'Sickle': 'シックル',
  'Beak': 'ビーク',
  'Snout': 'スナウト',
  'Hunter': 'ハンター',
  'Scythe': 'サイス',
  'Boss': 'ボス',
  'Ostrich': 'オーストリッチ',
  'Hollow': 'ホロウ',
  'Deceit': 'ディシート',
  'Spine': 'スパイン',
  'Thorn': 'ソーン',
  'Perforated': 'パーフォレイテッド',
  'Bird': 'バード',
  'Lizard': 'リザード',
  'Rib': 'リブ',
  'Fish': 'フィッシュ',
  'Stork': 'ストーク',
  'Plated': 'プレイテッド',
  'Abnormal': 'アブノーマル',
  'Five': 'ファイブ',
  'Trilobite': 'トライロバイト',
  'Scorpion': 'スコーピオン',
  'Shark': 'シャーク',
  'Tusk': 'タスク',
  'Saber': 'セイバー',
  'Arsinoe': 'アルシノエ',
  'Hornless': 'ホーンレス',

  // Basic Vocab
  'Big': 'ビッグ',
  'Small': 'スモール',
  'Three': 'スリー',
  'Long': 'ロング',
  'Fast': 'ファスト',
  'Safe': 'セーフ',
  'Hard': 'ハード',
  'Sky': 'スカイ',
  'Sea': 'シー',
  'Sound': 'サウンド',
  'Head': 'ヘッド',
  'Sharp': 'シャープ',
  'Short': 'ショート',
  'Spit': 'スピット',
  'Plant': 'プラント',
  'Good': 'グッド',
  'Thief': 'シーフ',
  'Heavy': 'ヘヴィ',
  'Jump': 'ジャンプ',
  'Run': 'ラン',
  'River': 'リバー',
  'Huge': 'ヒュージ',
  'Flat': 'フラット',
  'Speed': 'スピード',
  'Bone': 'ボーン',
  'Whip': 'ウィップ',
  'Weight': 'ウェイト',
  'Rear': 'リア',
  'Demon': 'デーモン',
  'Shield': 'シールド',
  'Four': 'フォー',
  'Old': 'オールド',
  'Water': 'ウォーター',
  'Paddle': 'パドル',
  'Eye': 'アイ',
  'Tall': 'トール',
  'Warm': 'ウォーム',
  'Bite': 'バイト',
  'Shrimp': 'シュリンプ',
  'Trunk': 'トランク',
  'Bottom': 'ボトム',
  'Swimmer': 'スイマー',
  'Teeth': 'ティース',
  'Cold': 'コウルド',
  'Cat': 'キャット',
  'Beast': 'ビースト',

  // General options & distractors used in quizzes
  'One': 'ワン',
  'Two': 'トゥー',
  'Little': 'リトル',
  'Thin': 'シン',
  'Weak': 'ウィーク',
  'Strong': 'ストロング',
  'Kind': 'カインド',
  'Happy': 'ハッピー',
  'Dangerous': 'デンジャラス',
  'Soft': 'ソフト',
  'Slow': 'スロウ',
  'Fly': 'フライ',
  'Sad': 'サッド',
  'Angry': 'アングリー',
  'Hot': 'ホット',
  'Dry': 'ドライ'
};

// Raw compact dinosaur definitions to fit neatly in tokens limit
interface RawDinoDef {
  id: string;
  nameJa: string;
  nameEn: string;
  sci: string;
  phonetic: string;
  phoneticKatakana: string;
  era: 'Triassic' | 'Jurassic' | 'Cretaceous';
  diet: 'Herbivore' | 'Carnivore' | 'Piscivore';
  length: string;
  meaning: string;
  pitch: number;
  triviaJa: string;
  triviaEn: string;

  // Q1 (Expert)
  expertKW: string;
  expertHint: string;
  expertSegs: [string, string?][];
  expertOpts: [string, string][]; // [text, translation]
  expertCorrect: number;
  expertExplJa: string;
  expertExplEn: string;

  // Q2 (Basic)
  basicKW: string;
  basicHint: string;
  basicSegs: [string, string?][];
  basicOpts: [string, string][]; // [text, translation]
  basicCorrect: number;
  basicExplJa: string;
  basicExplEn: string;
}

const RAW_DINOS: RawDinoDef[] = [
  // 1
  {
    id: 'tyrannosaurus',
    nameJa: 'ティラノサウルス',
    nameEn: 'Tyrannosaurus',
    sci: 'Tyrannosaurus rex',
    phonetic: '/tɪˌrænəˈsɔːrəs rɛks/',
    phoneticKatakana: 'タイラノサウルス レックス',
    era: 'Cretaceous',
    diet: 'Carnivore',
    length: '約12.0〜13.0m',
    meaning: '暴君のトカゲ王',
    pitch: 0.5,
    triviaJa: 'ティラノサウルスは最強の肉食恐竜で、噛む力は陸上動物史上最大でした。',
    triviaEn: 'T-rex was the most famous predator with an incredibly strong bite.',
    expertKW: 'Carnivore',
    expertHint: '肉食動物',
    expertSegs: [['ティラノサウルスは最強の「'], ['肉食動物', 'にくしょくどうぶつ'], ['」でした。これを表す英語はどれでしょう？']],
    expertOpts: [['Carnivore', '肉食動物（にくしょくどうぶつ）'], ['Herbivore', '草食動物（そうしょくどうぶつ）'], ['Piscivore', '魚食動物（ぎょしょくどうぶつ）'], ['Fossil', '化石（かせき）']],
    expertCorrect: 0,
    expertExplJa: 'Carnivoreはラテン語で「肉を食らうもの」を意味します。',
    expertExplEn: 'Carnivore refers to a meat-eating organism.',
    basicKW: 'Big',
    basicHint: '大きい',
    basicSegs: [['ティラノサウルスの体はとても「'], ['大きい', 'おおきい'], ['」でした。これを表す英語はどれでしょう？']],
    basicOpts: [['Big', '大きい（おおきい）'], ['Small', '小さい（ちいさい）'], ['Thin', '薄い（うすい）'], ['Short', '短い（みじかい）']],
    basicCorrect: 0,
    basicExplJa: 'Bigは体やサイズが「大きい」ことを指す基本英語です。',
    basicExplEn: 'Big describes anything of considerable size.'
  },
  // 2
  {
    id: 'triceratops',
    nameJa: 'トリケラトプス',
    nameEn: 'Triceratops',
    sci: 'Triceratops horridus',
    phonetic: '/traɪˈsɛrətɒps/',
    phoneticKatakana: 'トリケラトプス',
    era: 'Cretaceous',
    diet: 'Herbivore',
    length: '約8.0〜9.0m',
    meaning: '3つの角を持つ顔',
    pitch: 0.7,
    triviaJa: 'トリケラトプスは頭に3本の角を持ち、宿敵ティラノサウルスから身を守りました。',
    triviaEn: 'Triceratops had three sharp horns and a shield-like frill.',
    expertKW: 'Horn',
    expertHint: '角',
    expertSegs: [['頭に生えた鋭い「'], ['角', 'つの'], ['」で敵を威嚇しました。この「角」を表す英語はどれでしょう？']],
    expertOpts: [['Horn', '角（つの）'], ['Claw', '爪（つめ）'], ['Tail', '尻尾（しっぽ）'], ['Wing', '翼（つばさ）']],
    expertCorrect: 0,
    expertExplJa: 'Hornは動物の硬い「角」を意味します。',
    expertExplEn: 'Horn is a hard, pointed outgrowth on the head.',
    basicKW: 'Three',
    basicHint: '3つ',
    basicSegs: [['トリケラトプスは名前の通り「'], ['3つ', 'みっつ'], ['」の角を持っていました。「3」を表す英語はどれでしょう？']],
    basicOpts: [['One', '1つ（わん）'], ['Two', '2つ（とぅー）'], ['Three', '3つ（すりー）'], ['Four', '4つ（ふぉー）']],
    basicCorrect: 2,
    basicExplJa: 'Threeは「3つ」を意味する基礎数字です。',
    basicExplEn: 'Three represents the number 3.'
  },
  // 3
  {
    id: 'brachiosaurus',
    nameJa: 'ブラキオサウルス',
    nameEn: 'Brachiosaurus',
    sci: 'Brachiosaurus altithorax',
    phonetic: '/ˌbrækiəˈsɔːrəs/',
    phoneticKatakana: 'ブラキオサウルス',
    era: 'Jurassic',
    diet: 'Herbivore',
    length: '約25.0m',
    meaning: '腕のトカゲ',
    pitch: 0.4,
    triviaJa: 'キリンのように長い首で、超高層ビルの高さにある木の葉も食べられました。',
    triviaEn: 'Brachiosaurus had a towering height and ate tall forest leaves.',
    expertKW: 'Neck',
    expertHint: '首',
    expertSegs: [['ブラキオサウルスは非常に長い「'], ['首', 'くび'], ['」を持っていました。この「首」を表す英語はどれでしょう？']],
    expertOpts: [['Neck', '首（くび）'], ['Tail', '尻尾（しっぽ）'], ['Wing', '翼（つばさ）'], ['Bone', '骨（ほね）']],
    expertCorrect: 0,
    expertExplJa: 'Neckは「首」を意味します。ブラキオサウルスの首は9メートル以上ありました。',
    expertExplEn: 'Neck is the part of the body connecting the head to the torso.',
    basicKW: 'Long',
    basicHint: '長い',
    basicSegs: [['首や体がとても「'], ['長い', 'ながい'], ['」ことが彼らの特徴です。「長い」を表す英語はどれでしょう？']],
    basicOpts: [['Short', '短い（みじかい）'], ['Long', '長い（ながい）'], ['Heavy', '重い（おもい）'], ['Tall', '背が高い（たかい）']],
    basicCorrect: 1,
    basicExplJa: 'Longは長さが「長い」ことを表す基礎英単語です。',
    basicExplEn: 'Long means measuring a great distance from end to end.'
  },
  // 4
  {
    id: 'velociraptor',
    nameJa: 'ヴェロキラプトル',
    nameEn: 'Velociraptor',
    sci: 'Velociraptor mongoliensis',
    phonetic: '/vɪˈlɒsɪræptər/',
    phoneticKatakana: 'ヴェロキラプトル',
    era: 'Cretaceous',
    diet: 'Carnivore',
    length: '約2.0m',
    meaning: 'すばやい泥棒',
    pitch: 1.7,
    triviaJa: '知能が高く、足の後ろにある鎌のような大きくて鋭い爪で狩りをしました。',
    triviaEn: 'Velociraptor was an intelligent, fast predator with a curved foot claw.',
    expertKW: 'Claw',
    expertHint: '爪',
    expertSegs: [['後ろ足に獲物を切り裂く「'], ['爪', 'つめ'], ['」を持っていました。この「かぎ爪」を表す英語はどれでしょう？']],
    expertOpts: [['Horn', '角（つの）'], ['Claw', '爪（つめ）'], ['Wing', '翼（つばさ）'], ['Tooth', '歯（は）']],
    expertCorrect: 1,
    expertExplJa: 'Clawは鋭い動物の「爪」や「かぎ爪」を意味します。',
    expertExplEn: 'Claw represents a sharp, curved nail on the foot or hand.',
    basicKW: 'Fast',
    basicHint: '速い',
    basicSegs: [['ヴェロキラプトルは体が軽く、走るのがとても「'], ['速い', 'はやい'], ['」恐竜でした。「速い」を表す英語はどれでしょう？']],
    basicOpts: [['Slow', '遅い（おそい）'], ['Fast', '速い（はやい）'], ['Heavy', '重い（おおきい）'], ['Warm', '温かい（あたたかい）']],
    basicCorrect: 1,
    basicExplJa: 'Fastは「速い」を表します。ラプトルは俊敏なハンターでした。',
    basicExplEn: 'Fast means moving or capable of moving at high speed.'
  },
  // 5
  {
    id: 'spinosaurus',
    nameJa: 'スピノサウルス',
    nameEn: 'Spinosaurus',
    sci: 'Spinosaurus aegyptiacus',
    phonetic: '/ˌspaɪnəˈsɔːrəs/',
    phoneticKatakana: 'スピノサウルス',
    era: 'Cretaceous',
    diet: 'Piscivore',
    length: '約14.0〜15.0m',
    meaning: '棘のトカゲ',
    pitch: 0.55,
    triviaJa: '背中に巨大な帆を持ち、水の中を泳いで主に魚を食べて暮らしていました。',
    triviaEn: 'Spinosaurus was a giant dinosaur with a spine sail, adapted for water.',
    expertKW: 'Sail',
    expertHint: '帆',
    expertSegs: [['背中にある大きな「'], ['帆', 'ほ'], ['」は太陽の熱を浴びるためのものでした。「帆」を表す英語はどれでしょう？']],
    expertOpts: [['Sail', '帆（ほ）'], ['Wing', '翼（つばさ）'], ['Horn', '角（つの）'], ['Plate', '板（いた）']],
    expertCorrect: 0,
    expertExplJa: 'Sailは「帆（セイル）」を意味し、ヨットの帆や背中の突起を指します。',
    expertExplEn: 'Sail is a structure resembling a ship sail on the back.',
    basicKW: 'Fish',
    basicHint: '魚',
    basicSegs: [['スピノサウルスは水中で「'], ['魚', 'さかな'], ['」を捕まえていました。この「魚」を表す英語はどれでしょう？']],
    basicOpts: [['Bird', '鳥（とり）'], ['Fish', '魚（さかな）'], ['Cat', '猫（ねこ）'], ['Plant', '植物（しょくぶつ）']],
    basicCorrect: 1,
    basicExplJa: 'Fishは「魚」を意味する基礎的な単語です。',
    basicExplEn: 'Fish is a limbless cold-blooded animal living in water.'
  },
  // 6
  {
    id: 'stegosaurus',
    nameJa: 'ステゴサウルス',
    nameEn: 'Stegosaurus',
    sci: 'Stegosaurus stenops',
    phonetic: '/ˌstɛɡəˈsɔːrəs/',
    phoneticKatakana: 'ステゴサウルス',
    era: 'Jurassic',
    diet: 'Herbivore',
    length: '約9.0m',
    meaning: '屋根のあるトカゲ',
    pitch: 0.65,
    triviaJa: '背中に並ぶ五角形の骨の板と、尻尾にある4本の鋭いスパイクが特徴です。',
    triviaEn: 'Stegosaurus had flat bony plates along its spine for heat control.',
    expertKW: 'Plate',
    expertHint: '板',
    expertSegs: [['背中にある骨でできた「'], ['板', 'いた'], ['」で体温を調整したと考えられています。「板」は英語でどれでしょう？']],
    expertOpts: [['Plate', '板（いた）'], ['Spike', 'トゲ'], ['Wing', '翼（つばさ）'], ['Horn', '角（つの）']],
    expertCorrect: 0,
    expertExplJa: 'Plateは平らな「板」や「皿」を指します。',
    expertExplEn: 'Plate represents a flat, thin sheet of bone or metal.',
    basicKW: 'Safe',
    basicHint: '安全な',
    basicSegs: [['トゲのついた尾を振り回し、捕食者から身を守って「'], ['安全', 'あんぜん'], ['」でいられました。「安全な」を表す英語はどれでしょう？']],
    basicOpts: [['Dangerous', '危険な（きけんな）'], ['Safe', '安全な（あんぜんな）'], ['Cold', '冷たい（つめたい）'], ['Hard', '固い（かたい）']],
    basicCorrect: 1,
    basicExplJa: 'Safeは「安全な」を意味し、危険がない状態を言います。',
    basicExplEn: 'Safe means protected from or not exposed to danger.'
  },
  // 7
  {
    id: 'ankylosaurus',
    nameJa: 'アンキロサウルス',
    nameEn: 'Ankylosaurus',
    sci: 'Ankylosaurus magniventris',
    phonetic: '/ˌæŋkɪləˈsɔːrəs/',
    phoneticKatakana: 'アンキロサウルス',
    era: 'Cretaceous',
    diet: 'Herbivore',
    length: '約6.0〜8.0m',
    meaning: '連結したトカゲ',
    pitch: 0.6,
    triviaJa: '背中は硬い骨の鎧で覆われ、尾の先端には巨大なハンマーがついていました。',
    triviaEn: 'Ankylosaurus was a heavily armored dinosaur with a club tail.',
    expertKW: 'Armor',
    expertHint: '鎧',
    expertSegs: [['背中を覆う頑丈な「'], ['鎧', 'よろい'], ['」は弾丸すら通さないほど頑丈でした。「鎧」を表す英語はどれでしょう？']],
    expertOpts: [['Feather', '羽毛（うもう）'], ['Armor', '鎧（よろい）'], ['Scale', '鱗（うろこ）'], ['Tooth', '歯（は）']],
    expertCorrect: 1,
    expertExplJa: 'Armorは身を守るための「鎧（アーマー）」を指します。',
    expertExplEn: 'Armor is a tough protective covering for defense.',
    basicKW: 'Hard',
    basicHint: '固い',
    basicSegs: [['背中の骨のプレートは、石のように非常に「'], ['固い', 'かたい'], ['」ものでした。この「固い」を表す英語はどれでしょう？']],
    basicOpts: [['Soft', '柔らかい（やわらかい）'], ['Hard', '固い（かたい）'], ['Slow', '遅い（おそい）'], ['Easy', '簡単な（かんたんな）']],
    basicCorrect: 1,
    basicExplJa: 'Hardは「固い」や「硬い」を意味する基礎形容詞です。',
    basicExplEn: 'Hard means solid, firm, and resistant to pressure.'
  },
  // 8
  {
    id: 'pteranodon',
    nameJa: 'プテラノドン',
    nameEn: 'Pteranodon',
    sci: 'Pteranodon longiceps',
    phonetic: '/tɛˈrænədɒn/',
    phoneticKatakana: 'プテラノドン',
    era: 'Cretaceous',
    diet: 'Piscivore',
    length: '翼開長 約6.0m',
    meaning: '歯のない翼',
    pitch: 1.4,
    triviaJa: '大空を滑空した巨大な翼竜です。クチバシには歯がなく、魚を丸呑みしていました。',
    triviaEn: 'Pteranodon was a famous flying reptile with a massive wingspan.',
    expertKW: 'Wing',
    expertHint: '翼',
    expertSegs: [['空を飛ぶための長い「'], ['翼', 'つばさ'], ['」は、皮膜でできていました。この「翼」を表す英語はどれでしょう？']],
    expertOpts: [['Wing', '翼（つばさ）'], ['Tail', '尻尾（しっぽ）'], ['Horn', '角（つの）'], ['Claw', '爪（つめ）']],
    expertCorrect: 0,
    expertExplJa: 'Wingは鳥や昆虫、翼竜などの「翼・羽」を意味します。',
    expertExplEn: 'Wing is a modified forelimb used for flying.',
    basicKW: 'Sky',
    basicHint: '空',
    basicSegs: [['彼らは巨大な翼を使って広大な「'], ['空', 'そら'], ['」を滑空していました。この「空」を表す英語はどれでしょう？']],
    basicOpts: [['Sea', '海（うみ）'], ['Sky', '空（そら）'], ['River', '川（かわ）'], ['Land', '陸（りく）']],
    basicCorrect: 1,
    basicExplJa: 'Skyは地球を取り巻く「空」を表す基礎英語です。',
    basicExplEn: 'Sky is the region of the atmosphere visible from Earth.'
  },
  // 9
  {
    id: 'elasmosaurus',
    nameJa: 'エラスモサウルス',
    nameEn: 'Elasmosaurus',
    sci: 'Elasmosaurus platyurus',
    phonetic: '/ɪˌlæzməˈsɔːrəs/',
    phoneticKatakana: 'エラスモサウルス',
    era: 'Cretaceous',
    diet: 'Piscivore',
    length: '約14.0m',
    meaning: '薄い板のトカゲ',
    pitch: 0.8,
    triviaJa: '極めて長い首を持った首長竜で、4つの大きなひれ足を使って泳ぎました。',
    triviaEn: 'Elasmosaurus was a marine reptile with an extremely long neck.',
    expertKW: 'Flipper',
    expertHint: 'ひれ足',
    expertSegs: [['エラスモサウルスは4つの大きな「'], ['ひれ足', 'ひれあし'], ['」で推進力を得ていました。この「ひれ足」は英語で？']],
    expertOpts: [['Claw', '爪（つめ）'], ['Flipper', 'ひれ足（ひれあし）'], ['Wing', '翼（つばさ）'], ['Tail', '尻尾（しっぽ）']],
    expertCorrect: 1,
    expertExplJa: 'Flipperはアザラシやペンギン、首長竜の「ひれ足」を意味します。',
    expertExplEn: 'Flipper represents a broad, flat limb used for swimming.',
    basicKW: 'Sea',
    basicHint: '海',
    basicSegs: [['彼らは陸上ではなく、冷たい「'], ['海', 'うみ'], ['」の中で生活していました。この「海」を表す英語はどれでしょう？']],
    basicOpts: [['Sky', '空（そら）'], ['Sea', '海（うみ）'], ['River', '川（かわ）'], ['Forest', '森（もり）']],
    basicCorrect: 1,
    basicExplJa: 'Seaは地球表面を覆う塩水の「海」を意味します。',
    basicExplEn: 'Sea is the expanse of salt water that covers most of the earth.'
  },
  // 10
  {
    id: 'parasaurolophus',
    nameJa: 'パラサウロロフス',
    nameEn: 'Parasaurolophus',
    sci: 'Parasaurolophus walkeri',
    phonetic: '/ˌpærəsɔːˈrɒləfəs/',
    phoneticKatakana: 'パラサウロロフス',
    era: 'Cretaceous',
    diet: 'Herbivore',
    length: '約10.0m',
    meaning: 'サウロロフスに似た頭冠を持つもの',
    pitch: 0.9,
    triviaJa: '頭の後ろに伸びる長いトサカが特徴で、この中は空洞になっており、音を響かせて仲間と通信しました。',
    triviaEn: 'Parasaurolophus had a long crest on its head to make low trumpet-like sounds.',
    expertKW: 'Crest',
    expertHint: 'トサカ',
    expertSegs: [['頭の後ろに突き出た大きな「'], ['トサカ', 'とさか'], ['」が一番の特徴です。この「トサカ／頭冠」を表す英語はどれでしょう？']],
    expertOpts: [['Crest', 'トサカ／頭冠'], ['Horn', '角（つの）'], ['Plate', '板（いた）'], ['Armor', '鎧（よろい）']],
    expertCorrect: 0,
    expertExplJa: 'Crestは動物の頭頂部にある「トサカ」や「頭冠」を指します。',
    expertExplEn: 'Crest is a prominent feature on the head of birds or dinosaurs.',
    basicKW: 'Sound',
    basicHint: '音',
    basicSegs: [['空洞のトサカに空気を送り込み、遠くの仲間に「'], ['音', 'おと'], ['」を響かせて知らせていました。「音」を表す英語はどれでしょう？']],
    basicOpts: [['Light', '光（ひかり）'], ['Sound', '音（おと）'], ['Wind', '風（かぜ）'], ['Water', '水（みず）']],
    basicCorrect: 1,
    basicExplJa: 'Soundは、耳で聞こえる「音」を意味する基礎英語です。',
    basicExplEn: 'Sound is vibrations traveling through the air that can be heard.'
  },
  // 11
  {
    id: 'pachycephalosaurus',
    nameJa: 'パキケファロサウルス',
    nameEn: 'Pachycephalosaurus',
    sci: 'Pachycephalosaurus wyomingensis',
    phonetic: '/ˌpækɪˌsɛfələˈsɔːrəs/',
    phoneticKatakana: 'パキケファロサウルス',
    era: 'Cretaceous',
    diet: 'Herbivore',
    length: '約4.5m',
    meaning: '分厚い頭を持つトカゲ',
    pitch: 1.1,
    triviaJa: '頭頂部が丸いドーム状の分厚い骨でできており、仲間同士で頭突き合いをして儀式を行っていた説があります。',
    triviaEn: 'This dinosaur had a thick dome-like skull, likely used for head-butting.',
    expertKW: 'Dome',
    expertHint: 'ドーム',
    expertSegs: [['頭の上には、厚さ25cmに達する骨の「'], ['ドーム', 'どーむ'], ['」状のコブがありました。「丸い屋根・ドーム」を表す英語はどれでしょう？']],
    expertOpts: [['Plate', '板（いた）'], ['Dome', 'ドーム／丸い屋根'], ['Spike', 'トゲ'], ['Sail', '帆（ほ）']],
    expertCorrect: 1,
    expertExplJa: 'Domeは半球形の「丸い屋根（ドーム）」を意味します。',
    expertExplEn: 'Dome represents a rounded vault forming the roof of a structure.',
    basicKW: 'Head',
    basicHint: '頭',
    basicSegs: [['パキケファロサウルスは「'], ['頭', 'あたま'], ['」がヘルメットのように極めて頑丈でした。「頭」を表す英語はどれでしょう？']],
    basicOpts: [['Head', '頭（あたま）'], ['Tail', '尻尾（しっぽ）'], ['Hand', '手（て）'], ['Foot', '足（あし）']],
    basicCorrect: 0,
    basicExplJa: 'Headは「頭（ヘッド）」を意味する基礎形容詞/名詞です。',
    basicExplEn: 'Head is the upper part of the body containing the brain and eyes.'
  },
  // 12
  {
    id: 'allosaurus',
    nameJa: 'アロサウルス',
    nameEn: 'Allosaurus',
    sci: 'Allosaurus fragilis',
    phonetic: '/ˌæləˈsɔːrəs/',
    phoneticKatakana: 'アロサウルス',
    era: 'Jurassic',
    diet: 'Carnivore',
    length: '約8.5m',
    meaning: '異なるトカゲ',
    pitch: 0.6,
    triviaJa: 'ジュラ紀を代表する大型肉食恐竜で、ナイフのような鋭い歯で獲物を切り裂きました。',
    triviaEn: 'Allosaurus was a top Jurassic predator with dagger-sharp teeth.',
    expertKW: 'Tooth',
    expertHint: '歯',
    expertSegs: [['アロサウルスの口には、多くの鋭い「'], ['歯', 'は'], ['」がずらりと並んでいました。「歯（単数形）」を表す英語はどれでしょう？']],
    expertOpts: [['Tooth', '歯（は／単数形）'], ['Claw', '爪（つめ）'], ['Horn', '角（つの）'], ['Bone', '骨（ほね）']],
    expertCorrect: 0,
    expertExplJa: 'Toothは「歯」の単数形です（複数形はTeeth）。',
    expertExplEn: 'Tooth is a hard bony structure in the jaws used for biting.',
    basicKW: 'Sharp',
    basicHint: '鋭い',
    basicSegs: [['彼らの歯はよく切れるナイフのようにとても「'], ['鋭い', 'するどい'], ['」状態でした。この「鋭い」を表す英語はどれでしょう？']],
    basicOpts: [['Soft', '柔らかい（やわらかい）'], ['Sharp', '鋭い（するどい）'], ['Heavy', '重い（おもい）'], ['Slow', '遅い（おそい）']],
    basicCorrect: 1,
    basicExplJa: 'Sharpは刃物などが「鋭い」「尖っている」ことを表します。',
    basicExplEn: 'Sharp means having a thin edge or a fine point for cutting.'
  },
  // 13
  {
    id: 'carnotaurus',
    nameJa: 'カルノタウルス',
    nameEn: 'Carnotaurus',
    sci: 'Carnotaurus sastrei',
    phonetic: '/ˌkɑːrnəˈtɔːrəs/',
    phoneticKatakana: 'カルノタウルス',
    era: 'Cretaceous',
    diet: 'Carnivore',
    length: '約8.0m',
    meaning: '肉食の雄牛',
    pitch: 0.85,
    triviaJa: '目の上に牛のような2本の太いツノを持ち、極端に短い前足を持っていたスピード自慢の肉食恐竜です。',
    triviaEn: 'Carnotaurus had bull-like horns on its head and very tiny, reduced arms.',
    expertKW: 'Bull',
    expertHint: '雄牛',
    expertSegs: [['カルノタウルスは、頭に「'], ['雄牛', 'おすうし'], ['」のようなツノを持っていました。この「雄牛」を表す英語はどれでしょう？']],
    expertOpts: [['Bull', '雄牛（おすうし）'], ['Lion', 'ライオン'], ['Cat', '猫（ねこ）'], ['Wolf', '狼（おおかみ）']],
    expertCorrect: 0,
    expertExplJa: 'Bullは「雄牛（ブル）」を意味し、力強さの象徴でもあります。',
    expertExplEn: 'Bull refers to an adult male bovine animal.',
    basicKW: 'Short',
    basicHint: '短い',
    basicSegs: [['カルノタウルスの前あしは、退化して他の恐竜より非常に「'], ['短い', 'みじかい'], ['」状態でした。「短い」を表す英語はどれでしょう？']],
    basicOpts: [['Long', '長い（ながい）'], ['Short', '短い（みじかい）'], ['Tall', '背が高い（たかい）'], ['Big', '大きい（おおきい）']],
    basicCorrect: 1,
    basicExplJa: 'Shortは長さや時間が「短い」ことを意味する基礎英語です。',
    basicExplEn: 'Short means measuring a small distance from end to end.'
  },
  // 14
  {
    id: 'dilophosaurus',
    nameJa: 'ディロフォサウルス',
    nameEn: 'Dilophosaurus',
    sci: 'Dilophosaurus wetherilli',
    phonetic: '/daɪˌlɒfəˈsɔːrəs/',
    phoneticKatakana: 'ディロフォサウルス',
    era: 'Jurassic',
    diet: 'Carnivore',
    length: '約6.0m',
    meaning: '2つの頭冠を持つトカゲ',
    pitch: 1.25,
    triviaJa: '頭頂部に一対の丸いトサカを持ち、すばやく動き回って小動物を捕食していました。映画等での襟巻きや毒を吐く表現は創作です。',
    triviaEn: 'Dilophosaurus had twin circular crests on its head used for display.',
    expertKW: 'Frill',
    expertHint: '襟飾り',
    expertSegs: [['映画などでは、首に大きな「'], ['襟飾り', 'えりかざり'], ['（フリル）」を広げる姿で有名です。この「襟飾り」は英語で？']],
    expertOpts: [['Plate', '板（いた）'], ['Frill', '襟飾り／フリル'], ['Wing', '翼（つばさ）'], ['Horn', '角（つの）']],
    expertCorrect: 1,
    expertExplJa: 'Frillは、服や動物の首回りにある「ひだ飾り・襟飾り」を意味します。',
    expertExplEn: 'Frill represents a gathered or pleated border or neck display.',
    basicKW: 'Spit',
    basicHint: '吐き出す',
    basicSegs: [['映画などで、敵に毒を「'], ['吐き出す', 'はきだす'], ['」ようなおそろしい表現が描かれました。この「吐き出す」を表す英語はどれでしょう？']],
    basicOpts: [['Drink', '飲む（のむ）'], ['Spit', '吐き出す（はきだす）'], ['Eat', '食べる（たべる）'], ['Sing', '歌う（うたう）']],
    basicCorrect: 1,
    basicExplJa: 'Spitは唾や液体を「吐く・吐き出す」という意味の基礎動詞です。',
    basicExplEn: 'Spit means to eject saliva or liquid from the mouth.'
  },
  // 15
  {
    id: 'iguanodon',
    nameJa: 'イグアノドン',
    nameEn: 'Iguanodon',
    sci: 'Iguanodon bernissartensis',
    phonetic: '/ɪˈɡwɑːnədɒn/',
    phoneticKatakana: 'イグアノドン',
    era: 'Cretaceous',
    diet: 'Herbivore',
    length: '約10.0m',
    meaning: 'イグアナの歯',
    pitch: 0.8,
    triviaJa: '親指が鋭いトゲのようになっており、肉食恐竜を撃退する武器や、木の実をほじるために使われました。',
    triviaEn: 'Iguanodon had a sharp, dagger-like thumb spike used for defense.',
    expertKW: 'Thumb',
    expertHint: '親指',
    expertSegs: [['前足の「'], ['親指', 'おやゆび'], ['」に大きなトゲ状の爪があり、武器として機能していました。「親指」は英語で？']],
    expertOpts: [['Thumb', '親指（おやゆび）'], ['Finger', '指（ゆび）'], ['Toe', '足の指（あしのゆび）'], ['Head', '頭（あたま）']],
    expertCorrect: 0,
    expertExplJa: 'Thumbは手の「親指」を指します（他の指はFinger）。',
    expertExplEn: 'Thumb is the short, thick first digit of the human hand or animal equivalent.',
    basicKW: 'Plant',
    basicHint: '植物',
    basicSegs: [['イグアノドンは草や木の葉などの「'], ['植物', 'しょくぶつ'], ['」を主食とする穏やかな恐竜でした。この「植物」を表す英語はどれでしょう？']],
    basicOpts: [['Meat', '肉（にく）'], ['Fish', '魚（さかな）'], ['Plant', '植物（しょくぶつ）'], ['Stone', '石（いし）']],
    basicCorrect: 2,
    basicExplJa: 'Plantは「植物」や「草木」を表す基礎英単語です。',
    basicExplEn: 'Plant represents a living organism synthesizing nutrients in leaves.'
  },
  // 16
  {
    id: 'maiasaura',
    nameJa: 'マイアサウラ',
    nameEn: 'Maiasaura',
    sci: 'Maiasaura peeblesorum',
    phonetic: '/ˌmaɪəˈsɔːrə/',
    phoneticKatakana: 'マイアサウラ',
    era: 'Cretaceous',
    diet: 'Herbivore',
    length: '約9.0m',
    meaning: '良い母親のトカゲ',
    pitch: 0.95,
    triviaJa: '巣を作り、卵が孵化するまで温め、生まれた子供にエサを運んで育てた最初の恐竜として知られます。',
    triviaEn: 'Maiasaura is famous for nesting and caring for its babies.',
    expertKW: 'Nest',
    expertHint: '巣',
    expertSegs: [['マイアサウラは、地面を掘り下げて立派な「'], ['巣', 'す'], ['」を作って卵を温めました。この「巣」を表す英語はどれでしょう？']],
    expertOpts: [['Nest', '巣（す）'], ['Cave', '洞窟（どうくつ）'], ['Tree', '木（き）'], ['House', '家（いえ）']],
    expertCorrect: 0,
    expertExplJa: 'Nestは鳥や昆虫、爬虫類が作る「巣」を意味します。',
    expertExplEn: 'Nest is a structure made by animals to hold eggs and babies.',
    basicKW: 'Good',
    basicHint: '良い',
    basicSegs: [['マイアサウラは子育てが上手で、とても「'], ['良い', 'いい'], ['」お母さん恐竜でした。「良い」を表す英語はどれでしょう？']],
    basicOpts: [['Bad', '悪い（わるい）'], ['Good', '良い（いい）'], ['Sad', '悲しい（かなしい）'], ['Angry', '怒った（おこった）']],
    basicCorrect: 1,
    basicExplJa: 'Goodは「良い」「優れた」を意味する最も一般的な基本英語です。',
    basicExplEn: 'Good means to be desired or approved of; of high quality.'
  },
  // 17
  {
    id: 'oviraptor',
    nameJa: 'オヴィラプトル',
    nameEn: 'Oviraptor',
    sci: 'Oviraptor philoceratops',
    phonetic: '/ˌoʊvɪˈræptər/',
    phoneticKatakana: 'オヴィラプトル',
    era: 'Cretaceous',
    diet: 'Carnivore',
    length: '約2.0m',
    meaning: '卵の泥棒',
    pitch: 1.5,
    triviaJa: 'プロトケラトプスの卵を盗んで食べていたと思われて名付けられましたが、実際は自分の卵を温めて守っていた優しい恐竜でした。',
    triviaEn: 'Named "egg thief", Oviraptor was actually a protective parent.',
    expertKW: 'Egg',
    expertHint: '卵',
    expertSegs: [['化石の近くで他の恐竜の「'], ['卵', 'たまご'], ['」が見つかったことから、盗み食いを疑われました。「卵」は英語で何でしょう？']],
    expertOpts: [['Egg', '卵（たまご）'], ['Shell', '貝殻（かいがら）'], ['Nest', '巣（す）'], ['Bone', '骨（ほね）']],
    expertCorrect: 0,
    expertExplJa: 'Eggは鳥や爬虫類が産む「卵」を意味します。',
    expertExplEn: 'Egg is an oval object laid by female birds, reptiles, or dinosaurs.',
    basicKW: 'Thief',
    basicHint: '泥棒',
    basicSegs: [['オヴィラプトルは、かつて卵を盗む「'], ['泥棒', 'どろぼう'], ['」と誤解されていました。この「泥棒・ドロボー」を表す英語はどれでしょう？']],
    basicOpts: [['Hunter', 'ハンター'], ['Thief', '泥棒（どろぼう）'], ['Leader', '指導者（りーだー）'], ['Helper', '手伝う人（へるぱー）']],
    basicCorrect: 1,
    basicExplJa: 'Thief防は他人の持ち物を盗む「泥棒・コソ泥」を意味します。',
    basicExplEn: 'Thief is a person or animal who steals another person\'s property.'
  },
  // 18
  {
    id: 'argentinosaurus',
    nameJa: 'アルゼンチノサウルス',
    nameEn: 'Argentinosaurus',
    sci: 'Argentinosaurus huinculensis',
    phonetic: '/ˌɑːrdʒənˌtiːnoʊˈsɔːrəs/',
    phoneticKatakana: 'アルゼンチノサウルス',
    era: 'Cretaceous',
    diet: 'Herbivore',
    length: '約30.0〜35.0m',
    meaning: 'アルゼンチンのトカゲ',
    pitch: 0.3,
    triviaJa: '地球の歴史上で最大の陸上動物のひとつで、重さは70トン以上（ゾウ約12頭分）もありました。',
    triviaEn: 'One of the largest land animals in Earth\'s history, weighing up to 70 tons.',
    expertKW: 'Giant',
    expertHint: '巨人',
    expertSegs: [['アルゼンチノサウルスはまるで、歩く「'], ['巨人', 'きょじん'] ,['」のようでした。この「巨人」を意味する英語はどれでしょう？']],
    expertOpts: [['Dwarf', '小人（こびと）'], ['Giant', '巨人／巨大生物（じゃいあんと）'], ['Fossil', '化石（かせき）'], ['Insect', '昆虫（こんchuu）']],
    expertCorrect: 1,
    expertExplJa: 'Giantは極めて体格が大きな「巨人」「巨大生物」を意味します。',
    expertExplEn: 'Giant describes a creature of abnormally large size.',
    basicKW: 'Heavy',
    basicHint: '重い',
    basicSegs: [['体重は70トンを超え、地面が揺れるほど極めて「'], ['重い', 'おもい'], ['」恐竜でした。「重い」を表す英語はどれでしょう？']],
    basicOpts: [['Light', '軽い（かるい）'], ['Heavy', '重い（おもい）'], ['Fast', '速い（はやい）'], ['Cold', '冷たい（つめたい）']],
    basicCorrect: 1,
    basicExplJa: 'Heavyは、重量が「重い」ことを表す基礎英単語です。',
    basicExplEn: 'Heavy means of great weight; difficult to lift or move.'
  },
  // 19
  {
    id: 'deinonychus',
    nameJa: 'デイノニクス',
    nameEn: 'Deinonychus',
    sci: 'Deinonychus antirrhopus',
    phonetic: '/daɪˈnɒnɪkəs/',
    phoneticKatakana: 'デイノニクス',
    era: 'Cretaceous',
    diet: 'Carnivore',
    length: '約3.4m',
    meaning: '恐ろしい爪',
    pitch: 1.6,
    triviaJa: '後ろ足にある非常に大きくて鋭い「カマのようなかぎ爪」が最大の特徴で、ジャンプして獲物に襲いかかりました。',
    triviaEn: 'Deinonychus had a large, sickle-like claw on each hind foot for hunting.',
    expertKW: 'Sickle',
    expertHint: '草刈り鎌',
    expertSegs: [['彼らの爪は、草を刈る「'], ['鎌', 'かま'], ['」のような形をしていました。この「草刈り鎌（シックル）」を表す英語はどれでしょう？']],
    expertOpts: [['Sword', '剣（けん）'], ['Shield', '盾（たて）'], ['Sickle', '草刈り鎌（しっくる）'], ['Arrow', '矢（や）']],
    expertCorrect: 2,
    expertExplJa: 'Sickleは半月型をした農具の「草刈り鎌（シックル）」を指します。',
    expertExplEn: 'Sickle is a short-handled farming tool with a curved blade.',
    basicKW: 'Jump',
    basicHint: '跳ぶ',
    basicSegs: [['デイノニクスは強靭な足腰を使い、高く「'], ['跳ぶ', 'とぶ'], ['」ことが得意でした。「ジャンプする・跳ぶ」を表す英語はどれでしょう？']],
    basicOpts: [['Run', '走る（はしる）'], ['Swim', '泳ぐ（およぐ）'], ['Jump', '跳ぶ（とぶ）'], ['Sleep', '眠る（ねむる）']],
    basicCorrect: 2,
    basicExplJa: 'Jumpは、空中に飛び上がる「跳ぶ」「ジャンプする」を意味します。',
    basicExplEn: 'Jump means to push off the ground with legs to suspend in the air.'
  },
  // 20
  {
    id: 'gallimimus',
    nameJa: 'ガリミムス',
    nameEn: 'Gallimimus',
    sci: 'Gallimimus bullatus',
    phonetic: '/ˌɡælɪˈmaɪməs/',
    phoneticKatakana: 'ガリミムス',
    era: 'Cretaceous',
    diet: 'Herbivore',
    length: '約6.0m',
    meaning: '鶏に似たもの',
    pitch: 1.45,
    triviaJa: '現代のダチョウのように長い首と脚を持ち、歯のないクチバシで植物や昆虫を食べ、時速60キロで走りました。',
    triviaEn: 'Gallimimus looked like an ostrich and could run incredibly fast.',
    expertKW: 'Beak',
    expertHint: 'クチバシ',
    expertSegs: [['ガリミムスには歯がなく、鳥のような「'], ['クチバシ', 'くちばし'], ['」を持っていました。この「クチバシ」は英語で何でしょう？']],
    expertOpts: [['Tooth', '歯（は）'], ['Beak', 'クチバシ（びーく）'], ['Horn', '角（つの）'], ['Claw', '爪（つめ）']],
    expertCorrect: 1,
    expertExplJa: 'Beakは、鳥類などの硬い「クチバシ」を表します。',
    expertExplEn: 'Beak is the hard, pointed outer mouth parts of a bird or dinosaur.',
    basicKW: 'Run',
    basicHint: '走る',
    basicSegs: [['ダチョウのような長い脚で、大平原をとても速く「'], ['走る', 'はしる'], ['」ことができました。「走る」を表す英語はどれでしょう？']],
    basicOpts: [['Walk', '歩く（あるく）'], ['Run', '走る（はしる）'], ['Fly', '飛ぶ（とぶ）'], ['Swim', '泳ぐ（およぐ）']],
    basicCorrect: 1,
    basicExplJa: 'Runは、すばやく移動する「走る」を表す基礎動詞です。',
    basicExplEn: 'Run means to move at a speed faster than a walk.'
  },
  // 21
  {
    id: 'suchomimus',
    nameJa: 'スコミムス',
    nameEn: 'Suchomimus',
    sci: 'Suchomimus tenerensis',
    phonetic: '/ˌsuːkoʊˈmaɪməs/',
    phoneticKatakana: 'スコミムス',
    era: 'Cretaceous',
    diet: 'Piscivore',
    length: '約11.0m',
    meaning: 'ワニに似たもの',
    pitch: 0.7,
    triviaJa: '細長く伸びたワニのような口先（吻部）が特徴で、主に水辺で魚をハントして暮らしていました。',
    triviaEn: 'Suchomimus had a long crocodile-like snout designed to catch fish.',
    expertKW: 'Snout',
    expertHint: '口先',
    expertSegs: [['ワニのように細長く前に突き出た「'], ['口先', 'くちさき'], ['（鼻づら）」が特徴です。この「口先・鼻先」を意味する英語は？']],
    expertOpts: [['Snout', '口先／鼻先（すなうと）'], ['Ear', '耳（みみ）'], ['Tail', '尻尾（しっぽ）'], ['Wing', '翼（つばさ）']],
    expertCorrect: 0,
    expertExplJa: 'Snoutは、犬や豚、ワニなどの突出した「口先・鼻面」を指します。',
    expertExplEn: 'Snout represents the projecting nose and mouth of an animal.',
    basicKW: 'River',
    basicHint: '川',
    basicSegs: [['彼らは魚を捕まえるために、主に「'], ['川', 'かわ'], ['」の近くで過ごしていました。この「川」を表す英語はどれでしょう？']],
    basicOpts: [['Sea', '海（うみ）'], ['River', '川（かわ）'], ['Sky', '空（そら）'], ['Mountain', '山（やま）']],
    basicCorrect: 1,
    basicExplJa: 'Riverは流れのある「川」「河川」を指す基礎英単語です。',
    basicExplEn: 'River is a large natural stream of water flowing in a channel.'
  },
  // 22
  {
    id: 'giganotosaurus',
    nameJa: '...ギガノトサウルス',
    nameEn: 'Giganotosaurus',
    sci: 'Giganotosaurus carolinii',
    phonetic: '/ˌdʒɪɡəˌnoʊtəˈsɔːrəs/',
    phoneticKatakana: 'ギガノトサウルス',
    era: 'Cretaceous',
    diet: 'Carnivore',
    length: '約13.0m',
    meaning: '南の巨大なトカゲ',
    pitch: 0.45,
    triviaJa: 'ティラノサウルスに匹敵するか、それ以上に巨大な体躯を持っていた南米アルゼンチンの最強肉食恐竜です。',
    triviaEn: 'Giganotosaurus was one of the largest land carnivores ever found.',
    expertKW: 'Hunter',
    expertHint: '猟師',
    expertSegs: [['南半球の王者として、数々の草食恐竜を狩っていた「'], ['猟師', 'りょうし'], ['（捕食者）」でした。この「ハンター」を表す英語はどれでしょう？']],
    expertOpts: [['Helper', '助け手（へるぱー）'], ['Hunter', 'ハンター／猟師'], ['Fossil', '化石（かせき）'], ['Doctor', '医者（どくたー）']],
    expertCorrect: 1,
    expertExplJa: 'Hunterは獲物を追う「猟師」「ハンター」「狩人」を意味します。',
    expertExplEn: 'Hunter refers to a person or animal that hunts game for food.',
    basicKW: 'Huge',
    basicHint: 'とても大きい',
    basicSegs: [['ギガノトサウルスはティラノサウルスを超えるほど「'], ['巨大', 'きょだい'], ['」な体をしていました。この「とても大きい」を表す英語はどれでしょう？']],
    basicOpts: [['Small', '小さい（すもーる）'], ['Huge', '巨大な／とても大きい'], ['Short', '短い（しょーと）'], ['Thin', '薄い（しん）']],
    basicCorrect: 1,
    basicExplJa: 'Hugeは、BigやLargeよりもさらに規格外に「巨大な」ことを意味します。',
    basicExplEn: 'Huge means extremely large; colossal or enormous.'
  },
  // 23
  {
    id: 'therizinosaurus',
    nameJa: 'テリジノサウルス',
    nameEn: 'Therizinosaurus',
    sci: 'Therizinosaurus cheloniformis',
    phonetic: '/ˌθɛrɪˌzɪnoʊˈsɔːrəs/',
    phoneticKatakana: 'テリジノサウルス',
    era: 'Cretaceous',
    diet: 'Herbivore',
    length: '約10.0m',
    meaning: '刈り取り機のトカゲ',
    pitch: 0.75,
    triviaJa: '前足に長さ1メートルに達する世界最長の大ガマのような爪を持っていました。肉食ではなく植物をちぎって食べていました。',
    triviaEn: 'Therizinosaurus possessed giant, 1-meter-long scythe claws for gathering plants.',
    expertKW: 'Scythe',
    expertHint: '大鎌',
    expertSegs: [['彼らの手の爪は、死神が持つような巨大な「'], ['大鎌', 'おおがま'], ['」のようでした。この「大鎌（サイス）」を表す英語はどれでしょう？']],
    expertOpts: [['Sword', '剣（けん）'], ['Scythe', '大鎌（さいす）'], ['Shield', '盾（たて）'], ['Armor', '鎧（よろい）']],
    expertCorrect: 1,
    expertExplJa: 'Scytheは農具または死神が持つ「両手用の大鎌（サイス）」を指します。',
    expertExplEn: 'Scythe is a tool with a long, curved blade for cutting crops.',
    basicKW: 'Long',
    basicHint: '長い',
    basicSegs: [['テリジノサウルスの爪は、地球の動物の歴史の中で一番「'], ['長い', 'ながい'], ['」ものでした。「長い」を表す英語はどれでしょう？']],
    basicOpts: [['Short', '短い（みじかい）'], ['Long', '長い（ながい）'], ['Little', '小さい（りとる）'], ['Warm', '温かい（わーむ）']],
    basicCorrect: 1,
    basicExplJa: 'Longは「長い」を指します。テリジノサウルスの爪は1メートル近くありました。',
    basicExplEn: 'Long means extending a relatively great distance in space.'
  },
  // 24
  {
    id: 'protoceratops',
    nameJa: 'プロトケラトプス',
    nameEn: 'Protoceratops',
    sci: 'Protoceratops andrewsi',
    phonetic: '/ˌproʊtoʊˈsɛrətɒps/',
    phoneticKatakana: 'プロトケラトプス',
    era: 'Cretaceous',
    diet: 'Herbivore',
    length: '約1.8m',
    meaning: '最初の角を持つ顔',
    pitch: 1.3,
    triviaJa: 'トリケラトプスの祖先に近い、角のない小さな恐竜です。オウムのような硬いクチバシで硬い砂漠の植物をかじり取っていました。',
    triviaEn: 'A sheep-sized early ceratopsian dinosaur with a prominent beak.',
    expertKW: 'Beak',
    expertHint: 'クチバシ',
    expertSegs: [['トリケラトプスの親戚ですが、鼻先に角はなく、オウムのような頑丈な「'], ['クチバシ', 'くちばし'], ['」がありました。「クチバシ」は英語で？']],
    expertOpts: [['Beak', 'クチバシ（びーく）'], ['Tooth', '歯（は）'], ['Horn', '角（つの）'], ['Tail', '尻尾（しっぽ）']],
    expertCorrect: 0,
    expertExplJa: 'Beakは鳥や一部の恐竜が持つ硬い「クチバシ」です。',
    expertExplEn: 'Beak is the hornlike external projection of the jaws of a bird or dinosaur.',
    basicKW: 'Small',
    basicHint: '小さい',
    basicSegs: [['トリケラトプスに比べて、プロトケラトプスの体はヒツジ程度で非常に「'], ['小さい', 'ちいさい'], ['」サイズでした。「小さい」を表す英語はどれでしょう？']],
    basicOpts: [['Big', '大きい（びっぐ）'], ['Small', '小さい（すもーる）'], ['Huge', '巨大な（ひゅーじ）'], ['Long', '長い（ろんぐ）']],
    basicCorrect: 1,
    basicExplJa: 'Smallはサイズや規模が「小さい」ことを指す基礎英単語です。',
    basicExplEn: 'Small means size that is less than normal or average.'
  },
  // 25
  {
    id: 'pachyrhinosaurus',
    nameJa: 'パキリノサウルス',
    nameEn: 'Pachyrhinosaurus',
    sci: 'Pachyrhinosaurus lakustai',
    phonetic: '/ˌpækɪˌraɪnoʊˈsɔːrəs/',
    phoneticKatakana: 'パキリノサウルス',
    era: 'Cretaceous',
    diet: 'Herbivore',
    length: '約8.0m',
    meaning: '分厚い鼻のトカゲ',
    pitch: 0.72,
    triviaJa: 'トリケラトプスの仲間ですが、鼻先には突き出た角がなく、代わりに「骨の分厚いコブ」が形成されていました。',
    triviaEn: 'Pachyrhinosaurus had thick, flat bony bosses on its nose instead of horns.',
    expertKW: 'Boss',
    expertHint: '突起・コブ',
    expertSegs: [['鼻の上にある平らで大きく分厚い骨の「'], ['コブ', 'こぶ'], ['（突起）」で頭突きを行っていました。この「コブ・骨のコブ」は英語で？']],
    expertOpts: [['Boss', '骨のコブ／突起（ぼす）'], ['Horn', '角（つの）'], ['Wing', '翼（つばさ）'], ['Tail', '尻尾（しっぽ）']],
    expertCorrect: 0,
    expertExplJa: '骨のコブ状の部位を「Boss（ボス）」と呼びます。',
    expertExplEn: 'Boss refers to a circular, knob-like bone structure on a skull.',
    basicKW: 'Flat',
    basicHint: '平らな',
    basicSegs: [['彼らの鼻の上のコブは尖っておらず、上部が非常に「'], ['平ら', 'たいら'], ['」になっていました。この「平らな」を表す英語はどれでしょう？']],
    basicOpts: [['Sharp', '鋭い（しゃーぷ）'], ['Flat', '平らな（ふらっと）'], ['High', '高い（はい）'], ['Deep', '深い（でぃーぷ）']],
    basicCorrect: 1,
    basicExplJa: 'Flatは平坦な「平らな」「凹凸のない」を意味する基礎英語です。',
    basicExplEn: 'Flat means having a level, even surface with no raised parts.'
  },
  // 26
  {
    id: 'struthiomimus',
    nameJa: 'ストルティオミムス',
    nameEn: 'Struthiomimus',
    sci: 'Struthiomimus altus',
    phonetic: '/ˌstruːθioʊˈmaɪməs/',
    phoneticKatakana: 'ストルティオミムス',
    era: 'Cretaceous',
    diet: 'Herbivore',
    length: '約4.3m',
    meaning: 'ダチョウの模倣者',
    pitch: 1.55,
    triviaJa: '極めてスマートな体つきで、現代のダチョウのように素早いステップを踏んでサバンナを走り抜けました。',
    triviaEn: 'Struthiomimus had long legs and a toothless beak, looking very much like an ostrich.',
    expertKW: 'Ostrich',
    expertHint: 'ダチョウ',
    expertSegs: [['その骨格が現代の「'], ['ダチョウ', 'だちょう'], ['」にそっくりだったため、この名前がつきました。「ダチョウ」は英語で？']],
    expertOpts: [['Eagle', 'ワシ'], ['Ostrich', 'ダチョウ（おーすとりっち）'], ['Penguin', 'ペンギン'], ['Stork', 'コウノトリ']],
    expertCorrect: 1,
    expertExplJa: 'Ostrichは世界最大の走鳥類「ダチョウ」を意味します。',
    expertExplEn: 'Ostrich is a flightless swift-running African bird.',
    basicKW: 'Speed',
    basicHint: '速さ',
    basicSegs: [['ストルティオミムスは、天敵から逃げるための素晴らしい「'], ['速さ', 'はやさ'], ['」（スピード）を持っていました。この「速さ」を表す英語は？']],
    basicOpts: [['Weight', '重さ（うぇいと）'], ['Speed', '速さ／スピード'], ['Sound', '音（さうんど）'], ['Color', '色（からー）']],
    basicCorrect: 1,
    basicExplJa: 'Speedは物事が進む「速度」「スピード」「速さ」を意味する基本名詞です。',
    basicExplEn: 'Speed represents the rate at which someone or something is able to move.'
  },
  // 27
  {
    id: 'coelophysis',
    nameJa: 'シーロフィシス',
    nameEn: 'Coelophysis',
    sci: 'Coelophysis bauri',
    phonetic: '/ˌsɛlɒfɪsɪs/',
    phoneticKatakana: 'シーロフィシス',
    era: 'Triassic',
    diet: 'Carnivore',
    length: '約3.0m',
    meaning: '中空の骨',
    pitch: 1.8,
    triviaJa: '三畳紀の俊敏な肉食恐竜で、骨が鳥のように中空だったため非常に体が軽量でした。',
    triviaEn: 'Coelophysis was an early dinosaur with lightweight, hollow bones.',
    expertKW: 'Hollow',
    expertHint: '中空の',
    expertSegs: [['シーロフィシスは、骨の内部が「'], ['空洞', 'くうどう'], ['」になっていました。この「中空の」「中が空の」を表す英語は？']],
    expertOpts: [['Solid', '中身が詰まった'], ['Hollow', '中空の／空洞の（ほろう）'], ['Heavy', '重い'], ['Hard', '固い']],
    expertCorrect: 1,
    expertExplJa: 'Hollowは「中空の」「内部が空洞の」を意味します。',
    expertExplEn: 'Hollow means having a cavity or empty space inside.',
    basicKW: 'Bone',
    basicHint: '骨',
    basicSegs: [['空洞になっていたのは彼らの「'], ['骨', 'ほね'], ['」でした。この「骨（ボーン）」を意味する英語はどれでしょう？']],
    basicOpts: [['Meat', '肉（にく）'], ['Skin', '皮膚（ひふ）'], ['Bone', '骨（ほね）'], ['Hair', '毛（け）']],
    basicCorrect: 2,
    basicExplJa: 'Boneは動物の体を支える「骨」を表す基礎英語です。',
    basicExplEn: 'Bone is any of the pieces of hard tissue making up the skeleton.'
  },
  // 28
  {
    id: 'diplodocus',
    nameJa: 'ディプロドクス',
    nameEn: 'Diplodocus',
    sci: 'Diplodocus longus',
    phonetic: '/dɪˈplɒdəkəs/',
    phoneticKatakana: 'ディプロドクス',
    era: 'Jurassic',
    diet: 'Herbivore',
    length: '約27.0m',
    meaning: '二重の梁',
    pitch: 0.42,
    triviaJa: '極めて細長尾を持ち、その先端をムチのように超高速で振ることで、音速を超えて大きな破裂音を出せた可能性があります。',
    triviaEn: 'Diplodocus had an incredibly long tail that acted like a whip.',
    expertKW: 'Tail',
    expertHint: '尻尾',
    expertSegs: [['彼らの体の半分以上は、非常に長い「'], ['尻尾', 'しっぽ'], ['」が占めていました。この「尻尾」を表す英語はどれでしょう？']],
    expertOpts: [['Tail', '尻尾（しっぽ）'], ['Neck', '首（くび）'], ['Wing', '翼（つばさ）'], ['Horn', '角（つの）']],
    expertCorrect: 0,
    expertExplJa: 'Tailは脊椎動物の後部に伸びる「尻尾（テイル）」を指します。',
    expertExplEn: 'Tail is the hindmost part of an animal, especially forming a flexible appendage.',
    basicKW: 'Whip',
    basicHint: '鞭',
    basicSegs: [['ディプロドクスは尻尾を「'], ['ムチ', 'むち'], ['」のように激しく振り回して、音を出したり敵を攻撃しました。この「鞭」は英語で？']],
    basicOpts: [['Shield', '盾（たて）'], ['Whip', '鞭（むち）'], ['Sword', '剣（けん）'], ['Stone', '石（いし）']],
    basicCorrect: 1,
    basicExplJa: 'Whipは「ムチ（ホイップ）」、またはムチのように振ることを意味します。',
    basicExplEn: 'Whip is a strip of leather or cord used for driving animals or striking.'
  },
  // 29
  {
    id: 'apatosaurus',
    nameJa: 'アパトサウルス',
    nameEn: 'Apatosaurus',
    sci: 'Apatosaurus ajax',
    phonetic: '/əˌpætəˈsɔːrəs/',
    phoneticKatakana: 'アパトサウルス',
    era: 'Jurassic',
    diet: 'Herbivore',
    length: '約22.0m',
    meaning: 'だますトカゲ',
    pitch: 0.41,
    triviaJa: 'モササウルスの骨と似ていて学者を困惑させたことから「だますトカゲ」と名付けられました。かつてブロントサウルスと呼ばれた代表的な恐竜です。',
    triviaEn: 'Named "deceptive lizard" due to its bones resembling marine reptiles.',
    expertKW: 'Deceit',
    expertHint: 'だますこと',
    expertSegs: [['発見時、骨が他の爬虫類に似ていて学者を困惑させたため「'], ['だます', 'だます'], ['」という意味の名がつきました。この「詐欺／欺き」を表す英語は？']],
    expertOpts: [['Trust', '信頼（とらすと）'], ['Deceit', 'だますこと／欺き（でぃしーと）'], ['Friend', '友達（ふれんど）'], ['Leader', 'リーダー']],
    expertCorrect: 1,
    expertExplJa: 'Deceitは相手を「だますこと」「欺瞞」「詐欺」を意味します。',
    expertExplEn: 'Deceit means the action of deceiving someone by concealing the truth.',
    basicKW: 'Weight',
    basicHint: '重さ',
    basicSegs: [['彼らの体重は20トンもあり、ものすごい「'], ['重さ', 'おもさ'], ['」で大地を揺らしました。この「重さ・重量」を表す英語は？']],
    basicOpts: [['Speed', 'スピード'], ['Weight', '重さ／重量（うぇいと）'], ['Color', '色（からー）'], ['Sound', '音（さうんど）']],
    basicCorrect: 1,
    basicExplJa: 'Weightは物や人の「体重」「重量」「重さ（ウェイト）」を表す基礎名詞です。',
    basicExplEn: 'Weight is a body\'s relative mass or the quantity of matter contained by it.'
  },
  // 30
  {
    id: 'amargasaurus',
    nameJa: 'アマルガサウルス',
    nameEn: 'Amargasaurus',
    sci: 'Amargasaurus cazaui',
    phonetic: '/əˌmɑːrɡəˈsɔːrəs/',
    phoneticKatakana: 'アマルガサウルス',
    era: 'Cretaceous',
    diet: 'Herbivore',
    length: '約10.0m',
    meaning: 'アマルガのトカゲ',
    pitch: 0.52,
    triviaJa: '首から背中にかけて、2列に並ぶ鋭いトゲ（脊椎棘）が突き出ている、非常に個性的な首長竜です。',
    triviaEn: 'Amargasaurus had two parallel rows of high spines along its neck.',
    expertKW: 'Spine',
    expertHint: '棘・背骨',
    expertSegs: [['首の骨から突き出た、2列の鋭い「'], ['トゲ', 'とげ'], ['（棘突起）」が一番の特徴です。この「棘・背骨・突起」を表す英語はどれでしょう？']],
    expertOpts: [['Spine', 'トゲ／棘突起／背骨（すぱいん）'], ['Wing', '翼（つばさ）'], ['Flipper', 'ひれ（ふりっぱー）'], ['Armor', '鎧（よろい）']],
    expertCorrect: 0,
    expertExplJa: 'Spineは「トゲ」「背骨（スパイン）」「突起」を表す専門語彙です。',
    expertExplEn: 'Spine represents any hard, pointed defensive projection or backbone.',
    basicKW: 'Neck',
    basicHint: '首',
    basicSegs: [['この2本並びのトゲは、彼らの長い「'], ['首', 'くび'], ['」に沿って並んでいました。この「首」を表す英語はどれでしょう？']],
    basicOpts: [['Head', '頭（あたま）'], ['Tail', '尻尾（しっぽ）'], ['Neck', '首（くび）'], ['Leg', '足（あし）']],
    basicCorrect: 2,
    basicExplJa: 'Neckは「首（ネック）」を意味する体の基礎単語です。',
    basicExplEn: 'Neck is the part of the body connecting the head and shoulders.'
  },
  // 31
  {
    id: 'kentrosaurus',
    nameJa: 'ケントロサウルス',
    nameEn: 'Kentrosaurus',
    sci: 'Kentrosaurus aethiopicus',
    phonetic: '/ˌkɛntrəˈsɔːrəs/',
    phoneticKatakana: 'ケントロサウルス',
    era: 'Jurassic',
    diet: 'Herbivore',
    length: '約4.5m',
    meaning: '棘のあるトカゲ',
    pitch: 0.82,
    triviaJa: 'ステゴサウルスの仲間ですが、背中の後半部分や尻尾、腰には板ではなく、非常に鋭い多数の「トゲ（棘）」が生えていました。',
    triviaEn: 'Kentrosaurus had sharp, long spikes instead of plates on its lower back.',
    expertKW: 'Spike',
    expertHint: 'スパイク・長いトゲ',
    expertSegs: [['ケントロサウルスの体の後半部には、鋭い「'], ['トゲ', 'とげ'], ['」が多数生えていました。この「長いトゲ・スパイク」を表す英語は？']],
    expertOpts: [['Plate', '板（ぷれーと）'], ['Spike', '長いトゲ／スパイク'], ['Armor', '鎧（よろい）'], ['Wing', '翼（つばさ）']],
    expertCorrect: 1,
    expertExplJa: 'Spikeは「尖ったトゲ」「スパイク」「スパイク靴のピン」を指します。',
    expertExplEn: 'Spike represents a thin, pointed piece of metal, wood, or bone.',
    basicKW: 'Rear',
    basicHint: '後ろの',
    basicSegs: [['鋭いトゲは、体の「'], ['後ろ半分', 'うしろはんぶん'], ['」に集中して生えていました。この「後ろの」を表す英語はどれでしょう？']],
    basicOpts: [['Front', '前方の（ふろんと）'], ['Rear', '後方の／後ろの（りあ）'], ['Top', '頂上の（とっぷ）'], ['Under', '下の（あんだー）']],
    basicCorrect: 1,
    basicExplJa: 'Rearは、前（Front）の反対の「後部」「後ろの」を意味します。',
    basicExplEn: 'Rear is the back part of something, especially of a building or body.'
  },
  // 32
  {
    id: 'stygimoloch',
    nameJa: 'スティギモロク',
    nameEn: 'Stygimoloch',
    sci: 'Stygimoloch spinifer',
    phonetic: '/ˌstɪdʒɪˈmɒlək/',
    phoneticKatakana: 'スティギモロク',
    era: 'Cretaceous',
    diet: 'Herbivore',
    length: '約3.0m',
    meaning: '地獄の川からの悪魔',
    pitch: 1.15,
    triviaJa: 'パキケファロサウルスの若者とする説もあります。頭頂部の丸いコブの周りに、多数の尖った長いトゲを持っています。',
    triviaEn: 'Known as the "demon from the river Styx" due to its thorn-covered skull.',
    expertKW: 'Thorn',
    expertHint: 'イバラのトゲ',
    expertSegs: [['スティギモロクの頭には、草木の「'], ['トゲ', 'とげ'], ['」のような小さな鋭い突起が多数ありました。この「草木のトゲ・イバラ」は英語で？']],
    expertOpts: [['Plate', '板（ぷれーと）'], ['Thorn', '草木のトゲ／イバラ（そーん）'], ['Armor', '鎧（よろい）'], ['Crest', 'トサカ']],
    expertCorrect: 1,
    expertExplJa: 'Thornは、植物（イバラなど）の鋭い「トゲ（ソーン）」を意味します。',
    expertExplEn: 'Thorn represents a sharp-pointed woody projection on a plant or similar structure.',
    basicKW: 'Demon',
    basicHint: '悪魔',
    basicSegs: [['その凶悪なツノの見た目から、名前には「'], ['悪魔', 'あくま'], ['」という意味が入っています。この「悪魔・鬼」を表す英語はどれでしょう？']],
    basicOpts: [['Angel', '天使（えんじぇる）'], ['Demon', '悪魔（でーもん）'], ['King', '王様（きんぐ）'], ['Hero', '勇者（ひーろー）']],
    basicCorrect: 1,
    basicExplJa: 'Demonは、人間に害をなす邪悪な「悪魔」「鬼」を表します。',
    basicExplEn: 'Demon is an evil spirit or devil, especially in religious beliefs.'
  },
  // 33
  {
    id: 'torosaurus',
    nameJa: 'トロサウルス',
    nameEn: 'Torosaurus',
    sci: 'Torosaurus latus',
    phonetic: '/ˌtɔːroʊˈsɔːrəs/',
    phoneticKatakana: 'トロサウルス',
    era: 'Cretaceous',
    diet: 'Herbivore',
    length: '約8.0m',
    meaning: '穴の空いたトカゲ',
    pitch: 0.68,
    triviaJa: '陸上動物の歴史の中で、最大の頭骨（フリルの幅が2.7メートル超）を持つ恐竜です。フリルには軽量化のための大きな穴がありました。',
    triviaEn: 'Torosaurus had one of the largest skulls of any land animal, with holes in its frill.',
    expertKW: 'Perforated',
    expertHint: '穴の空いた',
    expertSegs: [['首のフリルの骨には、軽量化のためにたくさんの「'], ['穴が空いて', 'あながあいて'], ['」いました。この「穴が空いた・貫通した」を指す単語は？']],
    expertOpts: [['Perforated', '穴の空いた（ぱーふぉれいてっど）'], ['Solid', '密な（そりっど）'], ['Hard', '固い（はーど）'], ['Broken', '壊れた']],
    expertCorrect: 0,
    expertExplJa: 'Perforatedは、多数の穴がポツポツ空けられた「穴あき」の状態を意味します。',
    expertExplEn: 'Perforated means pierced with a hole or holes.',
    basicKW: 'Shield',
    basicHint: '盾',
    basicSegs: [['大きなフリルは、ティラノサウルスの攻撃から首を守る巨大な「'], ['盾', 'たて'], ['」の役割をしていました。この「盾（シールド）」を表す英語は？']],
    basicOpts: [['Sword', '剣（けん）'], ['Whip', '鞭（むち）'], ['Shield', '盾（しーるど）'], ['Arrow', '矢（や）']],
    basicCorrect: 2,
    basicExplJa: 'Shieldは、攻撃を防ぐための防具「盾（シールド）」を意味します。',
    basicExplEn: 'Shield is a broad piece of armor carried on the arm for protection.'
  },
  // 34
  {
    id: 'microraptor',
    nameJa: 'ミクロラプトル',
    nameEn: 'Microraptor',
    sci: 'Microraptor zhaoianus',
    phonetic: '/ˌmaɪkroʊˈræptər/',
    phoneticKatakana: 'ミクロラプトル',
    era: 'Cretaceous',
    diet: 'Carnivore',
    length: '約0.8m',
    meaning: '非常に小さい泥棒',
    pitch: 1.9,
    triviaJa: '手足の4つの脚すべてに長い翼羽（フライトフェザー）が並んでおり、森の木々をグライダーのように滑空していました。',
    triviaEn: 'A tiny dromaeosaurid dinosaur with long flight feathers on all four limbs.',
    expertKW: 'Feather',
    expertHint: '羽毛',
    expertSegs: [['ミクロラプトルは、カラスのように全身が黒い「'], ['羽毛', 'うもう'], ['」に包まれていました。この「羽毛」は英語で何でしょう？']],
    expertOpts: [['Scale', '鱗（すけいる）'], ['Feather', '羽毛（ふぇざー）'], ['Skin', '皮膚（すきん）'], ['Armor', '鎧（あーまー）']],
    expertCorrect: 1,
    expertExplJa: 'Featherは鳥類などの軽くてふんわりした「羽毛」「羽」を指します。',
    expertExplEn: 'Feather represents any of the flat appendages growing from a bird\'s skin.',
    basicKW: 'Four',
    basicHint: '4つ',
    basicSegs: [['彼らは、前あしと後ろあしの合計「'], ['4つ', 'よっつ'], ['」の翼を広げて空を滑空しました。「4」を表す英語はどれでしょう？']],
    basicOpts: [['Two', '2つ（とぅー）'], ['Three', '3つ（すりー）'], ['Four', '4つ（ふぉー）'], ['Five', '5つ（ふぁいぶ）']],
    basicCorrect: 2,
    basicExplJa: 'Fourは「4つ」を表す基礎英語の数字です。',
    basicExplEn: 'Four is the number equivalent to the sum of three and one.'
  },
  // 35
  {
    id: 'archaeopteryx',
    nameJa: 'アルカエオプテリクス',
    nameEn: 'Archaeopteryx',
    sci: 'Archaeopteryx lithographica',
    phonetic: '/ˌaːrkiˈɒptərɪks/',
    phoneticKatakana: 'アーケオプテリクス（始祖鳥）',
    era: 'Jurassic',
    diet: 'Carnivore',
    length: '約0.5m',
    meaning: '古代の翼',
    pitch: 2.0,
    triviaJa: '「始祖鳥（しそちょう）」として有名な、恐竜から鳥への進化の途中にある生き物です。羽毛があり、口にはまだ歯、翼には指爪がありました。',
    triviaEn: 'The famous "first bird", showing a clear evolutionary link between dinosaurs and birds.',
    expertKW: 'Bird',
    expertHint: '鳥',
    expertSegs: [['アルカエオプテリクスは、もっとも古い「'], ['鳥', 'とり'], ['」の祖先（始祖鳥）と考えられています。この「鳥」は英語で？']],
    expertOpts: [['Bird', '鳥（ばーど）'], ['Fish', '魚（ふぃっしゅ）'], ['Lizard', 'トカゲ（りざーど）'], ['Frog', 'カエル']],
    expertCorrect: 0,
    expertExplJa: 'Birdは「鳥類」「鳥（バード）」を意味する基礎名詞です。',
    expertExplEn: 'Bird represents a feathered, winged, warm-blooded egg-laying vertebrate.',
    basicKW: 'Old',
    basicHint: '古い',
    basicSegs: [['彼らは、現代 of 鳥たちのなかでも極めて「'], ['古い', 'ふるい'], ['」歴史を持っています。「古い」を表す英語はどれでしょう？']],
    basicOpts: [['New', '新しい（にゅー）'], ['Old', '古い（おーるど）'], ['Fast', '速い（ふぁすと）'], ['Soft', '柔らかい（そふと）']],
    basicCorrect: 1,
    basicExplJa: 'Oldは新しさの対義語である「古い」「古びた」を意味します。',
    basicExplEn: 'Old means having lived or existed for a long time.'
  },
  // 36
  {
    id: 'mosasaurus',
    nameJa: 'モササウルス',
    nameEn: 'Mosasaurus',
    sci: 'Mosasaurus hoffmannii',
    phonetic: '/ˌmoʊzəˈsɔːrəs/',
    phoneticKatakana: 'モササウルス',
    era: 'Cretaceous',
    diet: 'Carnivore',
    length: '約15.0〜18.0m',
    meaning: 'マース川のトカゲ',
    pitch: 0.5,
    triviaJa: '恐竜ではなく、ヘビやトカゲに非常に近い大型の海洋爬虫類で、海の最強の捕食者でした。',
    triviaEn: 'Mosasaurus was a gigantic marine reptile, related to modern monitor lizards.',
    expertKW: 'Lizard',
    expertHint: 'トカゲ',
    expertSegs: [['モササウルスの骨格は、現代の「'], ['トカゲ', 'とかげ'], ['」にきわめて近い特徴を持っていました。この「トカゲ」は英語で何でしょう？']],
    expertOpts: [['Frog', 'カエル'], ['Lizard', 'トカゲ（りざーど）'], ['Snake', 'ヘビ'], ['Bird', '鳥']],
    expertCorrect: 1,
    expertExplJa: 'Lizardは鱗を持つ爬虫類の仲間「トカゲ（リザード）」を意味します。',
    expertExplEn: 'Lizard is a reptile that typically has a long body and tail, and four legs.',
    basicKW: 'Water',
    basicHint: '水',
    basicSegs: [['彼らは陸上ではなく、大量の「'], ['水', 'みず'], ['」で満たされた海で暮らしていました。この「水」は英語で何でしょう？']],
    basicOpts: [['Fire', '火（ふぁいあ）'], ['Water', '水（うぉーたー）'], ['Stone', '石（すとーん）'], ['Wind', '風（うぃんど）']],
    basicCorrect: 1,
    basicExplJa: 'Waterは、あらゆる生命に不可欠な「水」を表す基礎英語です。',
    basicExplEn: 'Water is a colorless, transparent, odorless liquid that forms the seas.'
  },
  // 37
  {
    id: 'plesiosaurus',
    nameJa: 'プレシオサウルス',
    nameEn: 'Plesiosaurus',
    sci: 'Plesiosaurus dolichodeirus',
    phonetic: '/ˌpliːsiəˈsɔːrəs/',
    phoneticKatakana: 'プレシオサウルス',
    era: 'Jurassic',
    diet: 'Piscivore',
    length: '約3.5m',
    meaning: 'トカゲに似たもの',
    pitch: 0.78,
    triviaJa: 'ジュラ紀を代表する首長竜で、蛇腹のような首と平らなヒレ足を持ち、魚やアンモナイトを食べていました。',
    triviaEn: 'Plesiosaurus was a classic marine reptile with a snake-like neck and flippers.',
    expertKW: 'Rib',
    expertHint: 'あばら骨',
    expertSegs: [['プレシオサウルスの腹部には、体を保護する籠のような「'], ['あばら骨', 'あばらぼね'], ['」（肋骨）がありました。この「あばら骨」は？']],
    expertOpts: [['Rib', 'あばら骨（りぶ）'], ['Tooth', '歯（は）'], ['Claw', '爪（つめ）'], ['Wing', '翼（つばさ）']],
    expertCorrect: 0,
    expertExplJa: 'Ribは「あばら骨・肋骨」を意味します。',
    expertExplEn: 'Rib is any of the curved bones of the chest that protect internal organs.',
    basicKW: 'Paddle',
    basicHint: '櫂・こぐ',
    basicSegs: [['彼らは4本のヒレ足で、船の「'], ['オール', 'おーる'], ['」のように水をこいで進みました。この「櫂・オール」は英語で？']],
    basicOpts: [['Whip', '鞭（むち）'], ['Paddle', '櫂／オールでこぐ（ぱどる）'], ['Shield', '盾（しーるど）'], ['Sword', '剣（けん）']],
    basicCorrect: 1,
    basicExplJa: 'Paddleは、水を手や足で「かく」ことを言います。',
    basicExplEn: 'Paddle means to move through water using a paddle or limbs.'
  },
  // 38
  {
    id: 'ichthyosaurus',
    nameJa: 'イクチオサウルス',
    nameEn: 'Ichthyosaurus',
    sci: 'Ichthyosaurus communis',
    phonetic: '/ˌɪkθiəˈsɔːrəs/',
    phoneticKatakana: 'イクチオサウルス（魚竜）',
    era: 'Jurassic',
    diet: 'Piscivore',
    length: '約2.0m',
    meaning: '魚のトカゲ',
    pitch: 1.1,
    triviaJa: 'イルカに驚くほどそっくりな体型に収斂進化した「魚竜（ぎょりゅう）」です。巨大な目を持ち、深海でイカを狩っていました。',
    triviaEn: 'Ichthyosaurus looked exactly like a modern dolphin, adapted for high-speed swimming.',
    expertKW: 'Fish',
    expertHint: '魚',
    expertSegs: [['イルカに似ていますが、名前は「'], ['魚', 'さかな'], ['のトカゲ」という意味があります。この「魚」は英語で？']],
    expertOpts: [['Fish', '魚（ふぃっしゅ）'], ['Bird', '鳥（ばーど）'], ['Frog', 'カエル'], ['Lizard', 'トカゲ（りざーど）']],
    expertCorrect: 0,
    expertExplJa: 'Fishは水中を呼吸して泳ぐ「魚（フィッシュ）」を意味します。',
    expertExplEn: 'Fish is a cold-blooded vertebrate animal with gills and fins living wholly in water.',
    basicKW: 'Eye',
    basicHint: '目',
    basicSegs: [['深海の暗い場所でもよく見えるよう、巨大な「'], ['目', 'め'], ['」を持っていました。この「目（アイ）」を表す英語はどれでしょう？']],
    basicOpts: [['Ear', '耳（みみ）'], ['Eye', '目（め）'], ['Nose', '鼻（はな）'], ['Hand', '手（て）']],
    basicCorrect: 1,
    basicExplJa: 'Eyeは、光を感じて物を見る感覚器官「目（アイ）」を表します。',
    basicExplEn: 'Eye is the organ of sight in humans and animals.'
  },
  // 39
  {
    id: 'quetzalcoatlus',
    nameJa: 'ケツァルコアトルス',
    nameEn: 'Quetzalcoatlus',
    sci: 'Quetzalcoatlus northropi',
    phonetic: '/ˌkɛtsəlkɒˈætləs/',
    phoneticKatakana: 'ケツァルコアトルス',
    era: 'Cretaceous',
    diet: 'Carnivore',
    length: '約10.0〜11.0m',
    meaning: 'アステカの羽毛ある蛇の神（ケツァルコアトル）',
    pitch: 0.48,
    triviaJa: '史上最大の飛行生物のひとつで、翼を広げると戦闘機（F-16）並みの大きさ（約11メートル）になりました。',
    triviaEn: 'Quetzalcoatlus was one of the largest flying creatures to ever exist, as tall as a giraffe.',
    expertKW: 'Stork',
    expertHint: 'コウノトリ',
    expertSegs: [['地上では長いクチバシで現代の「'], ['コウノトリ', 'こうのとり'], ['」のように歩いて小動物を捕食していました。「コウノトリ」は英語で？']],
    expertOpts: [['Eagle', 'ワシ'], ['Ostrich', 'ダチョウ'], ['Stork', 'コウノトリ（すとーく）'], ['Duck', 'カモ']],
    expertCorrect: 2,
    expertExplJa: 'Storkは、大きくて首が長い鳥「コウノトリ（ストーク）」を指します。',
    expertExplEn: 'Stork represents a tall long-legged wading bird with a long heavy bill.',
    basicKW: 'Tall',
    basicHint: '背が高い',
    basicSegs: [['翼をたたんで地上に立つと、キリンのように非常に「'], ['背が高い', 'せがたかい'], ['」生物でした。この「背が高い」は英語で？']],
    basicOpts: [['Short', '低い（しょーと）'], ['Tall', '背が高い（とーる）'], ['Wide', '広い（わいど）'], ['Heavy', '重い（へびー）']],
    basicCorrect: 1,
    basicExplJa: 'Tallは、垂直方向の「背が高い・高い」を意味します。',
    basicExplEn: 'Tall means of great or more than average height.'
  },
  // 40
  {
    id: 'dimetrodon',
    nameJa: 'ディメトロドン',
    nameEn: 'Dimetrodon',
    sci: 'Dimetrodon grandis',
    phonetic: '/daɪˈmɛtrədɒn/',
    phoneticKatakana: 'ディメトロドン',
    era: 'Triassic',
    diet: 'Carnivore',
    length: '約3.0〜3.5m',
    meaning: '2種類のサイズの歯',
    pitch: 1.0,
    triviaJa: 'ペルム紀に繁栄した「単弓類（たんきゅうるい）」で、哺乳類の祖先に近いです。背中の大きな帆が有名です。',
    triviaEn: 'Often mistaken for a dinosaur, Dimetrodon lived before them and was closer to mammals.',
    expertKW: 'Sail',
    expertHint: '帆',
    expertSegs: [['背中にある、骨の突起と皮膜でできた巨大な「'], ['帆', 'ほ'], ['」が非常に有名です。この「帆」を表す英語はどれでしょう？']],
    expertOpts: [['Sail', '帆（せいる）'], ['Wing', '翼（うぃんぐ）'], ['Horn', '角（ほーん）'], ['Plate', '板（ぷれーと）']],
    expertCorrect: 0,
    expertExplJa: 'Sailは「帆（セイル）」を意味し、風を受けたり熱を放出する部位を指します。',
    expertExplEn: 'Sail is a structure resembling a sail, used for temperature regulation.',
    basicKW: 'Warm',
    basicHint: '温かい',
    basicSegs: [['ディメトロドンは背中の帆で太陽光を浴び、体を「'], ['温かい', 'あたたかい'], ['」状態に保ちました。この「温かい」を表す英語はどれでしょう？']],
    basicOpts: [['Cold', '冷たい（こーるど）'], ['Warm', '温かい（わーむ）'], ['Dry', '乾燥した'], ['Hard', '固い']],
    basicCorrect: 1,
    basicExplJa: 'Warmは、熱すぎず心地よい「温かい」「温暖な」を意味します。',
    basicExplEn: 'Warm means of or at a comfortable and agreeable high temperature.'
  },
  // 41
  {
    id: 'dunkleosteus',
    nameJa: 'ダンクルオステウス',
    nameEn: 'Dunkleosteus',
    sci: 'Dunkleosteus terrelli',
    phonetic: '/dʌŋkəlˈɒstiəs/',
    phoneticKatakana: 'ダンクルオステウス（板皮類）',
    era: 'Triassic',
    diet: 'Piscivore',
    length: '約6.0〜8.0m',
    meaning: 'ダンクルの骨',
    pitch: 0.55,
    triviaJa: '恐竜より前のデボン紀の海の王者で、頭部が重厚な骨板に覆われた「板皮類（ばんぴるい）」です。ハサミのような骨のプレートで噛み砕きました。',
    triviaEn: 'Dunkleosteus was a prehistoric armor-plated fish with massive bone shears instead of teeth.',
    expertKW: 'Plated',
    expertHint: '装甲板で覆われた',
    expertSegs: [['頭部がまるで戦車のように頑丈な「'], ['装甲板で覆われ', 'そうこうばんでおおわれ'], ['」ていました。この「金属や骨板で覆われた」を表す英語は？']],
    expertOpts: [['Plated', '骨板で覆われた（ぷれいてっど）'], ['Soft', '柔らかい'], ['Feathered', '羽毛がある'], ['Scaly', 'ウロコがある']],
    expertCorrect: 0,
    expertExplJa: 'Platedは、金属製や骨などの平らな厚板（プレート）で防護された状態を表します。',
    expertExplEn: 'Plated means covered with metal or bony plates for armor.',
    basicKW: 'Bite',
    basicHint: '噛む',
    basicSegs: [['彼らの「'], ['噛む', 'かむ'], ['力」は凄まじく、貝や甲殻類を粉砕しました。この「噛む、噛みつく」を表す基礎英語はどれでしょう？']],
    basicOpts: [['Sing', '歌う（しんぐ）'], ['Bite', '噛む／噛みつく（ばいと）'], ['Swim', '泳ぐ（すいむ）'], ['Jump', '跳ぶ（じゃんぷ）']],
    basicCorrect: 1,
    basicExplJa: 'Biteは、歯や口で「噛みつく・噛むこと（バイト）」を表します。',
    basicExplEn: 'Bite means to use teeth to cut, crush, or seize something.'
  },
  // 42
  {
    id: 'anomalocaris',
    nameJa: 'アノマロカリス',
    nameEn: 'Anomalocaris',
    sci: 'Anomalocaris canadensis',
    phonetic: '/əˌnɒməlɒˈkærɪs/',
    phoneticKatakana: 'アノマロカリス',
    era: 'Triassic',
    diet: 'Carnivore',
    length: '約0.6〜1.0m',
    meaning: '奇妙なエビ',
    pitch: 1.35,
    triviaJa: '約5億年前のカンブリア紀（古生代）の海における最大のハンターです。一対の触手と、パイナップルの輪切りのような丸い口を持っていました。',
    triviaEn: 'Anomalocaris was the top predator of the Cambrian seas, with giant segmented appendages.',
    expertKW: 'Abnormal',
    expertHint: '異常な・奇妙な',
    expertSegs: [['エビの化石と間違えられたことから「'], ['奇妙な', 'きみょうな'], ['エビ」と名付けられました。この「普通でない・異常な」を意味する英語は？']],
    expertOpts: [['Normal', '普通の（のーまる）'], ['Abnormal', '異常な／奇妙な（aブノーマル）'], ['Happy', '幸せな'], ['Heavy', '重い']],
    expertCorrect: 1,
    expertExplJa: 'Abnormalは、「奇妙な」「異常な」「普通ではない」を表します。',
    expertExplEn: 'Abnormal means deviating from what is normal or usual, typically in a worrisome way.',
    basicKW: 'Shrimp',
    basicHint: 'エビ',
    basicSegs: [['彼らの触手の化石が、最初は「'], ['エビ', 'えび'], ['」の胴体部分だと誤解されていました。この「エビ」を表す基礎英語はどれでしょう？']],
    basicOpts: [['Fish', '魚（ふぃっしゅ）'], ['Shrimp', 'エビ（しゅりんぷ）'], ['Bird', '鳥（ばーど）'], ['Cat', '猫（ねこ）']],
    basicCorrect: 1,
    basicExplJa: 'Shrimpは、小型の「エビ・小エビ（シュリンプ）」を意味します。',
    basicExplEn: 'Shrimp is a small free-swimming crustacean with an elongated body.'
  },
  // 43
  {
    id: 'opabinia',
    nameJa: 'オパビニア',
    nameEn: 'Opabinia',
    sci: 'Opabinia regalis',
    phonetic: '/ˌɒpəˈbɪniə/',
    phoneticKatakana: 'オパビニア',
    era: 'Triassic',
    diet: 'Carnivore',
    length: '約4.0〜7.0cm',
    meaning: 'オパビン峠の（発見地名）',
    pitch: 1.65,
    triviaJa: 'カンブリア紀の奇妙な生物で、頭に5つの目があり、先端にハサミの付いた長いノズル（管）が伸びていました。',
    triviaEn: 'Opabinia had five stalked eyes and a long nozzle claw to catch tiny sea worms.',
    expertKW: 'Five',
    expertHint: '5つ',
    expertSegs: [['オパビニアの頭には、飛び出した「'], ['5つ', 'いつつ'], ['」の目がありました。この「5つの・5」を表す英語はどれでしょう？']],
    expertOpts: [['Three', '3つ'], ['Four', '4つ'], ['Five', '5つ（ふぁいぶ）'], ['One', '1つ']],
    expertCorrect: 2,
    expertExplJa: 'Fiveは「5」「5つ」を意味する基礎数字です。',
    expertExplEn: 'Five represents the number 5, next after four.',
    basicKW: 'Trunk',
    basicHint: '象の鼻・ホース状の管',
    basicSegs: [['頭から象の「'], ['鼻', 'はな'], ['」のように長いクダが伸びていました。この「動物の鼻・管」を意味する英語は？']],
    basicOpts: [['Wing', '翼'], ['Trunk', '象の鼻／管（とらんく）'], ['Tail', '尻尾'], ['Tooth', '歯']],
    basicCorrect: 1,
    basicExplJa: 'Trunkは「ゾウの長い鼻・ホース状の管」などを指します。',
    basicExplEn: 'Trunk refers to the long, flexible nose of an elephant or similar tubelike organ.'
  },
  // 44
  {
    id: 'trilobite',
    nameJa: '三葉虫',
    nameEn: 'Trilobite',
    sci: 'Trilobita (Class)',
    phonetic: '/ˈtraɪləˌbaɪt/',
    phoneticKatakana: 'トライロバイト（三葉虫）',
    era: 'Triassic',
    diet: 'Herbivore',
    length: '約1.0〜70.0cm',
    meaning: '3つの葉に分かれたもの',
    pitch: 1.2,
    triviaJa: '古生代の海で数億年にわたって超大繁栄した甲殻類に似た節足動物です。世界各地で非常に多くの化石が見つかります。',
    triviaEn: 'Trilobites were highly successful marine arthropods that lived for 300 million years.',
    expertKW: 'Trilobite',
    expertHint: '三葉虫',
    expertSegs: [['この大繁栄した、体を縦に3つの部分に分けられる代表的な節足動物を「'], ['三葉虫', 'さんようちゅう'], ['」と呼びます。これを指す英語はどれ？']],
    expertOpts: [['Trilobite', '三葉虫（とらいろばいと）'], ['Scorpion', 'サソリ'], ['Ammonite', 'アンモナイト'], ['Shark', 'サメ']],
    expertCorrect: 0,
    expertExplJa: 'Trilobiteは、古生代を象徴する化石「三葉虫」の英語名です。',
    expertExplEn: 'Trilobite is a fossil marine arthropod that occurred abundantly in the Paleozoic.',
    basicKW: 'Bottom',
    basicHint: '底',
    basicSegs: [['三葉虫は泳ぐより、主に暗い海の「'], ['底', 'そこ'], ['」を這い回って食べ物を探していました。この「底・底面」を表す英語は？']],
    basicOpts: [['Top', '一番上（とっぷ）'], ['Bottom', '底／一番下（ぼとむ）'], ['Sky', '空（すかい）'], ['Wall', '壁（うぉーる）']],
    basicCorrect: 1,
    basicExplJa: 'Bottomは物体の最も低い場所や「底」「海底・川底」を意味する基本名詞です。',
    basicExplEn: 'Bottom is the lowest point or part of something.'
  },
  // 45
  {
    id: 'eurypterid',
    nameJa: 'ウミサソリ',
    nameEn: 'Eurypterid',
    sci: 'Eurypterida (Order)',
    phonetic: '/juːˈrɪptərid/',
    phoneticKatakana: 'ユーリプテリド（ウミサソリ）',
    era: 'Triassic',
    diet: 'Carnivore',
    length: '約2.0m',
    meaning: '広い翼（広いひれ）',
    pitch: 0.92,
    triviaJa: '古生代の浅瀬に生息していた巨大な節足動物で、現代のサソリやカブトガニに近い仲間です。平らな脚で水をこいで泳ぎ、魚を捕食しました。',
    triviaEn: 'Eurypterids, or "sea scorpions," were major aquatic predators of the Paleozoic.',
    expertKW: 'Scorpion',
    expertHint: 'サソリ',
    expertSegs: [['この恐ろしい巨大節足動物は、陸上の「'], ['サソリ', 'さそり'], ['」に姿が似ていたため「ウミサソリ」と呼ばれます。「サソリ」を表す英語はどれでしょう？']],
    expertOpts: [['Scorpion', 'サソリ（すこーぴおん）'], ['Spider', 'クモ'], ['Bee', 'ハチ'], ['Crab', 'カニ']],
    expertCorrect: 0,
    expertExplJa: 'Scorpionは、毒針付きの尾を持つ節足動物「サソリ」を表します。',
    expertExplEn: 'Scorpion is a terrestrial arachnid with lobster-like pincers and a poisonous stinger.',
    basicKW: 'Swimmer',
    basicHint: '泳ぎ手',
    basicSegs: [['ウミサソリは幅広の平らな足で水をかき、とても上手な「'], ['泳ぎ手', 'およぎて'], ['」として獲物を追跡しました。この「泳ぐ人・泳ぎ手」はどれ？']],
    basicOpts: [['Runner', '走る人'], ['Swimmer', '泳ぎ手／スイマー'], ['Flyer', '飛ぶ人'], ['Climber', '登る人']],
    basicCorrect: 1,
    basicExplJa: 'Swimmerは、水の中を泳ぐ「スイマー・泳ぎ手」を表す基礎英語です。',
    basicExplEn: 'Swimmer represents a person or animal that swims.'
  },
  // 46
  {
    id: 'megalodon',
    nameJa: 'メガロドン',
    nameEn: 'Megalodon',
    sci: 'Otodus megalodon',
    phonetic: '/ˈmɛɡələdɒn/',
    phoneticKatakana: 'メガロドン',
    era: 'Cretaceous',
    diet: 'Carnivore',
    length: '約15.0〜18.0m',
    meaning: '巨大な歯',
    pitch: 0.35,
    triviaJa: '海の歴史の中でもっとも巨大なサメで、20センチ近くある巨大な三角形の鋭い歯を何列も持っていました。',
    triviaEn: 'Megalodon was a colossal prehistoric shark with massive triangular teeth.',
    expertKW: 'Shark',
    expertHint: 'サメ',
    expertSegs: [['メガロドンは、海の歴史の中でもっとも巨大な「'], ['サメ', 'さめ'], ['」の仲間です。この「サメ」を意味する英語はどれでしょう？']],
    expertOpts: [['Whale', 'クジラ'], ['Shark', 'サメ（しゃーく）'], ['Dolphin', 'イルカ'], ['Octopus', 'タコ']],
    expertCorrect: 1,
    expertExplJa: 'Sharkは鋭い歯を持つ軟骨魚類「サメ（シャーク）」を意味します。',
    expertExplEn: 'Shark is a long-bodied chiefly marine fish with a cartilaginous skeleton.',
    basicKW: 'Teeth',
    basicHint: '歯（複数形）',
    basicSegs: [['メガロドンは強烈な噛む力と、何百本もの硬い「'], ['歯', 'は'], ['」を持っていました。この「歯（複数形）」を表す英語はどれでしょう？']],
    basicOpts: [['Tooth', '歯（単数形）'], ['Teeth', '歯（複数形／てぃーす）'], ['Nail', '爪（ねいる）'], ['Bone', '骨（ぼーん）']],
    basicCorrect: 1,
    basicExplJa: 'Teethは「歯」の複数形です。サメの歯は何度も生え変わります。',
    basicExplEn: 'Teeth is the plural form of tooth, representing multiple bony biting structures.'
  },
  // 47
  {
    id: 'mammoth',
    nameJa: 'マンモス',
    nameEn: 'Mammoth',
    sci: 'Mammuthus primigenius',
    phonetic: '/ˈmæməθ/',
    phoneticKatakana: 'マンモス',
    era: 'Cretaceous',
    diet: 'Herbivore',
    length: '約3.0〜5.0m',
    meaning: '大地の穴掘り（シベリア先住民の言葉より）',
    pitch: 0.4,
    triviaJa: '氷河期の極寒の環境に適応した、厚い毛皮で覆われた巨大なゾウの仲間です。長く湾曲した巨大なキバを持っていました。',
    triviaEn: 'Mammoth was a woolly prehistoric elephant that lived during the Ice Age.',
    expertKW: 'Tusk',
    expertHint: 'キバ',
    expertSegs: [['マンモスは、外に突き出た大きな「'], ['キバ', 'きば'], ['」を持っていました。この「象やマンモスの牙」は英語で？']],
    expertOpts: [['Tooth', '普通の歯'], ['Tusk', 'キバ（たすく）'], ['Horn', '角（つの）'], ['Claw', '爪（つめ）']],
    expertCorrect: 1,
    expertExplJa: 'Tuskは、口の外へ伸びる大きな「キバ」を指します。',
    expertExplEn: 'Tusk is a long, pointed tooth that projects outside the mouth in animals like elephants.',
    basicKW: 'Cold',
    basicHint: '冷たい・寒い',
    basicSegs: [['マンモスは、厚い氷と雪に覆われた極めて「'], ['寒い', 'さむい'], ['」地域（氷河期）で繁栄していました。この「冷たい/寒い」は英語で？']],
    basicOpts: [['Hot', '熱い（ほっと）'], ['Cold', '寒い／冷たい（こーるど）'], ['Warm', '温かい（わーむ）'], ['Dry', '乾燥した']],
    basicCorrect: 1,
    basicExplJa: 'Coldは気温が「低い」「寒い」または「冷たい」を表す基礎英語です。',
    basicExplEn: 'Cold means of or at a low temperature.'
  },
  // 48
  {
    id: 'smilodon',
    nameJa: 'スミロドン',
    nameEn: 'Smilodon',
    sci: 'Smilodon fatalis',
    phonetic: '/ˈsmaɪlədɒn/',
    phoneticKatakana: 'スミロドン（サーベルタイガー）',
    era: 'Cretaceous',
    diet: 'Carnivore',
    length: '約1.2m',
    meaning: '両刃の刀の歯',
    pitch: 0.9,
    triviaJa: '「サーベルタイガー」と呼ばれる、超巨大な2本の短剣のような犬歯を持った古代のネコ科動物です。',
    triviaEn: 'Smilodon, or "saber-toothed cat," had famously long canine teeth.',
    expertKW: 'Saber',
    expertHint: 'サーベル・軍刀',
    expertSegs: [['口から突き出た大きな犬歯は、まるで細長い「'], ['サーベル', 'さーべる'], ['」のようでした。この「刀・サーベル」を表す英語は？']],
    expertOpts: [['Saber', 'サーベル／細長い刀'], ['Shield', '盾（しーるど）'], ['Arrow', '矢（や）'], ['Whip', '鞭（むち）']],
    expertCorrect: 0,
    expertExplJa: 'Saberは、乗馬兵が使うやや湾曲した「軍刀・サーベル」を指します。',
    expertExplEn: 'Saber is a heavy cavalry sword with a curved blade.',
    basicKW: 'Cat',
    basicHint: 'ネコ',
    basicSegs: [['スミロドンは現代のトラと同じ「'], ['ネコ', 'ねこ'], ['」の仲間（ネコ科）に属しています。この「ネコ」を表す英語はどれ？']],
    basicOpts: [['Dog', '犬（どっぐ）'], ['Cat', '猫（きゃっと）'], ['Bird', '鳥（ばーど）'], ['Horse', '馬（ほーす）']],
    basicCorrect: 1,
    basicExplJa: 'Catは「ネコ」を指す基礎英単語です。スミロドンは獰猛な古代のネコでした。',
    basicExplEn: 'Cat is a small domesticated carnivorous mammal with soft fur.'
  },
  // 49
  {
    id: 'arsinoitherium',
    nameJa: 'アルシノイテリウム',
    nameEn: 'Arsinoitherium',
    sci: 'Arsinoitherium zitteli',
    phonetic: '/ˌɑːrsɪnɔɪˈθɪəriəm/',
    phoneticKatakana: 'アルシノイテリウム',
    era: 'Cretaceous',
    diet: 'Herbivore',
    length: '約3.0m',
    meaning: 'アルシノエの野獣（女王の名にちなむ）',
    pitch: 0.45,
    triviaJa: 'サイのような姿をしたゾウに近い巨大な草食哺乳類です。鼻の上に、巨大な2本の並んだ鋭いツノ（角）を持っていました。',
    triviaEn: 'Arsinoitherium looked like a rhino but had two giant bony horns side-by-side on its snout.',
    expertKW: 'Arsinoe',
    expertHint: 'アルシノエ（エジプト王妃）',
    expertSegs: [['この動物の名前は、エジプトの王妃「'], ['アルシノエ', 'あるしのえ'], ['」に由来しています。この名前はどれ？']],
    expertOpts: [['Arsinoe', 'アルシノエ（あるしのえ）'], ['Cleopatra', 'クレオパトラ'], ['Victoria', 'ビクトリア'], ['Elizabeth', 'エリザベス']],
    expertCorrect: 0,
    expertExplJa: 'Arsinoitheriumは、エジプトの女王アルシノエ2世にちなんで名付けられました。',
    expertExplEn: 'Arsinoe is the name of an ancient Egyptian queen after whom the beast was named.',
    basicKW: 'Beast',
    basicHint: '獣・野獣',
    basicSegs: [['名前の後半には、サイのように力強い「'], ['野獣', 'やじゅう'], ['」という意味が入っています。この「獣・野獣」を表す英語はどれでしょう？']],
    basicOpts: [['Bird', '鳥'], ['Fish', '魚'], ['Beast', '獣／野獣（びーすと）'], ['Insect', '昆虫']],
    basicCorrect: 2,
    basicExplJa: 'Beastは「四足の哺乳動物」や、獰猛な「野獣」「獣」を意味します。',
    basicExplEn: 'Beast represents any large four-legged mammalian animal.'
  },
  // 50
  {
    id: 'paraceratherium',
    nameJa: 'パラセラテリウム',
    nameEn: 'Paraceratherium',
    sci: 'Paraceratherium transouralicum',
    phonetic: '/ˌpærəsɛrəˈθɪəriəm/',
    phoneticKatakana: 'パラセラテリウム',
    era: 'Cretaceous',
    diet: 'Herbivore',
    length: '約7.4m',
    meaning: '角のないサイの近くのもの',
    pitch: 0.38,
    triviaJa: '地球の歴史上で最大の陸上哺乳類のひとつです。キリンのように高い木の葉を食べていました。',
    triviaEn: 'Paraceratherium was one of the largest land mammals to ever walk the earth, a hornless rhino relative.',
    expertKW: 'Hornless',
    expertHint: 'ツノのない',
    expertSegs: [['サイに近い仲間ですが、頭部に角は全く生えていませんでした。この「'], ['ツノのない', 'つののない'], ['」状態を表す英語はどれでしょう？']],
    expertOpts: [['Horned', '角が生えた'], ['Hornless', '角のない（ほーんれす）'], ['Toothed', '歯が生えた'], ['Winged', '翼がある']],
    expertCorrect: 1,
    expertExplJa: 'Hornlessは、Horn（角）に接尾辞「-less（〜のない）」が付いた「角のない」という言葉です。',
    expertExplEn: 'Hornless means lacking horns, either naturally or by dehorning.',
    basicKW: 'Tall',
    basicHint: '背が高い',
    basicSegs: [['肩の高さが5メートル近くあり、陸上の哺乳類としては最も「'], ['背が高い', 'せがたかい'], ['」部類でした。この「背が高い」を表す英語は？']],
    basicOpts: [['Short', '低い（しょーと）'], ['Tall', '背が高い（とーる）'], ['Wide', '広い（わいど）'], ['Heavy', '重い']],
    basicCorrect: 1,
    basicExplJa: 'Tallは、人や建物、背の高さなどが「高い」状態を意味する基本形容詞です。',
    basicExplEn: 'Tall means measuring a great distance from the bottom to top.'
  }
];

// Dynamically generate the full DinosaurChallenge objects at runtime to satisfy types and save bundle token space
export const DINO_CHALLENGES: DinosaurChallenge[] = RAW_DINOS.map(raw => {
  const isExpertDouble = raw.id.endsWith('_basic');
  const normalizedId = isExpertDouble ? raw.id.replace('_basic', '') : raw.id;

  const vocabQuestion: QuizQuestion = {
    japaneseSegments: raw.expertSegs.map(seg => ({ text: seg[0], ...(seg[1] ? { ruby: seg[1] } : {}) })),
    keyword: raw.expertKW,
    keywordHintJa: raw.expertHint,
    options: raw.expertOpts.map(opt => ({ text: opt[0], translation: opt[1] })),
    correctIndex: raw.expertCorrect,
    explanationJa: raw.expertExplJa,
    explanationEn: raw.expertExplEn
  };

  const basicQuestion: QuizQuestion = {
    japaneseSegments: raw.basicSegs.map(seg => ({ text: seg[0], ...(seg[1] ? { ruby: seg[1] } : {}) })),
    keyword: raw.basicKW,
    keywordHintJa: raw.basicHint,
    options: raw.basicOpts.map(opt => ({ text: opt[0], translation: opt[1] })),
    correctIndex: raw.basicCorrect,
    explanationJa: raw.basicExplJa,
    explanationEn: raw.basicExplEn
  };

  return {
    id: normalizedId,
    nameJa: raw.nameJa,
    nameEn: raw.nameEn,
    scientificName: raw.sci,
    phonetic: raw.phonetic,
    phoneticKatakana: raw.phoneticKatakana,
    era: raw.era,
    diet: raw.diet,
    length: raw.length,
    meaning: raw.meaning,
    audioPitch: raw.pitch,
    triviaJa: raw.triviaJa,
    triviaEn: raw.triviaEn,
    vocabQuestion,
    basicQuestion
  };
});
